import type { GlossaryEntry } from '../../types';

export const aleph: GlossaryEntry[] = [
  // Aleph - 𐤀
  { phoenician: '𐤀', latin: "'", meaning: { en: 'Aleph (first letter of the alphabet)', fr: 'Aleph (première lettre de l\'alphabet)', ar: 'ألف (الحرف الأول من الأبجدية)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁', latin: "'b", meaning: { en: 'Father, ancestor', fr: 'Père, ancêtre', ar: 'أب، سلف' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤃', latin: "'bd", meaning: { en: 'To perish, be lost; to destroy', fr: 'Périr, être perdu; détruire', ar: 'يهلك، يضيع؛ يدمر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤄', latin: "'bh", meaning: { en: 'To be willing, consent', fr: 'Être consentant, consentir', ar: 'يرغب، يوافق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤉', latin: "'by", meaning: { en: 'Enemy', fr: 'Ennemi', ar: 'عدو' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤉𐤓', latin: "'byr", meaning: { en: 'Mighty, strong', fr: 'Puissant, fort', ar: 'جبار، قوي' }, grammar: { pos: 'Adjective', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤉𐤕', latin: "'byt", meaning: { en: 'To mourn', fr: 'Pleurer, faire le deuil', ar: 'ينوح، يحزن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤉𐤍', latin: "'byn", meaning: { en: 'Poor, needy', fr: 'Pauvre, nécessiteux', ar: 'فقير، محتاج' }, grammar: { pos: 'Adjective', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤊', latin: "'bk", meaning: { en: 'To get entangled', fr: 'S\'emmêler, se compliquer', ar: 'يتشابك، يتعقد' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤀𐤁𐤋', latin: "'bl", meaning: { en: 'To mourn, but, truly', fr: 'Pleurer, mais, vraiment', ar: 'ينوح، لكن، حقا' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a conjunction/adverb.' } },
  { phoenician: '𐤀𐤁𐤍', latin: "'bn", meaning: { en: 'Stone', fr: 'Pierre', ar: 'حجر' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤁𐤎', latin: "'bs", meaning: { en: 'To feed, fatten', fr: 'Nourrir, engraisser', ar: 'يطعم، يسمن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤑', latin: "'bṣ", meaning: { en: 'To be strong', fr: 'Être fort', ar: 'يكون قوياً' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: '[verify]' } },
  { phoenician: '𐤀𐤁𐤒', latin: "'bq", meaning: { en: 'Dust', fr: 'Poussière', ar: 'غبار' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤂𐤃', latin: "'gd", meaning: { en: 'To bind', fr: 'Lier, attacher', ar: 'يربط، يقيد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤂𐤌', latin: "'gm", meaning: { en: 'Marsh, reed-bed', fr: 'Marais, roselière', ar: 'مستنقع، قصب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤂𐤍', latin: "'gn", meaning: { en: 'Basin, bowl', fr: 'Bassin, bol', ar: 'حوض، وعاء' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤂𐤓', latin: "'gr", meaning: { en: 'To hire, rent', fr: 'Engager, louer', ar: 'يستأجر، يؤجر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤃𐤁', latin: "'db", meaning: { en: 'To grieve', fr: 'S\'affliger, avoir du chagrin', ar: 'يحزن، يغتم' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤀𐤃𐤌', latin: "'dm", meaning: { en: 'Man, Person, mankind', fr: 'Homme, Personne, humanité', ar: 'إنسان، شخص، بشرية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤃𐤌𐤄', latin: "'dmh", meaning: { en: 'Earth, ground', fr: 'Terre, sol', ar: 'أرض، تراب' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤃𐤍', latin: "'dn", meaning: { en: 'Lord, Master', fr: 'Seigneur, Maître', ar: 'سيد، رب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤃𐤍', latin: "'dn", meaning: { en: "Adonis — a beautiful young god representing the cycle of plant growth, who dies and is resurrected", fr: "Adonis — un beau jeune dieu représentant le cycle de la croissance végétale, qui meurt et ressuscite", ar: "أدونيس — إله شاب جميل يمثل دورة نمو النبات، يموت ويبعث من جديد" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤃𐤓', latin: "'dr", meaning: { en: 'Mighty, noble, cloak', fr: 'Puissant, noble, manteau', ar: 'جبار، نبيل، عباءة' }, grammar: { pos: 'Adjective', gender: 'm', number: 's', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤄𐤃', latin: "'hd", meaning: { en: 'To grasp, hold', fr: 'Saisir, tenir', ar: 'يمسك، يقبض' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: '[verify]' } },
  { phoenician: '𐤀𐤄𐤁', latin: "'hb", meaning: { en: 'To love', fr: 'Aimer', ar: 'يحب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤄𐤋', latin: "'hl", meaning: { en: 'Tent', fr: 'Tente', ar: 'خيمة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅', latin: "'w", meaning: { en: 'Or', fr: 'Ou', ar: 'أو' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤀𐤅𐤃', latin: "'wd", meaning: { en: 'Still, yet, again', fr: 'Encore, toujours, de nouveau', ar: 'ما زال، بعد، مرة أخرى' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤅𐤄', latin: "'wh", meaning: { en: 'Desire', fr: 'Désir', ar: 'رغبة' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤀𐤅𐤉', latin: "'wy", meaning: { en: 'Alas!, Woe!', fr: 'Hélas!, Malheur!', ar: 'وا أسفاه!، ويل!' }, grammar: { pos: 'Interjection' } },
  { phoenician: '𐤀𐤅𐤋', latin: "'wl", meaning: { en: 'Child, infant', fr: 'Enfant, nourrisson', ar: 'طفل، رضيع' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤌', latin: "'wm", meaning: { en: 'If, unless', fr: 'Si, à moins que', ar: 'إذا، ما لم' }, grammar: { pos: 'Conjunction', notes: '[verify]' } },
  { phoenician: '𐤀𐤅𐤍', latin: "'wn", meaning: { en: 'Iniquity, trouble', fr: 'Iniquité, problème', ar: 'إثم، مشكلة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤐', latin: "'wp", meaning: { en: 'To fly', fr: 'Voler', ar: 'يطير' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤅𐤑𐤓', latin: "'wṣr", meaning: { en: 'Treasure, storehouse', fr: 'Trésor, entrepôt', ar: 'كنز، مخزن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤓', latin: "'wr", meaning: { en: 'Light', fr: 'Lumière', ar: 'نور' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤕', latin: "'wt", meaning: { en: 'Sign, mark', fr: 'Signe, marque', ar: 'علامة، إشارة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤆', latin: "'z", meaning: { en: 'Then, at that time', fr: 'Alors, à ce moment-là', ar: 'حينئذ، في ذلك الوقت' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤆𐤁', latin: "'zb", meaning: { en: 'To leave, abandon', fr: 'Quitter, abandonner', ar: 'يترك، يهجر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤆𐤍', latin: "'zn", meaning: { en: 'Ear', fr: 'Oreille', ar: 'أذن' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤆𐤓', latin: "'zr", meaning: { en: 'To help, aid', fr: 'Aider, secourir', ar: 'يساعد، يعين' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤇', latin: "'ḥ", meaning: { en: 'Brother', fr: 'Frère', ar: 'أخ' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤇𐤃', latin: "'ḥd", meaning: { en: 'One', fr: 'Un', ar: 'واحد' }, grammar: { pos: 'Numeral', gender: 'm' } },
  { phoenician: '𐤀𐤇𐤅𐤆', latin: "'ḥwz", meaning: { en: 'Possession, property', fr: 'Possession, propriété', ar: 'ملكية، حيازة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤇𐤅𐤕', latin: "'ḥwt", meaning: { en: 'Sisterhood', fr: 'Fraternité (sororité)', ar: 'أخوة (بين النساء)' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: '[verify]' } },
  { phoenician: '𐤀𐤇𐤆', latin: "'ḥz", meaning: { en: 'To seize, grasp', fr: 'Saisir, empoigner', ar: 'يمسك، يقبض على' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤇𐤓', latin: "'ḥr", meaning: { en: 'After, behind', fr: 'Après, derrière', ar: 'بعد، خلف' }, grammar: { pos: 'Adverb', notes: 'Also a preposition.' } },
  { phoenician: '𐤀𐤇𐤓𐤉𐤕', latin: "'ḥryt", meaning: { en: 'End, future', fr: 'Fin, avenir', ar: 'نهاية، مستقبل' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤇𐤕', latin: "'ḥt", meaning: { en: 'Sister', fr: 'Sœur', ar: 'أخت' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤈', latin: "'ṭ", meaning: { en: 'Softly, secretly', fr: 'Doucement, secrètement', ar: 'بهدوء، سرا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤉', latin: "'y", meaning: { en: 'Where?', fr: 'Où ?', ar: 'أين؟' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤉𐤁', latin: "'yb", meaning: { en: 'Enemy', fr: 'Ennemi', ar: 'عدو' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉𐤃', latin: "'yd", meaning: { en: 'Misfortune, calamity', fr: 'Malheur, calamité', ar: 'مصيبة، كارثة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉𐤊', latin: "'yk", meaning: { en: 'How?', fr: 'Comment ?', ar: 'كيف؟' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤉𐤋', latin: "'yl", meaning: { en: 'Ram, pillar, strength, terebinth', fr: 'Bélier, pilier, force, térébinthe', ar: 'كبش، عمود، قوة، بطم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉𐤋𐤍', latin: "'yln", meaning: { en: 'Tree', fr: 'Arbre', ar: 'شجرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉𐤌', latin: "'ym", meaning: { en: 'Terrible, dreadful', fr: 'Terrible, redoutable', ar: 'رهيب، مريع' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤉𐤍', latin: "'yn", meaning: { en: 'There is not', fr: 'Il n\'y a pas', ar: 'ليس هناك' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤀𐤉𐤐𐤄', latin: "'yph", meaning: { en: 'Ephah (a measure)', fr: 'Ephah (une mesure)', ar: 'إيفة (وحدة قياس)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤉𐤔', latin: "'yš", meaning: { en: 'Man, husband', fr: 'Homme, mari', ar: 'رجل، زوج' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤊', latin: "'k", meaning: { en: 'Surely, however', fr: 'Sûrement, cependant', ar: 'أكيد، لكن' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤊𐤆𐤓', latin: "'kzr", meaning: { en: 'Cruel', fr: 'Cruel', ar: 'قاسٍ' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤊𐤋', latin: "'kl", meaning: { en: 'To eat, food', fr: 'Manger, nourriture', ar: 'يأكل، طعام' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤋', latin: "'l", meaning: { en: "El, the supreme god, equivalent to Cronus", fr: "El, le dieu suprême, équivalent à Cronos", ar: "إل، الإله الأعلى عند الفينيقيين، مقابله اليوناني Cronus" }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a preposition and negative particle.' }, category: 'theonym' },
  { phoenician: '𐤀𐤋𐤂𐤁𐤉𐤔', latin: "'lgbyš", meaning: { en: 'Crystal, hail', fr: 'Cristal, grêle', ar: 'بلور، بَرَد' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: '[verify]' } },
  { phoenician: '𐤀𐤋𐤄', latin: "'lh", meaning: { en: 'Goddess; these', fr: 'Déesse; ces', ar: 'إلهة؛ هؤلاء' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Also a pronoun.' } },
  { phoenician: '𐤀𐤋𐤅𐤍', latin: "'lwn", meaning: { en: 'Oak', fr: 'Chêne', ar: 'بلوط' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤋𐤇', latin: "'lḥ", meaning: { en: 'God (Aramaic form)', fr: 'Dieu (forme araméenne)', ar: 'إله (صيغة آرامية)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤋𐤉𐤋', latin: "'lyl", meaning: { en: 'Idol, worthless', fr: 'Idole, sans valeur', ar: 'صنم، تافه' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adjective.' } },
  { phoenician: '𐤀𐤋𐤋', latin: "'ll", meaning: { en: 'To enter', fr: 'Entrer', ar: 'يدخل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤋𐤌', latin: "'lm", meaning: { en: 'Gods; silent', fr: 'Dieux; silencieux', ar: 'آلهة؛ صامت' }, grammar: { pos: 'Noun', gender: 'm', number: 'p', notes: 'Also an adjective.' } },
  { phoenician: '𐤀𐤋𐤌𐤍', latin: "'lmn", meaning: { en: 'Widow', fr: 'Veuve', ar: 'أرملة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤋𐤐', latin: "'lp", meaning: { en: 'Thousand; Ox; to teach', fr: 'Mille; Bœuf; enseigner', ar: 'ألف؛ ثور؛ يعلم' }, grammar: { pos: 'Numeral', notes: 'Also a noun and a verb.' } },
  { phoenician: '𐤀𐤌', latin: "'m", meaning: { en: 'Mother; If; cubit', fr: 'Mère; Si; coudée', ar: 'أم؛ إذا؛ ذراع' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Also a conjunction and a unit of measure.' } },
  { phoenician: '𐤀𐤌𐤄', latin: "'mh", meaning: { en: 'Maidservant', fr: 'Servante', ar: 'أمة، خادمة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤌𐤅𐤍', latin: "'mwn", meaning: { en: 'Amon (god)', fr: 'Amon (dieu)', ar: 'آمون (إله)' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Proper noun.' }, category: 'theonym' },
  { phoenician: '𐤀𐤌𐤉𐤓', latin: "'myr", meaning: { en: 'Summit, treetop', fr: 'Sommet, cime d\'arbre', ar: 'قمة، رأس الشجرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤌𐤌', latin: "'mm", meaning: { en: 'Tribe, clan', fr: 'Tribu, clan', ar: 'قبيلة، عشيرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤌𐤍', latin: "'mn", meaning: { en: 'To be firm, faithful', fr: 'Être ferme, fidèle', ar: 'يكون راسخًا، أمينًا' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤌𐤑', latin: "'mṣ", meaning: { en: 'Strong', fr: 'Fort', ar: 'قوي' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤌𐤓', latin: "'mr", meaning: { en: 'To say, speak, word', fr: 'Dire, parler, mot', ar: 'يقول، يتكلم، كلمة' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤍𐤇', latin: "'nḥ", meaning: { en: 'To sigh, groan', fr: 'Soupirer, gémir', ar: 'يتنهد، يئن' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤀𐤍𐤇𐤍𐤅', latin: "'nḥnw", meaning: { en: 'We', fr: 'Nous', ar: 'نحن' }, grammar: { pos: 'Pronoun', gender: 'c', number: 'p' } },
  { phoenician: '𐤀𐤍𐤉', latin: "'ny", meaning: { en: 'I; Ship', fr: 'Je; Navire', ar: 'أنا؛ سفينة' }, grammar: { pos: 'Pronoun', gender: 'c', number: 's', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤍𐤊', latin: "'nk", meaning: { en: 'I, me', fr: 'Je, moi', ar: 'أنا' }, grammar: { pos: 'Pronoun', gender: 'c', number: 's' } },
  { phoenician: '𐤀𐤍𐤎', latin: "'ns", meaning: { en: 'To compel, force', fr: 'Contraindre, forcer', ar: 'يجبر، يرغم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤍𐤐', latin: "'np", meaning: { en: 'Face', fr: 'Visage', ar: 'وجه' }, grammar: { pos: 'Noun', gender: 'm', number: 'p', notes: 'Dual form.' } },
  { phoenician: '𐤀𐤍𐤐', latin: "'np", meaning: { en: "Anubis — god of the afterlife, mummification, and protection of tombs", fr: "Anubis — dieu de l'au-delà, de la momification et de la protection des tombes", ar: "أنوبيس — إله الحياة الآخرة، التحنيط وحماية المقابر" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤍𐤒', latin: "'nq", meaning: { en: 'To cry out', fr: 'Pousser un cri', ar: 'يصرخ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤍𐤔', latin: "'nš", meaning: { en: 'Man, person', fr: 'Homme, personne', ar: 'رجل، شخص' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤅𐤓', latin: "'swr", meaning: { en: 'Prison, bond', fr: 'Prison, lien', ar: 'سجن، قيد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤉𐤓', latin: "'syr", meaning: { en: 'Prisoner', fr: 'Prisonnier', ar: 'سجين' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤍', latin: "'sn", meaning: { en: 'Thorn-bush', fr: 'Buisson épineux', ar: 'شجيرة شوكية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤐', latin: "'sp", meaning: { en: 'To gather, collect', fr: 'Rassembler, collecter', ar: 'يجمع، يلم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤎𐤓', latin: "'sr", meaning: { en: 'To bind, imprison', fr: 'Lier, emprisonner', ar: 'يربط، يسجن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤎𐤓', latin: "'sr", meaning: { en: "Osiris — god of the afterlife, fertility, and resurrection", fr: "Osiris — dieu de l'au-delà, de la fertilité et de la résurrection", ar: "أوزيريس — إله الحياة الآخرة والخصوبة والبعث" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤐', latin: "'p", meaning: { en: 'Nose, anger; also, too', fr: 'Nez, colère; aussi', ar: 'أنف، غضب؛ أيضاً' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adverb.' } },
  { phoenician: '𐤀𐤐𐤃', latin: "'pd", meaning: { en: 'Ephod (priestly garment)', fr: 'Éphod (vêtement sacerdotal)', ar: 'أفود (رداء كهنوتي)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤐𐤄', latin: "'ph", meaning: { en: 'To bake', fr: 'Cuire au four', ar: 'يخبز' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤐𐤉𐤋', latin: "'pyl", meaning: { en: 'Late, backward', fr: 'Tardif, en retard', ar: 'متأخر' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤐𐤒', latin: "'pq", meaning: { en: 'Channel, stream', fr: 'Canal, cours d\'eau', ar: 'قناة، مجرى' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤑𐤁𐤏', latin: "'ṣbʿ", meaning: { en: 'Finger, toe', fr: 'Doigt, orteil', ar: 'إصبع' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤑𐤉𐤋𐤄', latin: "'ṣylh", meaning: { en: 'Nobility', fr: 'Noblesse', ar: 'نبل، شرف' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤑𐤋', latin: "'ṣl", meaning: { en: 'Noble, chief', fr: 'Noble, chef', ar: 'نبيل، رئيس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤑𐤓', latin: "'ṣr", meaning: { en: 'To store, treasure', fr: 'Emmagasiner, thésauriser', ar: 'يخزن، يكنز' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤒𐤅', latin: "'qw", meaning: { en: 'Wild goat', fr: 'Chèvre sauvage', ar: 'وعل، ماعز بري' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤁', latin: "'rb", meaning: { en: 'To lie in wait, ambush', fr: 'Se poster en embuscade', ar: 'يكمن، ينصب كمينا' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤓𐤁𐤏', latin: "'rbʿ", meaning: { en: 'Four', fr: 'Quatre', ar: 'أربعة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤀𐤓𐤁𐤄', latin: "'rbh", meaning: { en: 'Locust', fr: 'Sauterelle', ar: 'جراد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤂', latin: "'rg", meaning: { en: 'To weave', fr: 'Tisser', ar: 'ينسج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤓𐤂𐤌𐤍', latin: "'rgmn", meaning: { en: 'Purple', fr: 'Pourpre', ar: 'أرجوان' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤆', latin: "'rz", meaning: { en: 'Cedar', fr: 'Cèdre', ar: 'أرز' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤇', latin: "'rḥ", meaning: { en: 'Way, path, to wander', fr: 'Chemin, sentier, errer', ar: 'طريق، درب، يهيم' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤀𐤓𐤉', latin: "'ry", meaning: { en: 'Lion', fr: 'Lion', ar: 'أسد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤊', latin: "'rk", meaning: { en: 'Long', fr: 'Long', ar: 'طويل' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤓𐤍', latin: "'rn", meaning: { en: 'Ark, chest, coffin', fr: 'Arche, coffre, cercueil', ar: 'تابوت، صندوق' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤑', latin: "'rṣ", meaning: { en: 'Earth, Land', fr: 'Terre, Pays', ar: 'أرض، بلد' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤔', latin: "'š", meaning: { en: 'Fire; Man', fr: 'Feu; Homme', ar: 'نار؛ رجل' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Man (`iš) is a different word.' } },
  { phoenician: '𐤀𐤔𐤃', latin: "'šd", meaning: { en: 'Foundation, slope', fr: 'Fondation, pente', ar: 'أساس، منحدر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤄', latin: "'šh", meaning: { en: 'Fire-offering', fr: 'Offrande par le feu', ar: 'قربان بالنار' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤊', latin: "'šk", meaning: { en: 'Testicle', fr: 'Testicule', ar: 'خصية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤊𐤓', latin: "'škr", meaning: { en: 'Payment, reward', fr: 'Paiement, récompense', ar: 'أجر، مكافأة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤌', latin: "'šm", meaning: { en: 'Guilt, trespass', fr: 'Culpabilité, transgression', ar: 'ذنب، إثم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤌𐤍', latin: "ʾšmn", meaning: { en: "Eshmun — god of healing, similar to Asklepios", fr: "Eshmun — dieu de la guérison, similaire à Asclépios", ar: "إشمون — إله الشفاء، مشابه Asklepios" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤔𐤐', latin: "'šp", meaning: { en: 'Magician, enchanter', fr: 'Magicien, enchanteur', ar: 'ساحر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤓', latin: "'šr", meaning: { en: 'Which, that, who; happy', fr: 'Qui, que; heureux', ar: 'الذي، التي؛ سعيد' }, grammar: { pos: 'Particle', notes: 'Relative particle; also an adjective.' } },
  { phoenician: '𐤀𐤔𐤕', latin: "'št", meaning: { en: 'Woman, wife', fr: 'Femme, épouse', ar: 'امرأة، زوجة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤔𐤕𐤓𐤕', latin: "ʾštrt", meaning: { en: "Astarte, goddess of love and war", fr: "Astarté, déesse de l'amour et de la guerre", ar: "أشترت / Astarte — إلهة الحب والحرب" }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤕', latin: "'t", meaning: { en: 'You (f. sg./m. sg.); with', fr: 'Tu (f. sg./m. sg.); avec', ar: 'أنتِ / أنتَ؛ مع' }, grammar: { pos: 'Pronoun', number: 's', notes: 'Also a preposition.' } },
  { phoenician: '𐤀𐤕𐤓', latin: "'tr", meaning: { en: 'Place', fr: 'Lieu', ar: 'مكان' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤕𐤌', latin: "'tm", meaning: { en: 'You (m. pl.)', fr: 'Vous (m. pl.)', ar: 'أنتم' }, grammar: { pos: 'Pronoun', gender: 'm', number: 'p' } },
  { phoenician: '𐤀𐤕𐤍', latin: "'tn", meaning: { en: 'You (f. pl.); she-donkey', fr: 'Vous (f. pl.); ânesse', ar: 'أنتن؛ أتان' }, grammar: { pos: 'Pronoun', gender: 'f', number: 'p', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤌𐤎𐤏𐤍', latin: "ʾmsʿn", meaning: { en: "Ptah-Sokar-Osiris — a Punic syncretism with Egyptian deities", fr: "Ptah-Sokar-Osiris — un syncrétisme punique avec des divinités égyptiennes", ar: "پتاح-سوقر-أوزوريس — مزج بونيقي مع المصري" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤔𐤏𐤓', latin: "ʾšʿr", meaning: { en: "Ashar — a moon god sometimes found in Phoenician inscriptions", fr: "Ashar — un dieu lunaire parfois trouvé dans les inscriptions phéniciennes", ar: "آشور / Ashar — إله القمر أحيانًا في النقوش الفينيقية" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤉𐤎', latin: "ʾst", meaning: { en: "Isis — Egyptian goddess of motherhood, magic, and healing", fr: "Isis — Déesse égyptienne de la maternité, de la magie et de la guérison", ar: "إيزيس — الإلهة المصرية للأمومة والسحر والشفاء" }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
];