import type { GlossaryEntry } from '../../types';

export const aleph: GlossaryEntry[] = [
  // Aleph - 𐤀
  { phoenician: '𐤀', latin: 'ʾ', meaning: { en: 'Aleph (first letter of the alphabet)', fr: 'Aleph (première lettre de l\'alphabet)', ar: 'ألف (الحرف الأول من الأبجدية)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁', latin: 'ʾb', meaning: { en: 'Father, ancestor', fr: 'Père, ancêtre', ar: 'أب، سلف' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤃', latin: 'ʾbd', meaning: { en: 'To perish, be lost; to destroy', fr: 'Périr, être perdu; détruire', ar: 'يهلك، يضيع؛ يدمر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤄', latin: 'ʾbh', meaning: { en: 'To be willing, consent', fr: 'Être consentant, consentir', ar: 'يرغب، يوافق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤉', latin: 'ʾby', meaning: { en: 'Enemy', fr: 'Ennemi', ar: 'عدو' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤉𐤓', latin: 'ʾbyr', meaning: { en: 'Mighty, strong', fr: 'Puissant, fort', ar: 'جبار، قوي' }, grammar: { pos: 'Adjective', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤉𐤕', latin: 'ʾbyt', meaning: { en: 'To mourn', fr: 'Pleurer, faire le deuil', ar: 'ينوح، يحزن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤉𐤍', latin: 'ʾbyn', meaning: { en: 'Poor, needy', fr: 'Pauvre, nécessiteux', ar: 'فقير، محتاج' }, grammar: { pos: 'Adjective', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤁𐤊', latin: 'ʾbk', meaning: { en: 'To get entangled', fr: 'S\'emmêler, se compliquer', ar: 'يتشابك، يتعقد' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤀𐤁𐤋', latin: 'ʾbl', meaning: { en: 'To mourn, but, truly', fr: 'Pleurer, mais, vraiment', ar: 'ينوح، لكن، حقا' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a conjunction/adverb.' } },
  { phoenician: '𐤀𐤁𐤍', latin: 'ʾbn', meaning: { en: 'Stone', fr: 'Pierre', ar: 'حجر' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤁𐤎', latin: 'ʾbs', meaning: { en: 'To feed, fatten', fr: 'Nourrir, engraisser', ar: 'يطعم، يسمن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤁𐤑', latin: 'ʾbṣ', meaning: { en: 'To be strong', fr: 'Être fort', ar: 'يكون قوياً' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: '[verify]' } },
  { phoenician: '𐤀𐤁𐤒', latin: 'ʾbq', meaning: { en: 'Dust', fr: 'Poussière', ar: 'غبار' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤂𐤃', latin: 'ʾgd', meaning: { en: 'To bind', fr: 'Lier, attacher', ar: 'يربط، يقيد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤂𐤃𐤉𐤓', latin: 'ʾgdyr', meaning: { en: 'Gadir (Cádiz, Spain)', fr: 'Gadir (Cadix, Espagne)', ar: 'غادير (قادس، إسبانيا)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤀𐤂𐤌', latin: 'ʾgm', meaning: { en: 'Marsh, reed-bed', fr: 'Marais, roselière', ar: 'مستنقع، قصب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤂𐤍', latin: 'ʾgn', meaning: { en: 'Basin, bowl', fr: 'Bassin, bol', ar: 'حوض، وعاء' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤂𐤓', latin: 'ʾgr', meaning: { en: 'To hire, rent', fr: 'Engager, louer', ar: 'يستأجر، يؤجر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤃𐤁', latin: 'ʾdb', meaning: { en: 'To grieve', fr: 'S\'affliger, avoir du chagrin', ar: 'يحزن، يغتم' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤀𐤃𐤌', latin: 'ʾdm', meaning: { en: 'Man, Person, mankind', fr: 'Homme, Personne, humanité', ar: 'إنسان، شخص، بشرية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤃𐤌𐤄', latin: 'ʾdmh', meaning: { en: 'Earth, ground', fr: 'Terre, sol', ar: 'أرض، تراب' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤃𐤍', latin: 'ʾdn', meaning: { en: 'Lord, Master', fr: 'Seigneur, Maître', ar: 'سيد، رب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤃𐤍', latin: 'ʾdn', meaning: { en: "Adonis — a beautiful young god representing the cycle of plant growth, who dies and is resurrected", fr: "Adonis — un beau jeune dieu représentant le cycle de la croissance végétale, qui meurt et ressuscite", ar: "أدونيس — إله شاب جميل يمثل دورة نمو النبات، يموت ويبعث من جديد" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤃𐤓', latin: 'ʾdr', meaning: { en: 'Mighty, noble, cloak', fr: 'Puissant, noble, manteau', ar: 'جبار، نبيل، عباءة' }, grammar: { pos: 'Adjective', gender: 'm', number: 's', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤄𐤃', latin: 'ʾhd', meaning: { en: 'To grasp, hold', fr: 'Saisir, tenir', ar: 'يمسك، يقبض' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: '[verify]' } },
  { phoenician: '𐤀𐤄𐤁', latin: 'ʾhb', meaning: { en: 'To love', fr: 'Aimer', ar: 'يحب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤄𐤋', latin: 'ʾhl', meaning: { en: 'Tent', fr: 'Tente', ar: 'خيمة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅', latin: 'ʾw', meaning: { en: 'Or', fr: 'Ou', ar: 'أو' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤀𐤅𐤃', latin: 'ʾwd', meaning: { en: 'Still, yet, again', fr: 'Encore, toujours, de nouveau', ar: 'ما زال، بعد، مرة أخرى' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤅𐤄', latin: 'ʾwh', meaning: { en: 'Desire', fr: 'Désir', ar: 'رغبة' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤀𐤅𐤉', latin: 'ʾwy', meaning: { en: 'Alas!, Woe!', fr: 'Hélas!, Malheur!', ar: 'وا أسفاه!، ويل!' }, grammar: { pos: 'Interjection' } },
  { phoenician: '𐤀𐤅𐤋', latin: 'ʾwl', meaning: { en: 'Child, infant', fr: 'Enfant, nourrisson', ar: 'طفل، رضيع' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤌', latin: 'ʾwm', meaning: { en: 'If, unless', fr: 'Si, à moins que', ar: 'إذا، ما لم' }, grammar: { pos: 'Conjunction', notes: '[verify]' } },
  { phoenician: '𐤀𐤅𐤍', latin: 'ʾwn', meaning: { en: 'Iniquity, trouble', fr: 'Iniquité, problème', ar: 'إثم، مشكلة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤐', latin: 'ʾwp', meaning: { en: 'To fly', fr: 'Voler', ar: 'يطير' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤅𐤑𐤓', latin: 'ʾwṣr', meaning: { en: 'Treasure, storehouse', fr: 'Trésor, entrepôt', ar: 'كنز، مخزن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤓', latin: 'ʾwr', meaning: { en: 'Light', fr: 'Lumière', ar: 'نور' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤅𐤕', latin: 'ʾwt', meaning: { en: 'Sign, mark', fr: 'Signe, marque', ar: 'علامة، إشارة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤆', latin: 'ʾz', meaning: { en: 'Then, at that time', fr: 'Alors, à ce moment-là', ar: 'حينئذ، في ذلك الوقت' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤆𐤁', latin: 'ʾzb', meaning: { en: 'To leave, abandon', fr: 'Quitter, abandonner', ar: 'يترك، يهجر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤆𐤍', latin: 'ʾzn', meaning: { en: 'Ear', fr: 'Oreille', ar: 'أذن' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤆𐤓', latin: 'ʾzr', meaning: { en: 'To help, aid', fr: 'Aider, secourir', ar: 'يساعد، يعين' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤇', latin: 'ʾḥ', meaning: { en: 'Brother', fr: 'Frère', ar: 'أخ' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤇𐤃', latin: 'ʾḥd', meaning: { en: 'One', fr: 'Un', ar: 'واحد' }, grammar: { pos: 'Numeral', gender: 'm' } },
  { phoenician: '𐤀𐤇𐤅𐤆', latin: 'ʾḥwz', meaning: { en: 'Possession, property', fr: 'Possession, propriété', ar: 'ملكية، حيازة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤇𐤅𐤕', latin: 'ʾḥwt', meaning: { en: 'Sisterhood', fr: 'Fraternité (sororité)', ar: 'أخوة (بين النساء)' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: '[verify]' } },
  { phoenician: '𐤀𐤇𐤆', latin: 'ʾḥz', meaning: { en: 'To seize, grasp', fr: 'Saisir, empoigner', ar: 'يمسك، يقبض على' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤇𐤓', latin: 'ʾḥr', meaning: { en: 'After, behind', fr: 'Après, derrière', ar: 'بعد، خلف' }, grammar: { pos: 'Adverb', notes: 'Also a preposition.' } },
  { phoenician: '𐤀𐤇𐤓𐤉𐤕', latin: 'ʾḥryt', meaning: { en: 'End, future', fr: 'Fin, avenir', ar: 'نهاية، مستقبل' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤇𐤕', latin: 'ʾḥt', meaning: { en: 'Sister', fr: 'Sœur', ar: 'أخت' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤈', latin: 'ʾṭ', meaning: { en: 'Softly, secretly', fr: 'Doucement, secrètement', ar: 'بهدوء، سرا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤉', latin: 'ʾy', meaning: { en: 'Where?', fr: 'Où ?', ar: 'أين؟' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤉𐤁', latin: 'ʾyb', meaning: { en: 'Enemy', fr: 'Ennemi', ar: 'عدو' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉𐤁𐤔𐤌', latin: 'ʾybšm', meaning: { en: 'Ibiza, Spain', fr: 'Ibiza, Espagne', ar: 'إيبيزا، إسبانيا' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤀𐤉𐤃', latin: 'ʾyd', meaning: { en: 'Misfortune, calamity', fr: 'Malheur, calamité', ar: 'مصيبة، كارثة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉-𐤇𐤅𐤋', latin: 'ʾy-ḥwl', meaning: { en: 'Iol (Cherchell, Algeria)', fr: 'Iol (Cherchell, Algérie)', ar: 'إيول (شرشال، الجزائر)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤀𐤉𐤊', latin: 'ʾyk', meaning: { en: 'How?', fr: 'Comment ?', ar: 'كيف؟' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤉𐤊𐤎𐤌', latin: 'ʾyksm', meaning: { en: 'Icosium (modern Algiers, Algeria)', fr: 'Icosium (actuellement Alger, Algérie)', ar: 'إيكوسيوم (الجزائر العاصمة حاليًا)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤀𐤉𐤋', latin: 'ʾyl', meaning: { en: 'Ram, pillar, strength, terebinth', fr: 'Bélier, pilier, force, térébinthe', ar: 'كبش، عمود، قوة، بطم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉𐤋𐤍', latin: 'ʾyln', meaning: { en: 'Tree', fr: 'Arbre', ar: 'شجرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤉𐤌', latin: 'ʾym', meaning: { en: 'Terrible, dreadful', fr: 'Terrible, redoutable', ar: 'رهيب، مريع' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤉𐤍', latin: 'ʾyn', meaning: { en: 'There is not', fr: 'Il n\'y a pas', ar: 'ليس هناك' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤀𐤉𐤐𐤄', latin: 'ʾyph', meaning: { en: 'Ephah (a measure)', fr: 'Ephah (une mesure)', ar: 'إيفة (وحدة قياس)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤉𐤓𐤍𐤌', latin: 'ʾyrnm', meaning: { en: 'Pantelleria', fr: 'Pantelleria', ar: 'بنتليريا (جزيرة بين صقلية وتونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤀𐤉𐤔', latin: 'ʾyš', meaning: { en: 'Man, husband', fr: 'Homme, mari', ar: 'رجل، زوج' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤊', latin: 'ʾk', meaning: { en: 'Surely, however', fr: 'Sûrement, cependant', ar: 'أكيد، لكن' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤀𐤊𐤆𐤓', latin: 'ʾkzr', meaning: { en: 'Cruel', fr: 'Cruel', ar: 'قاسٍ' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤊𐤋', latin: 'ʾkl', meaning: { en: 'To eat, food', fr: 'Manger, nourriture', ar: 'يأكل، طعام' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤋', latin: 'ʾl', meaning: { en: "El, the supreme god, equivalent to Cronus", fr: "El, le dieu suprême, équivalent à Cronos", ar: "إل، الإله الأعلى عند الفينيقيين، مقابله اليوناني Cronus" }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a preposition and negative particle.' }, category: 'theonym' },
  { phoenician: '𐤀𐤋𐤂𐤁𐤉𐤔', latin: 'ʾlgbyš', meaning: { en: 'Crystal, hail', fr: 'Cristal, grêle', ar: 'بلور، بَرَد' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: '[verify]' } },
  { phoenician: '𐤀𐤋𐤄', latin: 'ʾlh', meaning: { en: 'Goddess; these', fr: 'Déesse; ces', ar: 'إلهة؛ هؤلاء' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Also a pronoun.' } },
  { phoenician: '𐤀𐤋𐤅𐤍', latin: 'ʾlwn', meaning: { en: 'Oak', fr: 'Chêne', ar: 'بلوط' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤋𐤇', latin: 'ʾlḥ', meaning: { en: 'God (Aramaic form)', fr: 'Dieu (forme araméenne)', ar: 'إله (صيغة آرامية)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤋𐤉𐤋', latin: 'ʾlyl', meaning: { en: 'Idol, worthless', fr: 'Idole, sans valeur', ar: 'صنم، تافه' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adjective.' } },
  { phoenician: '𐤀𐤋𐤋', latin: 'ʾll', meaning: { en: 'To enter', fr: 'Entrer', ar: 'يدخل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤋𐤌', latin: 'ʾlm', meaning: { en: 'Gods; silent', fr: 'Dieux; silencieux', ar: 'آلهة؛ صامت' }, grammar: { pos: 'Noun', gender: 'm', number: 'p', notes: 'Also an adjective.' } },
  { phoenician: '𐤀𐤋𐤌𐤍', latin: 'ʾlmn', meaning: { en: 'Widow', fr: 'Veuve', ar: 'أرملة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤋𐤐', latin: 'ʾlp', meaning: { en: 'Thousand; Ox, head of cattle, bull; to teach', fr: 'Mille; Bœuf, tête de bétail, taureau; enseigner', ar: 'ألف؛ ثور، رأس ماشية؛ يعلم' }, grammar: { pos: 'Numeral', notes: 'Also a noun and a verb.' } },
  { phoenician: '𐤀𐤌', latin: 'ʾm', meaning: { en: 'Mother; If; cubit', fr: 'Mère; Si; coudée', ar: 'أم؛ إذا؛ ذراع' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Also a conjunction and a unit of measure.' } },
  { phoenician: '𐤀𐤌𐤄', latin: 'ʾmh', meaning: { en: 'Maidservant', fr: 'Servante', ar: 'أمة، خادمة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤌𐤅𐤍', latin: 'ʾmwn', meaning: { en: 'Amon (god)', fr: 'Amon (dieu)', ar: 'آمون (إله)' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Proper noun.' }, category: 'theonym' },
  { phoenician: '𐤀𐤌𐤉𐤓', latin: 'ʾmyr', meaning: { en: 'Summit, treetop', fr: 'Sommet, cime d\'arbre', ar: 'قمة، رأس الشجرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤌𐤌', latin: 'ʾmm', meaning: { en: 'Tribe, clan', fr: 'Tribu, clan', ar: 'قبيلة، عشيرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤌𐤍', latin: 'ʾmn', meaning: { en: 'To be firm, faithful', fr: 'Être ferme, fidèle', ar: 'يكون راسخًا، أمينًا' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤌𐤎𐤏𐤍', latin: "ʾmsʿn", meaning: { en: "Ptah-Sokar-Osiris — a Punic syncretism with Egyptian deities", fr: "Ptah-Sokar-Osiris — un syncrétisme punique avec des divinités égyptiennes", ar: "پتاح-سوقر-أوزوريس — مزج بونيقي مع المصري" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤌𐤑', latin: 'ʾmṣ', meaning: { en: 'Strong', fr: 'Fort', ar: 'قوي' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤌𐤓', latin: 'ʾmr', meaning: { en: 'To say, speak, word', fr: 'Dire, parler, mot', ar: 'يقول، يتكلم، كلمة' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤌𐤓', latin: 'ʾmr', meaning: { en: 'Lamb', fr: 'Agneau', ar: 'حمل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤍𐤇', latin: 'ʾnḥ', meaning: { en: 'To sigh, groan', fr: 'Soupirer, gémir', ar: 'يتنهد، يئن' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤀𐤍𐤇𐤍𐤅', latin: 'ʾnḥnw', meaning: { en: 'We', fr: 'Nous', ar: 'نحن' }, grammar: { pos: 'Pronoun', gender: 'c', number: 'p' } },
  { phoenician: '𐤀𐤍𐤉', latin: 'ʾny', meaning: { en: 'I; Ship', fr: 'Je; Navire', ar: 'أنا؛ سفينة' }, grammar: { pos: 'Pronoun', gender: 'c', number: 's', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤍𐤊', latin: 'ʾnk', meaning: { en: 'I, me', fr: 'Je, moi', ar: 'أنا' }, grammar: { pos: 'Pronoun', gender: 'c', number: 's' } },
  { phoenician: '𐤀𐤍𐤎', latin: 'ʾns', meaning: { en: 'To compel, force', fr: 'Contraindre, forcer', ar: 'يجبر، يرغم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤍𐤐', latin: 'ʾnp', meaning: { en: 'Face', fr: 'Visage', ar: 'وجه' }, grammar: { pos: 'Noun', gender: 'm', number: 'p', notes: 'Dual form.' } },
  { phoenician: '𐤀𐤍𐤐', latin: 'ʾnp', meaning: { en: "Anubis — god of the afterlife, mummification, and protection of tombs", fr: "Anubis — dieu de l'au-delà, de la momification et de la protection des tombes", ar: "أنوبيس — إله الحياة الآخرة، التحنيط وحماية المقابر" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤍𐤒', latin: 'ʾnq', meaning: { en: 'To cry out', fr: 'Pousser un cri', ar: 'يصرخ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤍𐤔', latin: 'ʾnš', meaning: { en: 'Man, person', fr: 'Homme, personne', ar: 'رجل، شخص' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤅𐤓', latin: 'ʾswr', meaning: { en: 'Prison, bond', fr: 'Prison, lien', ar: 'سجن، قيد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤉𐤓', latin: 'ʾsyr', meaning: { en: 'Prisoner', fr: 'Prisonnier', ar: 'سجين' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤍', latin: 'ʾsn', meaning: { en: 'Thorn-bush', fr: 'Buisson épineux', ar: 'شجيرة شوكية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤎𐤐', latin: 'ʾsp', meaning: { en: 'To gather, collect', fr: 'Rassembler, collecter', ar: 'يجمع، يلم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤎𐤓', latin: 'ʾsr', meaning: { en: 'To bind, imprison', fr: 'Lier, emprisonner', ar: 'يربط، يسجن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤎𐤓', latin: 'ʾsr', meaning: { en: "Osiris — god of the afterlife, fertility, and resurrection", fr: "Osiris — dieu de l'au-delà, de la fertilité et de la résurrection", ar: "أوزيريس — إله الحياة الآخرة والخصوبة والبعث" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤐', latin: 'ʾp', meaning: { en: 'Nose, anger; also, too', fr: 'Nez, colère; aussi', ar: 'أنف، غضب؛ أيضاً' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adverb.' } },
  { phoenician: '𐤀𐤐𐤃', latin: 'ʾpd', meaning: { en: 'Ephod (priestly garment)', fr: 'Éphod (vêtement sacerdotal)', ar: 'أفود (رداء كهنوتي)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤐𐤄', latin: 'ʾph', meaning: { en: 'To bake', fr: 'Cuire au four', ar: 'يخبز' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤐𐤉𐤋', latin: 'ʾpyl', meaning: { en: 'Late, backward', fr: 'Tardif, en retard', ar: 'متأخر' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤐𐤒', latin: 'ʾpq', meaning: { en: 'Channel, stream', fr: 'Canal, cours d\'eau', ar: 'قناة، مجرى' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤑𐤁𐤏', latin: 'ʾṣbʿ', meaning: { en: 'Finger, toe', fr: 'Doigt, orteil', ar: 'إصبع' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤑𐤉𐤋𐤄', latin: 'ʾṣylh', meaning: { en: 'Nobility', fr: 'Noblesse', ar: 'نبل، شرف' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤑𐤋', latin: 'ʾṣl', meaning: { en: 'Noble, chief', fr: 'Noble, chef', ar: 'نبيل، رئيس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤑𐤓', latin: 'ʾṣr', meaning: { en: 'To store, treasure', fr: 'Emmagasiner, thésauriser', ar: 'يخزن، يكنز' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤒𐤅', latin: 'ʾqw', meaning: { en: 'Wild goat', fr: 'Chèvre sauvage', ar: 'وعل، ماعز بري' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤁', latin: 'ʾrb', meaning: { en: 'To lie in wait, ambush', fr: 'Se poster en embuscade', ar: 'يكمن، ينصب كمينا' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤓𐤁𐤏', latin: 'ʾrbʿ', meaning: { en: 'Four', fr: 'Quatre', ar: 'أربعة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤀𐤓𐤁𐤄', latin: 'ʾrbh', meaning: { en: 'Locust', fr: 'Sauterelle', ar: 'جراد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤂', latin: 'ʾrg', meaning: { en: 'To weave', fr: 'Tisser', ar: 'ينسج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤀𐤓𐤂𐤌𐤍', latin: 'ʾrgmn', meaning: { en: 'Purple', fr: 'Pourpre', ar: 'أرجوان' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤉', latin: 'ʾry', meaning: { en: 'Lion', fr: 'Lion', ar: 'أسد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤊', latin: 'ʾrk', meaning: { en: 'Long', fr: 'Long', ar: 'طويل' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤀𐤓𐤍', latin: 'ʾrn', meaning: { en: 'Ark, chest, coffin', fr: 'Arche, coffre, cercueil', ar: 'تابوت، صندوق' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤆', latin: "ʾarz", meaning: { en: 'Cedar (a famous Phoenician export).', fr: 'Cèdre (une exportation phénicienne célèbre).', ar: 'أرز (من الصادرات الفينيقية الشهيرة).' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤓𐤑', latin: 'ʾrṣ', meaning: { en: 'Earth, Land', fr: 'Terre, Pays', ar: 'أرض، بلد' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤔', latin: 'ʾš', meaning: { en: 'Fire; Man', fr: 'Feu; Homme', ar: 'نار؛ رجل' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Man (`iš) is a different word.' } },
  { phoenician: '𐤀𐤔𐤁𐤍𐤉𐤀', latin: "ʾšbnyʾ", meaning: { en: 'Hispania (Spain)', fr: 'Hispanie (Espagne)', ar: 'هسبانيا (إسبانيا)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤀𐤔𐤃', latin: 'ʾšd', meaning: { en: 'Foundation, slope', fr: 'Fondation, pente', ar: 'أساس، منحدر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤄', latin: 'ʾšh', meaning: { en: 'Fire-offering', fr: 'Offrande par le feu', ar: 'قربان بالنار' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤏𐤓', latin: "ʾšʿr", meaning: { en: 'Assyria', fr: 'Assyrie', ar: 'آشور' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤀𐤔𐤏𐤓', latin: "ʾšʿr", meaning: { en: "Ashar — a moon god sometimes found in Phoenician inscriptions", fr: "Ashar — un dieu lunaire parfois trouvé dans les inscriptions phéniciennes", ar: "آشور / Ashar — إله القمر أحيانًا في النقوش الفينيقية" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤔𐤊', latin: 'ʾšk', meaning: { en: 'Testicle', fr: 'Testicule', ar: 'خصية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤊𐤓', latin: 'ʾškr', meaning: { en: 'Payment, reward', fr: 'Paiement, récompense', ar: 'أجر، مكافأة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤌', latin: 'ʾšm', meaning: { en: 'Guilt, trespass', fr: 'Culpabilité, transgression', ar: 'ذنب، إثم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤌𐤍', latin: "ʾšmn", meaning: { en: "Eshmun — god of healing, similar to Asklepios", fr: "Eshmun — dieu de la guérison, similaire à Asclépios", ar: "إشمون — إله الشفاء، مشابه Asklepios" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤔𐤐', latin: 'ʾšp', meaning: { en: 'Magician, enchanter', fr: 'Magicien, enchanteur', ar: 'ساحر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤔𐤓', latin: 'ʾšr', meaning: { en: 'Which, that, who; happy', fr: 'Qui, que; heureux', ar: 'الذي، التي؛ سعيد' }, grammar: { pos: 'Particle', notes: 'Relative particle; also an adjective.' } },
  { phoenician: '𐤀𐤔𐤕', latin: 'ʾšt', meaning: { en: 'Woman, wife', fr: 'Femme, épouse', ar: 'امرأة، زوجة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤀𐤔𐤕𐤓𐤕', latin: "ʾštrt", meaning: { en: "Astarte, goddess of love and war", fr: "Astarté, déesse de l'amour et de la guerre", ar: "أشترت / Astarte — إلهة الحب والحرب" }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤕', latin: 'ʾt', meaning: { en: 'You (f. sg./m. sg.); with', fr: 'Tu (f. sg./m. sg.); avec', ar: 'أنتِ / أنتَ؛ مع' }, grammar: { pos: 'Pronoun', number: 's', notes: 'Also a preposition.' } },
  { phoenician: '𐤀𐤕𐤓', latin: 'ʾtr', meaning: { en: 'Place', fr: 'Lieu', ar: 'مكان' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤀𐤕𐤌', latin: 'ʾtm', meaning: { en: 'You (m. pl.)', fr: 'Vous (m. pl.)', ar: 'أنتم' }, grammar: { pos: 'Pronoun', gender: 'm', number: 'p' } },
  { phoenician: '𐤀𐤕𐤍', latin: 'ʾtn', meaning: { en: 'You (f. pl.); she-donkey', fr: 'Vous (f. pl.); ânesse', ar: 'أنتن؛ أتان' }, grammar: { pos: 'Pronoun', gender: 'f', number: 'p', notes: 'Also a noun.' } },
  { phoenician: '𐤀𐤉𐤎', latin: "ʾst", meaning: { en: "Isis — Egyptian goddess of motherhood, magic, and healing", fr: "Isis — Déesse égyptienne de la maternité, de la magie et de la guérison", ar: "إيزيس — الإلهة المصرية للأمومة والسحر والشفاء" }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
  { phoenician: '𐤀𐤇𐤋𐤀𐤌𐤄', latin: 'ʾḥlʾmʾ', meaning: { en: 'Red jasper', fr: 'Jaspe rouge', ar: 'يشب أحمر' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Egyptian origin: ḫnm.t. Context: Imported along with trade goods.' } },
  { phoenician: '𐤀𐤉', latin: 'ʾy', meaning: { en: 'Coastland or island', fr: 'Côte ou île', ar: 'ساحل أو جزيرة' }, grammar: { pos: 'Noun', number: 's', notes: 'Egyptian origin: iw. Context: Borrowed from Egyptian.' } },
  { phoenician: '𐤀𐤍', latin: 'ʾn', meaning: { en: 'Craftsman or artisan', fr: 'Artisan', ar: 'حرفي أو صانع' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'From Sumerian via Akkadian, specialized craft term.' } },
  { phoenician: '𐤀𐤍𐤊', latin: 'ʾnk', meaning: { en: 'Craftsman', fr: 'Artisan', ar: 'حرفي' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Skilled laborer, from Egyptian mnḫ.' } },
  { phoenician: '𐤀𐤋𐤍', latin: 'ʾln', meaning: { en: 'Stool or throne', fr: 'Tabouret ou trône', ar: 'مقعد أو عرش' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Borrowed via Hurrian and Akkadian, related to Egyptian "support".' } },
];