import type { GlossaryEntry } from '../../types';

export const ayin: GlossaryEntry[] = [
  // Ayin - 𐤏
  { phoenician: '𐤏', latin: 'ʿ', meaning: { en: 'Ayin (sixteenth letter)', fr: 'Ayin (seizième lettre)', ar: 'عين (الحرف السادس عشر)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤏𐤁', latin: 'ʿb', meaning: { en: 'Cloud', fr: 'Nuage', ar: 'سحابة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤁𐤃', latin: 'ʿbd', meaning: { en: 'Servant, slave; to serve', fr: 'Serviteur, esclave; servir', ar: 'عبد، خادم؛ يخدم' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤏𐤁𐤓', latin: 'ʿbr', meaning: { en: 'To cross over, pass', fr: 'Traverser, passer', ar: 'يعبر، يمر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤁𐤈', latin: 'ʿbṭ', meaning: { en: 'To take a pledge', fr: 'Prendre un gage', ar: 'يأخذ رهنا' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤂𐤁', latin: 'ʿgb', meaning: { en: 'To love, have pleasure', fr: 'Aimer, avoir du plaisir', ar: 'يحب، يستمتع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤂𐤋', latin: 'ʿgl', meaning: { en: 'Calf', fr: 'Veau', ar: 'عجل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤃', latin: 'ʿd', meaning: { en: 'Until, as far as; witness', fr: 'Jusqu\'à; témoin', ar: 'حتى، إلى؛ شاهد' }, grammar: { pos: 'Preposition', notes: 'Also a noun.' } },
  { phoenician: '𐤏𐤃𐤍', latin: 'ʿdn', meaning: { en: 'Pleasure, Eden', fr: 'Plaisir, Eden', ar: 'متعة، عدن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤃𐤐', latin: 'ʿdp', meaning: { en: 'To cover, be faint', fr: 'Couvrir, s\'évanouir', ar: 'يغطي، يغمى عليه' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤅𐤃', latin: 'ʿwd', meaning: { en: 'Witness, again', fr: 'Témoin, encore', ar: 'شاهد، مرة أخرى' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adverb.' } },
  { phoenician: '𐤏𐤅𐤋𐤌', latin: 'ʿwlm', meaning: { en: 'Eternity, forever', fr: 'Éternité, pour toujours', ar: 'أبدية، إلى الأبد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤅𐤐', latin: 'ʿwp', meaning: { en: 'Bird, fowl', fr: 'Oiseau, volaille', ar: 'طائر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤅𐤓', latin: 'ʿwr', meaning: { en: 'Skin, hide; to be blind', fr: 'Peau; être aveugle', ar: 'جلد؛ يكون أعمى' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤏𐤆', latin: 'ʿz', meaning: { en: 'Goat or he-goat', fr: 'Chèvre ou bouc', ar: 'عنزة أو تيس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤆', latin: 'ʿz', meaning: { en: 'Strong, strength', fr: 'Fort, force', ar: 'قوي، قوة' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤏𐤆𐤓', latin: 'ʿzr', meaning: { en: "Azor — a local deity", fr: "Azor — une divinité locale", ar: "عزر — إله محلي" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤏𐤈', latin: 'ʿṭ', meaning: { en: 'Time', fr: 'Temps', ar: 'وقت' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤏𐤈𐤓', latin: 'ʿṭr', meaning: { en: 'Crown, to surround', fr: 'Couronne, entourer', ar: 'تاج، يحيط' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤏𐤉𐤍', latin: 'ʿyn', meaning: { en: 'Eye, spring', fr: 'Œil, source', ar: 'عين، نبع' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤏𐤉𐤓', latin: 'ʿyr', meaning: { en: 'City', fr: 'Ville', ar: 'مدينة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤏𐤋', latin: 'ʿl', meaning: { en: 'Upon, on, over', fr: 'Sur, dessus', ar: 'على، فوق' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤏𐤋𐤄', latin: 'ʿlh', meaning: { en: 'To go up', fr: 'Monter', ar: 'يصعد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤋𐤆', latin: 'ʿlz', meaning: { en: 'To exult', fr: 'Exulter', ar: 'يبتهج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤋𐤌', latin: 'ʿlm', meaning: { en: 'Young man', fr: 'Jeune homme', ar: 'شاب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤌', latin: 'ʿm', meaning: { en: 'People, nation', fr: 'Peuple, nation', ar: 'شعب، أمة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤌𐤃', latin: 'ʿmd', meaning: { en: 'To stand', fr: 'Se tenir debout', ar: 'يقف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤌𐤋', latin: 'ʿml', meaning: { en: 'Trouble, labor', fr: 'Peine, labeur', ar: 'تعب، كدح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤌𐤍', latin: 'ʿmn', meaning: { en: "Amon — The Egyptian god, appears in some Punic and Phoenician inscriptions", fr: "Amon — Le dieu égyptien, apparaît dans certaines inscriptions puniques et phéniciennes", ar: "آمون — الإله المصري، يظهر في بعض النقوش البونية والفينيقية" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤏𐤍𐤁', latin: 'ʿenob', meaning: { en: 'Grape', fr: 'Raisin', ar: 'عنب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤍𐤕', latin: 'ʿnt', meaning: { en: "Anat — goddess of war and fertility", fr: "Anat — déesse de la guerre et de la fertilité", ar: "عنات / Anat — إلهة الحرب والخصوبة" }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
  { phoenician: '𐤏𐤍𐤅', latin: 'ʿnw', meaning: { en: 'Humble, afflicted', fr: 'Humble, affligé', ar: 'متواضع، بائس' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤏𐤍𐤔', latin: 'ʿnš', meaning: { en: 'To fine, punish', fr: 'Mettre à l\'amende, punir', ar: 'يغرم، يعاقب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤐𐤅𐤍', latin: "'pwn", meaning: { en: 'Hippo (Bizerte, Tunisia & Annaba, Algeria)', fr: 'Hippone (Bizerte, Tunisie & Annaba, Algérie)', ar: 'هيبو (بنزرت، تونس وعنابة، الجزائر)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤏𐤑', latin: 'ʿṣ', meaning: { en: 'Tree, wood', fr: 'Arbre, bois', ar: 'شجرة، خشب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤑𐤌', latin: 'ʿṣm', meaning: { en: 'Bone', fr: 'Os', ar: 'عظم' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤏𐤑𐤌', latin: 'ʿṣm', meaning: { en: 'Buttocks', fr: 'Fesses', ar: 'مؤخّرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤏𐤒𐤁', latin: 'ʿqb', meaning: { en: 'Heel, to supplant', fr: 'Talon, supplanter', ar: 'عقب، يحل محل' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤏𐤒𐤓', latin: 'ʿqr', meaning: { en: 'Barren', fr: 'Stérile', ar: 'عاقر' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤏𐤓𐤁', latin: 'ʿrb', meaning: { en: 'Evening; to mix, pledge', fr: 'Soir; mélanger, garantir', ar: 'مساء؛ يخلط، يرهن' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤏𐤓𐤁𐤉', latin: 'ʿrby', meaning: { en: 'Arab, a general term for Arabs.', fr: 'Arabe, un terme général pour les Arabes.', ar: 'عربي، مصطلح عام للعرب.' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤏𐤓𐤋', latin: 'ʿrl', meaning: { en: 'Uncircumcised', fr: 'Incirconcis', ar: 'أغلف' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤏𐤓𐤐', latin: 'ʿrp', meaning: { en: 'Neck', fr: 'Cou', ar: 'عنق' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤓𐤒', latin: 'ʿrq', meaning: { en: 'Artery/Blood Vessel', fr: 'Artère/Vaisseau sanguin', ar: 'عرق' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤏𐤔𐤓', latin: 'ʿšr', meaning: { en: 'Ten', fr: 'Dix', ar: 'عشرة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤏𐤔𐤒', latin: 'ʿšq', meaning: { en: 'To oppress', fr: 'Opprimer', ar: 'يظلم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤏𐤔𐤕𐤓𐤕', latin: 'ʻštrt', meaning: { en: 'Venus (associated with Astarte)', fr: 'Vénus (associée à Astarté)', ar: 'الزهرة (مرتبط بعشتروت)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
];