import type { GlossaryEntry } from '../../types';

export const bet: GlossaryEntry[] = [
  // Bet - 𐤁
  { phoenician: '𐤁', latin: 'b', meaning: { en: 'In, at, with, by; Bet (second letter)', fr: 'Dans, à, avec, par; Bet (deuxième lettre)', ar: 'في، بـ؛ بيت (الحرف الثاني)' }, grammar: { pos: 'Preposition', notes: 'Also a noun (the letter name).' } },
  { phoenician: '𐤁𐤀', latin: "b'", meaning: { en: 'To enter, come in', fr: 'Entrer, venir dedans', ar: 'يدخل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤀𐤓', latin: "b'r", meaning: { en: 'Well, pit', fr: 'Puits, fosse', ar: 'بئر، حفرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤀𐤔', latin: "b'š", meaning: { en: 'To stink', fr: 'Puer', ar: 'ينتن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤂𐤃', latin: 'bgd', meaning: { en: 'Garment, to act treacherously', fr: 'Vêtement, agir avec traîtrise', ar: 'ثوب، يغدر' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤁𐤂𐤓', latin: 'bgr', meaning: { en: 'To be mature', fr: 'Être mature', ar: 'ينضج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤃', latin: 'bd', meaning: { en: 'In the hand of, through; linen', fr: 'Dans la main de, à travers; lin', ar: 'في يد، عبر؛ كتان' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a prepositional phrase component.' } },
  { phoenician: '𐤁𐤃𐤃', latin: 'bdd', meaning: { en: 'Alone, solitude', fr: 'Seul, solitude', ar: 'وحده، عزلة' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤁𐤃𐤋', latin: 'bdl', meaning: { en: 'To separate; Bdellium (a resin)', fr: 'Séparer; Bdellium (une résine)', ar: 'يفصل؛ مقل (صمغ)' }, grammar: { pos: 'Verb', stem: 'C-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤁𐤃𐤒', latin: 'bdq', meaning: { en: 'Fissure, breach', fr: 'Fissure, brèche', ar: 'شق، ثغرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤄𐤋', latin: 'bhl', meaning: { en: 'To be terrified, hasten', fr: 'Être terrifié, se hâter', ar: 'يرتعب، يسرع' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤁𐤄𐤌𐤄', latin: 'bhmh', meaning: { en: 'Beast, cattle', fr: 'Bête, bétail', ar: 'بهيمة، ماشية' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤄𐤓', latin: 'bhr', meaning: { en: 'To shine', fr: 'Briller', ar: 'يلمع' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: '[verify]' } },
  { phoenician: '𐤁𐤄𐤉𐤓', latin: 'bhyr', meaning: { en: 'Bright, shining', fr: 'Brillant, éclatant', ar: 'مشرق، لامع' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤁𐤅𐤀', latin: "bw'", meaning: { en: 'To come, enter', fr: 'Venir, entrer', ar: 'يأتي، يدخل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤅𐤆', latin: 'bwz', meaning: { en: 'To despise', fr: 'Mépriser', ar: 'يحتقر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤅𐤊', latin: 'bwk', meaning: { en: 'To be perplexed', fr: 'Être perplexe', ar: 'يحتار' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤁𐤅𐤓', latin: 'bwr', meaning: { en: 'Cistern, pit', fr: 'Citerne, fosse', ar: 'جب، حفرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤅𐤔', latin: 'bwš', meaning: { en: 'To be ashamed', fr: 'Avoir honte', ar: 'يخجل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤆', latin: 'bz', meaning: { en: 'Plunder, spoil', fr: 'Pillage, butin', ar: 'نهب، غنيمة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤆𐤄', latin: 'bzh', meaning: { en: 'Contempt', fr: 'Mépris', ar: 'ازدراء' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤆𐤓', latin: 'bzr', meaning: { en: 'To scatter', fr: 'Disperser', ar: 'يبعثر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤈𐤇', latin: 'bṭḥ', meaning: { en: 'To trust', fr: 'Faire confiance', ar: 'يثق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤈𐤋', latin: 'bṭl', meaning: { en: 'To cease', fr: 'Cesser', ar: 'يتوقف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤈𐤍', latin: 'bṭn', meaning: { en: 'Belly, womb', fr: 'Ventre, utérus', ar: 'بطن، رحم' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤉', latin: 'by', meaning: { en: 'Please, pray', fr: 'S\'il vous plaît, prière', ar: 'من فضلك، رجاء' }, grammar: { pos: 'Interjection' } },
  { phoenician: '𐤁𐤉𐤃', latin: 'byd', meaning: { en: 'In the hand of', fr: 'Dans la main de', ar: 'في يد' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤁𐤉𐤍', latin: 'byn', meaning: { en: 'Between, among', fr: 'Entre, parmi', ar: 'بين' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤁𐤉𐤍𐤄', latin: 'bynh', meaning: { en: 'Understanding', fr: 'Compréhension', ar: 'فهم' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤉𐤑𐤄', latin: 'byṣh', meaning: { en: 'Egg', fr: 'Œuf', ar: 'بيضة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤉𐤓', latin: 'byr', meaning: { en: 'Cistern', fr: 'Citerne', ar: 'جب' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: '[verify]' } },
  { phoenician: '𐤁𐤉𐤓𐤄', latin: 'byrh', meaning: { en: 'Palace, fortress', fr: 'Palais, forteresse', ar: 'قصر، حصن' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤉𐤕', latin: 'byt', meaning: { en: 'House, temple', fr: 'Maison, temple', ar: 'بيت، معبد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤊', latin: 'bk', meaning: { en: 'To weep', fr: 'Pleurer', ar: 'يبكي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤊𐤄', latin: 'bkh', meaning: { en: 'Weeping', fr: 'Pleurs', ar: 'بكاء' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤊𐤓', latin: 'bkr', meaning: { en: 'To be firstborn', fr: 'Être premier-né', ar: 'يكون بكرًا' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤁𐤊𐤅𐤓', latin: 'bkwr', meaning: { en: 'Firstborn', fr: 'Premier-né', ar: 'بكر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤋', latin: 'bl', meaning: { en: 'Not, without', fr: 'Ne...pas, sans', ar: 'لا، بدون' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤁𐤋𐤂', latin: 'blg', meaning: { en: 'To smile, be glad', fr: 'Sourire, être joyeux', ar: 'يبتسم، يفرح' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤁𐤋𐤄', latin: 'blh', meaning: { en: 'To wear out', fr: 'S\'user', ar: 'يبلى' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤋𐤉', latin: 'bly', meaning: { en: 'Without', fr: 'Sans', ar: 'بدون' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤁𐤋𐤉𐤏𐤋', latin: "blyʿl", meaning: { en: 'Worthlessness, wickedness', fr: 'Indignité, méchanceté', ar: 'خسة، شر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤋𐤋', latin: 'bll', meaning: { en: 'To mix, confuse', fr: 'Mélanger, confondre', ar: 'يخلط، يربك' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤋𐤌', latin: 'blm', meaning: { en: 'To restrain', fr: 'Restreindre', ar: 'يكبح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤋𐤏', latin: "blʿ", meaning: { en: 'To swallow', fr: 'Avaler', ar: 'يبتلع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤋𐤕', latin: 'blt', meaning: { en: 'Except', fr: 'Sauf', ar: 'إلا' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤁𐤋𐤕𐤉', latin: 'blty', meaning: { en: 'Not, except', fr: 'Ne...pas, sauf', ar: 'ليس، إلا' }, grammar: { pos: 'Particle', notes: 'Also preposition.' } },
  { phoenician: '𐤁𐤌𐤄', latin: 'bmh', meaning: { en: 'High place', fr: 'Haut lieu', ar: 'مرتفع، مذبح' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤍', latin: 'bn', meaning: { en: 'Son', fr: 'Fils', ar: 'ابن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤍𐤄', latin: 'bnh', meaning: { en: 'To build', fr: 'Construire', ar: 'يبني' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤎𐤌', latin: 'bsm', meaning: { en: 'Perfume, spice', fr: 'Parfum, épice', ar: 'عطر، بهار' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤎𐤓', latin: 'bsr', meaning: { en: 'Unripe grape', fr: 'Raisin vert', ar: 'حصرم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤏𐤃', latin: "bʿd", meaning: { en: 'Behind, through', fr: 'Derrière, à travers', ar: 'خلف، عبر' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤁𐤏𐤄', latin: "bʿh", meaning: { en: 'To seek, ask', fr: 'Chercher, demander', ar: 'يبحث، يسأل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤏𐤋', latin: "bʿl", meaning: { en: "Lord, master, Ba'al, husband", fr: "Seigneur, maître, Ba'al, mari", ar: 'سيد، رب، بعل، زوج' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤏𐤓', latin: "bʿr", meaning: { en: 'To burn, consume; beast', fr: 'Brûler, consommer; bête', ar: 'يحرق، يستهلك؛ بهيمة' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤁𐤏𐤕', latin: "bʿt", meaning: { en: 'To be terrified', fr: 'Être terrifié', ar: 'يرتعب' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤁𐤑', latin: 'bṣ', meaning: { en: 'Fine linen', fr: 'Lin fin', ar: 'كتان ناعم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤑𐤄', latin: 'bṣh', meaning: { en: 'Swamp, mire', fr: 'Marécage, bourbier', ar: 'مستنقع، وحل' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤑𐤏', latin: "bṣʿ", meaning: { en: 'To cut off, gain profit', fr: 'Couper, réaliser un profit', ar: 'يقطع، يربح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤑𐤒', latin: 'bṣq', meaning: { en: 'Dough', fr: 'Pâte', ar: 'عجين' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤑𐤓', latin: 'bṣr', meaning: { en: 'Fortress, to fortify', fr: 'Forteresse, fortifier', ar: 'حصن، يحصن' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤁𐤒', latin: 'bq', meaning: { en: 'To lay waste', fr: 'Dévaster', ar: 'يدمر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤒𐤏', latin: "bqʿ", meaning: { en: 'Valley, to split', fr: 'Vallée, fendre', ar: 'وادٍ، يشق' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤁𐤒𐤓', latin: 'bqr', meaning: { en: 'Cattle, morning', fr: 'Bétail, matin', ar: 'ماشية، صباح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤒𐤔', latin: 'bqš', meaning: { en: 'To seek, request', fr: 'Chercher, demander', ar: 'يبحث، يطلب' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤁𐤓', latin: 'br', meaning: { en: 'Son (Aramaic); pure; grain', fr: 'Fils (araméen); pur; grain', ar: 'ابن (آرامية)؛ نقي؛ حبوب' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adjective.' } },
  { phoenician: '𐤁𐤓𐤀', latin: "br'", meaning: { en: 'To create', fr: 'Créer', ar: 'يخلق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤓𐤃', latin: 'brd', meaning: { en: 'Hail', fr: 'Grêle', ar: 'بَرَد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤓𐤄', latin: 'brh', meaning: { en: 'To flee; food', fr: 'Fuir; nourriture', ar: 'يهرب؛ طعام' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤁𐤓𐤅𐤀', latin: "brw'", meaning: { en: 'Cypress', fr: 'Cyprès', ar: 'سرو' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤓𐤅𐤔', latin: 'brwš', meaning: { en: 'Cypress, fir', fr: 'Cyprès, sapin', ar: 'سرو، تنوب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤓𐤉', latin: 'bry', meaning: { en: 'Fat', fr: 'Gras', ar: 'سمين' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤁𐤓𐤉𐤇', latin: 'bryḥ', meaning: { en: 'Fugitive, bar', fr: 'Fugitif, barre', ar: 'هارب، عارضة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤓𐤉𐤕', latin: 'bryt', meaning: { en: 'Covenant', fr: 'Alliance', ar: 'عهد' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤓𐤊', latin: 'brk', meaning: { en: 'To bless, knee', fr: 'Bénir, genou', ar: 'يبارك، ركبة' }, grammar: { pos: 'Verb', stem: 'D-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤁𐤓𐤌', latin: 'brm', meaning: { en: 'But, however', fr: 'Mais, cependant', ar: 'لكن' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤁𐤓𐤒', latin: 'brq', meaning: { en: 'Lightning', fr: 'Éclair', ar: 'برق' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤓𐤓', latin: 'brr', meaning: { en: 'To purify', fr: 'Purifier', ar: 'يطهر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤁𐤔𐤄', latin: 'bšh', meaning: { en: 'Shame', fr: 'Honte', ar: 'خجل' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: '[verify]' } },
  { phoenician: '𐤁𐤔𐤋', latin: 'bšl', meaning: { en: 'To boil, cook', fr: 'Bouillir, cuisiner', ar: 'يغلي، يطبخ' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤁𐤔𐤌', latin: 'bšm', meaning: { en: 'Spice, balsam', fr: 'Épice, baume', ar: 'بهار، بلسم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤔𐤍', latin: 'bšn', meaning: { en: 'Shame', fr: 'Honte', ar: 'خزي' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤔𐤓', latin: 'bšr', meaning: { en: 'Flesh', fr: 'Chair', ar: 'لحم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤁𐤕', latin: 'bt', meaning: { en: 'Daughter; House of', fr: 'Fille; Maison de', ar: 'ابنة؛ بيت' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤕𐤅𐤋𐤄', latin: 'btwlh', meaning: { en: 'Virgin', fr: 'Vierge', ar: 'عذراء' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤁𐤕𐤊', latin: 'btk', meaning: { en: 'In the midst of', fr: 'Au milieu de', ar: 'في وسط' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤁𐤕𐤓', latin: 'btr', meaning: { en: 'To cut in two', fr: 'Couper en deux', ar: 'يشطر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
];
