import type { GlossaryEntry } from '../../types';

export const dalet: GlossaryEntry[] = [
  // Daleth - 𐤃
  { phoenician: '𐤃', latin: 'd', meaning: { en: 'Daleth (fourth letter)', fr: 'Daleth (quatrième lettre)', ar: 'دال (الحرف الرابع)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤀𐤁', latin: "d'b", meaning: { en: 'To languish', fr: 'Languir', ar: 'يذوي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤀𐤁𐤄', latin: "d'bh", meaning: { en: 'Languishing', fr: 'Languissant', ar: 'ذابل' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤀𐤂', latin: "d'g", meaning: { en: 'To be anxious', fr: 'Être anxieux', ar: 'يقلق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤁𐤉𐤓', latin: 'dbyr', meaning: { en: 'Inner sanctuary, oracle', fr: 'Sanctuaire intérieur, oracle', ar: 'قدس الأقداس، محراب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤁𐤒', latin: 'dbq', meaning: { en: 'To cling', fr: 'S\'attacher', ar: 'يلتصق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤁𐤓', latin: 'dbr', meaning: { en: 'Word, matter, thing, to speak', fr: 'Mot, affaire, chose, parler', ar: 'كلمة، أمر، شيء، يتكلم' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤁𐤔', latin: 'dbš', meaning: { en: 'Honey', fr: 'Miel', ar: 'عسل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤂', latin: 'dg', meaning: { en: 'Fish', fr: 'Poisson', ar: 'سمك' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤂𐤄', latin: 'dgh', meaning: { en: 'Fish (collective)', fr: 'Poissons (collectif)', ar: 'سمك (جمع)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤂𐤍', latin: 'dgn', meaning: { en: "Dagon, god of grain and fertility; also grain, corn", fr: "Dagon, dieu des céréales et de la fertilité; aussi grain, maïs", ar: "داجون، إله الحبوب والخصوبة؛ وأيضاً حبوب، غلة" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤃𐤂𐤓', latin: 'dgr', meaning: { en: 'To brood, gather', fr: 'Couver, rassembler', ar: 'يحضن، يجمع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤂𐤋', latin: 'dgl', meaning: { en: 'Banner, standard', fr: 'Bannière, étendard', ar: 'راية، علم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤃', latin: 'dd', meaning: { en: 'Beloved, uncle', fr: 'Bien-aimé, oncle', ar: 'حبيب، عم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤄𐤁', latin: 'dhb', meaning: { en: 'Gold (Aramaic)', fr: 'Or (araméen)', ar: 'ذهب (آرامية)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤅𐤃', latin: 'dwd', meaning: { en: 'Beloved, pot', fr: 'Bien-aimé, pot', ar: 'حبيب، قدر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤅𐤇', latin: 'dwḥ', meaning: { en: 'To rinse', fr: 'Rincer', ar: 'يشطف' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤃𐤅𐤊', latin: 'dwk', meaning: { en: 'To crush', fr: 'Écraser', ar: 'يسحق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤅𐤍', latin: 'dwn', meaning: { en: 'To judge', fr: 'Juger', ar: 'يحكم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤅𐤓', latin: 'dwr', meaning: { en: 'Generation, to dwell', fr: 'Génération, habiter', ar: 'جيل، يسكن' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤅𐤔', latin: 'dwš', meaning: { en: 'To thresh', fr: 'Battre (le blé)', ar: 'يدرس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤇𐤄', latin: 'dḥh', meaning: { en: 'To push, thrust', fr: 'Pousser, enfoncer', ar: 'يدفع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤉', latin: 'dy', meaning: { en: 'Sufficient, enough', fr: 'Suffisant, assez', ar: 'كافٍ' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤉𐤍', latin: 'dyn', meaning: { en: 'Judgment, to judge', fr: 'Jugement, juger', ar: 'دينونة، يحكم' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤉𐤔', latin: 'dyš', meaning: { en: 'Threshing', fr: 'Battage', ar: 'درس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤊', latin: 'dk', meaning: { en: 'Crushed', fr: 'Écrasé', ar: 'مسحوق' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤊𐤀', latin: "dk'", meaning: { en: 'To crush', fr: 'Écraser', ar: 'يسحق' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤃𐤊𐤓', latin: 'dkr', meaning: { en: 'Male', fr: 'Mâle', ar: 'ذكر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤋', latin: 'dl', meaning: { en: 'Poor, weak', fr: 'Pauvre, faible', ar: 'فقير، ضعيف' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤋𐤄', latin: 'dlh', meaning: { en: 'To draw water', fr: 'Puiser de l\'eau', ar: 'يستقي الماء' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤋𐤋', latin: 'dll', meaning: { en: 'To be low, impoverished', fr: 'Être bas, appauvri', ar: 'يكون وضيعًا، يفتقر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤋𐤒', latin: 'dlq', meaning: { en: 'To pursue, burn', fr: 'Poursuivre, brûler', ar: 'يطارد، يحترق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤋𐤕', latin: 'dlt', meaning: { en: 'Door', fr: 'Porte', ar: 'باب' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤌', latin: 'dm', meaning: { en: 'Blood', fr: 'Sang', ar: 'دم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤌𐤄', latin: 'dmh', meaning: { en: 'To be like, resemble', fr: 'Être comme, ressembler', ar: 'يشبه' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤌𐤉', latin: 'dmy', meaning: { en: 'Silence', fr: 'Silence', ar: 'صمت' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤌𐤌', latin: 'dmm', meaning: { en: 'To be silent', fr: 'Être silencieux', ar: 'يصمت' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤌𐤏', latin: "dmʿ", meaning: { en: 'Tear (from crying)', fr: 'Larme', ar: 'دمعة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤍', latin: 'dn', meaning: { en: 'To judge', fr: 'Juger', ar: 'يدين' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤏', latin: "dʿ", meaning: { en: 'Knowledge', fr: 'Connaissance', ar: 'معرفة' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤏𐤕', latin: "dʿt", meaning: { en: 'Knowledge, to know', fr: 'Connaissance, savoir', ar: 'معرفة، يعرف' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤐', latin: 'dp', meaning: { en: 'Tablet, board', fr: 'Tablette, planche', ar: 'لوح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤐𐤒', latin: 'dpq', meaning: { en: 'To knock', fr: 'Frapper (à la porte)', ar: 'يطرق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤒', latin: 'dq', meaning: { en: 'Thin, fine', fr: 'Mince, fin', ar: 'رقيق، ناعم' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤒𐤓', latin: 'dqr', meaning: { en: 'To pierce', fr: 'Percer', ar: 'يطعن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤓', latin: 'dr', meaning: { en: 'Generation', fr: 'Génération', ar: 'جيل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤓𐤁𐤍', latin: 'drbn', meaning: { en: 'Goad', fr: 'Aiguillon', ar: 'مهماز' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤓𐤅𐤌', latin: 'drwm', meaning: { en: 'South', fr: 'Sud', ar: 'جنوب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤓𐤊', latin: 'drk', meaning: { en: 'Way, path, to tread', fr: 'Chemin, sentier, fouler', ar: 'طريق، درب، يدوس' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤓𐤓', latin: 'drr', meaning: { en: 'Freedom', fr: 'Liberté', ar: 'حرية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤓𐤔', latin: 'drš', meaning: { en: 'To seek, inquire', fr: 'Chercher, s\'enquérir', ar: 'يبحث، يسأل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤔𐤀', latin: "dš'", meaning: { en: 'Grass, to sprout', fr: 'Herbe, germer', ar: 'عشب، ينبت' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤔𐤍', latin: 'dšn', meaning: { en: 'Fat, prosperous', fr: 'Gras, prospère', ar: 'سمين، مزدهر' }, grammar: { pos: 'Verb', stem: 'D-stem', notes: 'Also an adjective.' } },
];