import type { GlossaryEntry } from '../../types';

export const dalet: GlossaryEntry[] = [
  // Daleth - 𐤃
  { phoenician: '𐤃', latin: 'd', meaning: { en: 'Daleth (fourth letter)', fr: 'Daleth (quatrième lettre)', ar: 'دال (الحرف الرابع)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤀𐤁', latin: "dʾb", meaning: { en: 'To languish', fr: 'Languir', ar: 'يذوي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤀𐤁𐤄', latin: "dʾbh", meaning: { en: 'Languishing', fr: 'Languissant', ar: 'ذابل' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤀𐤂', latin: "dʾg", meaning: { en: 'To be anxious', fr: 'Être anxieux', ar: 'يقلق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤁𐤉𐤓', latin: 'dbyr', meaning: { en: 'Inner sanctuary, oracle', fr: 'Sanctuaire intérieur, oracle', ar: 'قدس الأقداس، محراب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤁𐤒', latin: 'dbq', meaning: { en: 'To cling', fr: 'S\'attacher', ar: 'يلتصق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤁𐤓', latin: 'dbr', meaning: { en: 'Cella of a temple', fr: 'Cella d\'un temple', ar: 'حجرة المعبد الداخلية (cella)' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤃𐤁𐤓', latin: 'dbr', meaning: { en: 'To say, to tell', fr: 'Dire, raconter', ar: 'يقول، يخبر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤁𐤓', latin: 'dbr', meaning: { en: 'Thing, matter, act; word, promise', fr: 'Chose, affaire, acte; mot, promesse', ar: 'شيء، أمر، فعل؛ كلمة، وعد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤁𐤓', latin: 'dbr', meaning: { en: 'Affairs, acts, history; statement, declaration', fr: 'Affaires, actes, histoire; déclaration', ar: 'شؤون، أعمال، تاريخ؛ بيان، إعلان' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' } },
  { phoenician: '𐤃𐤁𐤓𐤍', latin: 'dbrn', meaning: { en: 'Dubren, a Libyan god of the Tripolitanian hinterland in the late Roman period', fr: 'Dubren, un dieu libyen de l\'arrière-pays tripolitain à la fin de la période romaine', ar: 'دوبرن، إله ليبي في المناطق الداخلية لطرابلس في أواخر العصر الروماني' }, grammar: { pos: 'Noun' }, category: 'theonym' },
  { phoenician: '𐤃𐤁𐤔', latin: 'dbš', meaning: { en: 'Honey', fr: 'Miel', ar: 'عسل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤂', latin: 'dg', meaning: { en: 'Fish', fr: 'Poisson', ar: 'سمك' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤂𐤄', latin: 'dgh', meaning: { en: 'Fish (collective)', fr: 'Poissons (collectif)', ar: 'سمك (جمع)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤂𐤍', latin: 'dgn', meaning: { en: "Dagon, god of grain and fertility; also grain, corn", fr: "Dagon, dieu des céréales et de la fertilité; aussi grain, maïs", ar: "داجون، إله الحبوب والخصوبة؛ وأيضاً حبوب، غلة" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤃𐤂𐤓', latin: 'dgr', meaning: { en: 'To brood, gather', fr: 'Couver, rassembler', ar: 'يحضن، يجمع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤂𐤋', latin: 'dgl', meaning: { en: 'Banner, standard', fr: 'Bannière, étendard', ar: 'راية، علم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤃', latin: 'dd', meaning: { en: 'Beloved, uncle', fr: 'Bien-aimé, oncle', ar: 'حبيب، عم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤄𐤁', latin: 'dhb', meaning: { en: 'Gold (Aramaic)', fr: 'Or (araméen)', ar: 'ذهب (آرامية)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤇𐤄', latin: 'dḥh', meaning: { en: 'To push, thrust', fr: 'Pousser, enfoncer', ar: 'يدفع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤇𐤉', latin: 'dḥy', meaning: { en: 'To push down, overturn; to enlarge a building', fr: 'Renverser, retourner; agrandir un bâtiment', ar: 'يدفع للأسفل، يقلب؛ يوسع مبنى' }, grammar: { pos: 'Verb', notes: 'Variant root 𐤃𐤇𐤇 (dḥḥ).' } },
  { phoenician: '𐤃𐤋', latin: 'dl', meaning: { en: 'Poor, weak', fr: 'Pauvre, faible', ar: 'فقير، ضعيف' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤋', latin: 'dl', meaning: { en: 'Labor, toil', fr: 'Labeur, travail pénible', ar: 'كدح، عناء' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤃𐤋', latin: 'dl', meaning: { en: 'Without', fr: 'Sans', ar: 'بدون' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤃𐤋', latin: 'dl', meaning: { en: 'And, also, as well as, together with', fr: 'Et, aussi, ainsi que, avec', ar: 'و، أيضاً، كذلك، مع' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤃𐤋𐤄', latin: 'dlh', meaning: { en: 'To draw water', fr: 'Puiser de l\'eau', ar: 'يستقي الماء' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤋𐤇𐤌𐤔', latin: 'dlḥmš', meaning: { en: 'Abu Simbel in Nubia, Egypt', fr: 'Abou Simbel en Nubie, Égypte', ar: 'أبو سمبل في النوبة، مصر' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤃𐤋𐤉', latin: 'dly', meaning: { en: 'To possess, own, have', fr: 'Posséder, avoir', ar: 'يملك، يمتلك، لديه' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤃𐤋𐤋', latin: 'dll', meaning: { en: 'To be low, impoverished', fr: 'Être bas, appauvri', ar: 'يكون وضيعًا، يفتقر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤋𐤒', latin: 'dlq', meaning: { en: 'To pursue, burn', fr: 'Poursuivre, brûler', ar: 'يطارد، يحترق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤋𐤕', latin: 'dlt', meaning: { en: 'Door, panel of a gate, plaque, writing tablet, book (codex), column of a written document', fr: 'Porte, panneau de portail, plaque, tablette à écrire, livre (codex), colonne d\'un document écrit', ar: 'باب، لوح بوابة، لوحة، لوح كتابة، كتاب (مخطوطة)، عمود في وثيقة مكتوبة' }, grammar: { pos: 'Noun', gender: 'f', notes: 'Plural: 𐤃𐤋𐤇𐤕 (dlḥt)' } },
  { phoenician: '𐤃𐤌', latin: 'dm', meaning: { en: 'Blood', fr: 'Sang', ar: 'دم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤌 𐤏𐤑', latin: "dm ʿṣ", meaning: { en: 'Wine (literally "blood of the vine")', fr: 'Vin (littéralement "sang de la vigne")', ar: 'خمر (حرفيًا "دم الكرمة")' }, grammar: { pos: 'Noun', notes: 'Figurative expression.' } },
  { phoenician: '𐤃𐤌𐤄', latin: 'dmh', meaning: { en: 'To be like', fr: 'Être comme', ar: 'يشبه' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤌𐤌', latin: 'dmm', meaning: { en: 'To be silent', fr: 'Être silencieux', ar: 'يصمت' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤍', latin: 'dn', meaning: { en: 'To judge', fr: 'Juger', ar: 'يدين' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤍𐤉𐤍', latin: 'dnyn', meaning: { en: 'Danunian, an Anatolian ethnonym from the Karatepe bilingual.', fr: 'Danunien, un ethnonyme anatolien du bilingue de Karatepe.', ar: 'دنوني، اسم قومي أناضولي من نقش كاراتبه ثنائي اللغة.' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤃𐤍𐤍𐤉', latin: 'dnny', meaning: { en: 'Danunian, group local to Azatiwada (Cilicia).', fr: 'Danunien, groupe local d\'Azatiwada (Cilicie).', ar: 'دنوني، مجموعة محلية لأزاتيوادا (قيليقية).' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤃𐤍𐤍𐤉𐤌', latin: 'dnnym', meaning: { en: 'Danunians, an ethnic population of Adana (8th c. BC)', fr: 'Danuniens, une population ethnique d\'Adana (VIIIe s. av. J.-C.)', ar: 'الدانونيون، مجموعة عرقية من أضنة (القرن الثامن قبل الميلاد)' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤃𐤏𐤌', latin: "dʿm", meaning: { en: 'A god known only from personal names', fr: 'Un dieu connu seulement par les noms personnels', ar: 'إله لا يُعرف إلا من خلال الأسماء الشخصية' }, grammar: { pos: 'Noun' }, category: 'theonym' },
  { phoenician: '𐤃𐤏𐤌𐤇𐤍𐤀', latin: "dʿmḥnʾ", meaning: { en: 'Do\'m-Hanno ("Do\'m show him favor!")', fr: 'Do\'m-Hanno ("Do\'m, montre-lui ta faveur!")', ar: 'دعم حنو ("يا دعم، امنحه فضلك!")' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤃𐤏𐤌𐤌𐤋𐤊', latin: "dʿmmlk", meaning: { en: 'Do\'m-Malok ("Do\'m reigns")', fr: 'Do\'m-Malok ("Do\'m règne")', ar: 'دعم ملك ("دعم يملك")' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤃𐤏𐤌𐤑𐤋𐤇', latin: "dʿmṣlḥ", meaning: { en: 'Do\'m-Saloḥ ("Do\'m prospers")', fr: 'Do\'m-Saloḥ ("Do\'m prospère")', ar: 'دعم صلح ("دعم يزدهر")' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤃𐤏𐤌𐤔𐤌𐤏', latin: "dʿmšmʿ", meaning: { en: 'Do\'m-Shamo\' ("Do\'m, hear!")', fr: 'Do\'m-Shamo\' ("Do\'m, entends!")', ar: 'دعم شمع ("يا دعم، اسمع!")' }, grammar: { pos: 'Noun', notes: 'Reading uncertain.' }, category: 'personal_name' },
  { phoenician: '𐤃𐤏𐤄', latin: "dʿh", meaning: { en: 'Knowledge', fr: 'Connaissance', ar: 'معرفة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤏𐤕', latin: "dʿt", meaning: { en: 'Knowledge', fr: 'Connaissance', ar: 'معرفة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤃𐤏𐤕', latin: "dʿt", meaning: { en: 'Friendship', fr: 'Amitié', ar: 'صداقة' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤃𐤒', latin: 'dq', meaning: { en: 'Thin, small; finely crushed, powdered', fr: 'Mince, petit; finement broyé, en poudre', ar: 'رقيق، صغير؛ مسحوق ناعم' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤒𐤓', latin: 'dqr', meaning: { en: 'To pierce', fr: 'Percer', ar: 'يطعن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤒𐤓', latin: 'dqr', meaning: { en: 'A kind of earthen vessel', fr: 'Une sorte de récipient en terre', ar: 'نوع من الأواني الفخارية' }, grammar: { pos: 'Noun', gender: 'f', notes: 'Plural: 𐤃𐤒𐤓𐤕 (dqrt)' } },
  { phoenician: '𐤃𐤓', latin: 'dr', meaning: { en: 'Generation, period, era', fr: 'Génération, période, ère', ar: 'جيل، فترة، عصر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤓', latin: 'dr', meaning: { en: 'Family, clan', fr: 'Famille, clan', ar: 'عائلة، عشيرة' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤃𐤓 𐤁𐤍 𐤏𐤋𐤌', latin: "dr bn ʿlm", meaning: { en: 'The family of the gods, pantheon', fr: 'La famille des dieux, panthéon', ar: 'عائلة الآلهة، مجمع الآلهة' }, grammar: { pos: 'Noun', notes: 'Expression' }, category: 'theonym' },
  { phoenician: '𐤃𐤓𐤉', latin: 'dry', meaning: { en: 'Enduring, permanent', fr: 'Durable, permanent', ar: 'دائم، باقٍ' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤓𐤅𐤌', latin: 'drwm', meaning: { en: 'South', fr: 'Sud', ar: 'جنوب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤓𐤊', latin: 'drk', meaning: { en: 'Way, road', fr: 'Chemin, route', ar: 'طريق، درب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤓𐤊', latin: 'drk', meaning: { en: 'Foot soldier, infantryman', fr: 'Soldat à pied, fantassin', ar: 'جندي مشاة' }, grammar: { pos: 'Noun', gender: 'm', notes: 'Meaning is problematic.' } },
  { phoenician: '𐤃𐤓𐤓', latin: 'drr', meaning: { en: 'To flow freely', fr: 'Couler librement', ar: 'يتدفق بحرية' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤓𐤔', latin: 'drš', meaning: { en: 'To seek, inquire', fr: 'Chercher, s\'enquérir', ar: 'يبحث، يستعلم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤔𐤀', latin: "dš'", meaning: { en: 'Grass, to sprout', fr: 'Herbe, germer', ar: 'عشب، ينبت' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤔𐤍', latin: 'dšn', meaning: { en: 'Fat, prosperous', fr: 'Gras, prospère', ar: 'سمين، مزدهر' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤅𐤃', latin: 'dwd', meaning: { en: 'Beloved, pot', fr: 'Bien-aimé, pot', ar: 'حبيب، قدر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤅𐤇', latin: 'dwḥ', meaning: { en: 'To rinse', fr: 'Rincer', ar: 'يشطف' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤃𐤅𐤊', latin: 'dwk', meaning: { en: 'To crush', fr: 'Écraser', ar: 'يسحق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤅𐤍', latin: 'dwn', meaning: { en: 'To judge', fr: 'Juger', ar: 'يحكم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤅𐤓', latin: 'dwr', meaning: { en: 'Generation, to dwell', fr: 'Génération, habiter', ar: 'جيل، يسكن' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤅𐤔', latin: 'dwš', meaning: { en: 'To thresh', fr: 'Battre (le blé)', ar: 'يدرس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤃𐤊', latin: 'dk', meaning: { en: 'Crushed', fr: 'Écrasé', ar: 'مسحوق' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤃𐤊𐤀', latin: "dkʾ", meaning: { en: 'To crush', fr: 'Écraser', ar: 'يسحق' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤃𐤊𐤓', latin: 'dkr', meaning: { en: 'Male', fr: 'Mâle', ar: 'ذكر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤉', latin: 'dy', meaning: { en: 'Sufficient, enough', fr: 'Suffisant, assez', ar: 'كافٍ' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤃𐤉𐤍', latin: 'dyn', meaning: { en: 'Judgment, to judge', fr: 'Jugement, juger', ar: 'دينونة، يحكم' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤃𐤉𐤔', latin: 'dyš', meaning: { en: 'Threshing', fr: 'Battage', ar: 'درس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
];
