import type { GlossaryEntry } from '../../types';

export const gimel: GlossaryEntry[] = [
  // Gimel - 𐤂
  { phoenician: '𐤂', latin: 'g', meaning: { en: 'Gimel (third letter)', fr: 'Gimel (troisième lettre)', ar: 'جيم (الحرف الثالث)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤀𐤄', latin: "g'h", meaning: { en: 'Pride', fr: 'Orgueil', ar: 'كبرياء' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤀𐤋', latin: "g'l", meaning: { en: 'To redeem', fr: 'Racheter', ar: 'يفدي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤀𐤅𐤄', latin: "g'wh", meaning: { en: 'Arrogance, majesty', fr: 'Arrogance, majesté', ar: 'غطرسة، جلال' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤂𐤀𐤅𐤍', latin: "g'wn", meaning: { en: 'Pride', fr: 'Orgueil', ar: 'فخر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤁', latin: 'gb', meaning: { en: 'Back, hill, cistern', fr: 'Dos, colline, citerne', ar: 'ظهر، تل، جب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤁𐤄', latin: 'gbh', meaning: { en: 'High, tall', fr: 'Haut, grand', ar: 'عالٍ، طويل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤁𐤉𐤏', latin: "gbyʿ", meaning: { en: 'Cup, bowl', fr: 'Coupe, bol', ar: 'كأس، وعاء' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤁𐤉𐤍', latin: 'gbyn', meaning: { en: 'Cupola, boss', fr: 'Coupole, bosse', ar: 'قبة، نتوء' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤂𐤁𐤅𐤋', latin: 'gbwl', meaning: { en: 'Border, territory', fr: 'Frontière, territoire', ar: 'حد، إقليم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤁𐤓', latin: 'gbr', meaning: { en: 'Man, warrior', fr: 'Homme, guerrier', ar: 'رجل، محارب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤁𐤏', latin: "gbʿ", meaning: { en: 'Hill', fr: 'Colline', ar: 'تل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤂', latin: 'gg', meaning: { en: 'Roof', fr: 'Toit', ar: 'سطح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤃', latin: 'gd', meaning: { en: 'Fortune (a god)', fr: 'Fortune (un dieu)', ar: 'الحظ (إله)' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Proper noun.' } },
  { phoenician: '𐤂𐤃𐤅𐤋', latin: 'gdwl', meaning: { en: 'Great, large', fr: 'Grand', ar: 'عظيم، كبير' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤂𐤃𐤋', latin: 'gdl', meaning: { en: 'To be great', fr: 'Être grand', ar: 'يكون عظيماً' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤃𐤓', latin: 'gdr', meaning: { en: 'Wall, fence', fr: 'Mur, clôture', ar: 'جدار، سياج' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤂𐤃𐤏', latin: "gdʿ", meaning: { en: 'To cut down', fr: 'Abattre', ar: 'يقطع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤄𐤓', latin: 'ghr', meaning: { en: 'To bend down', fr: 'Se pencher', ar: 'ينحني' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤅', latin: 'gw', meaning: { en: 'Midst, interior', fr: 'Milieu, intérieur', ar: 'وسط، داخل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤅𐤋', latin: 'gwl', meaning: { en: 'To rejoice', fr: 'Se réjouir', ar: 'يبتهج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤅𐤌𐤄', latin: 'gwmh', meaning: { en: 'Pit', fr: 'Fosse', ar: 'حفرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤂𐤅𐤉', latin: 'gwy', meaning: { en: 'Nation, people', fr: 'Nation, peuple', ar: 'أمة، شعب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤅𐤓', latin: 'gwr', meaning: { en: 'To sojourn, dwell; lion cub', fr: 'Séjourner, habiter; lionceau', ar: 'يقطن، يسكن؛ شبل' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤂𐤆', latin: 'gz', meaning: { en: 'Fleece, mowing', fr: 'Toison, fauchage', ar: 'صوف، جز' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤆𐤋', latin: 'gzl', meaning: { en: 'To rob, seize', fr: 'Voler, saisir', ar: 'يسلب، يستولي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤆𐤓', latin: 'gzr', meaning: { en: 'To cut, decree', fr: 'Couper, décréter', ar: 'يقطع، يقرر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤇𐤋', latin: 'gḥl', meaning: { en: 'Coal', fr: 'Charbon', ar: 'فحم' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤂𐤉𐤋', latin: 'gyl', meaning: { en: 'To rejoice', fr: 'Se réjouir', ar: 'يفرح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤋', latin: 'gl', meaning: { en: 'Heap, wave', fr: 'Amas, vague', ar: 'كومة، موجة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤋𐤄', latin: 'glh', meaning: { en: 'To reveal, go into exile', fr: 'Révéler, s\'exiler', ar: 'يكشف، يذهب إلى المنفى' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤋𐤅𐤋', latin: 'glwl', meaning: { en: 'Idol', fr: 'Idole', ar: 'صنم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤋𐤇', latin: 'glḥ', meaning: { en: 'To shave', fr: 'Raser', ar: 'يحلق' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤂𐤋𐤋', latin: 'gll', meaning: { en: 'To roll', fr: 'Rouler', ar: 'يدحرج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤋𐤌', latin: 'glm', meaning: { en: 'To wrap up', fr: 'Envelopper', ar: 'يلف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤌', latin: 'gm', meaning: { en: 'Also, too', fr: 'Aussi', ar: 'أيضاً' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤂𐤌𐤋', latin: 'gml', meaning: { en: 'Camel; to reward, wean', fr: 'Chameau; récompenser, sevrer', ar: 'جمل؛ يكافئ، يفطم' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤂𐤌𐤓', latin: 'gmr', meaning: { en: 'To complete', fr: 'Compléter', ar: 'يكمل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤍', latin: 'gn', meaning: { en: 'Garden', fr: 'Jardin', ar: 'حديقة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤍𐤁', latin: 'gnb', meaning: { en: 'To steal', fr: 'Voler', ar: 'يسرق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤍𐤄', latin: 'gnh', meaning: { en: 'Garden', fr: 'Jardin', ar: 'بستان' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤂𐤏𐤄', latin: "gʿh", meaning: { en: 'To low, bellow', fr: 'Mugir, beugler', ar: 'يخور' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤏𐤋', latin: "gʿl", meaning: { en: 'To loathe, abhor', fr: 'Détester, abhorrer', ar: 'يمقت، يكره' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤐𐤍', latin: 'gpn', meaning: { en: 'Vine', fr: 'Vigne', ar: 'كرمة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤂𐤓', latin: 'gr', meaning: { en: 'Sojourner, stranger', fr: 'Étranger résidant', ar: 'غريب، نزيل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤓𐤀', latin: "gr'", meaning: { en: 'To gargle, throat', fr: 'Se gargariser, gorge', ar: 'يغرغر، حلق' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤂𐤓𐤁', latin: 'grb', meaning: { en: 'Scab, itch', fr: 'Gale, démangeaison', ar: 'جرب، حكة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤓𐤂𐤓', latin: 'grgr', meaning: { en: 'To saw, throat', fr: 'Scier, gorge', ar: 'ينشر، حلق' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤂𐤓𐤆𐤍', latin: 'grzn', meaning: { en: 'Axe', fr: 'Hache', ar: 'فأس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤓𐤌', latin: 'grm', meaning: { en: 'Bone, self', fr: 'Os, soi-même', ar: 'عظم، نفس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤓𐤍', latin: 'grn', meaning: { en: 'Threshing floor', fr: 'Aire de battage', ar: 'بيدر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤓𐤎', latin: 'grs', meaning: { en: 'Grits, crushed grain', fr: 'Gruau, grain concassé', ar: 'جريش، حبوب مطحونة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤂𐤓𐤏', latin: "grʿ", meaning: { en: 'To diminish, lessen', fr: 'Diminuer, réduire', ar: 'ينقص، يقلل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤓𐤔', latin: 'grš', meaning: { en: 'To drive out, expel', fr: 'Chasser, expulser', ar: 'يطرد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤂𐤔𐤌', latin: 'gšm', meaning: { en: 'Rain', fr: 'Pluie', ar: 'مطر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
];
