import type { GlossaryEntry } from '../../types';

export const he: GlossaryEntry[] = [
  // He - 𐤄
  { phoenician: '𐤄', latin: 'h', meaning: { en: 'He (fifth letter)', fr: 'He (cinquième lettre)', ar: 'هاء (الحرف الخامس)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤄-', latin: 'h-', meaning: { en: 'The (definite article)', fr: 'Le, la, les (article défini)', ar: 'الـ (أداة التعريف)' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤄𐤀', latin: "hʾ", meaning: { en: 'Behold, lo!', fr: 'Voici, voilà!', ar: 'ها هو!' }, grammar: { pos: 'Interjection' } },
  { phoenician: '𐤄𐤀𐤕', latin: "hʾt", meaning: { en: 'This', fr: 'Ceci', ar: 'هذا' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤄𐤁𐤋', latin: 'hbl', meaning: { en: 'Vapor, vanity', fr: 'Vapeur, vanité', ar: 'بخار، باطل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤂𐤄', latin: 'hgh', meaning: { en: 'To meditate, mutter', fr: 'Méditer, murmurer', ar: 'يتأمل، يهمهم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤃𐤌', latin: 'hdm', meaning: { en: 'Footstool', fr: 'Marchepied', ar: 'موطئ قدم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤃𐤓', latin: 'hdr', meaning: { en: 'Splendor, majesty', fr: 'Splendeur, majesté', ar: 'بهاء، جلال' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤃𐤅𐤌', latin: 'hdwm', meaning: { en: 'Stool', fr: 'Tabouret', ar: 'مقعد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤅𐤀', latin: "hwʾ", meaning: { en: 'He, it', fr: 'Il', ar: 'هو' }, grammar: { pos: 'Pronoun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤅𐤃', latin: 'hwd', meaning: { en: 'Splendor', fr: 'Splendeur', ar: 'بهاء' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤅𐤄', latin: 'hwh', meaning: { en: 'To fall, happen', fr: 'Tomber, arriver', ar: 'يسقط، يحدث' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤅𐤍', latin: 'hwn', meaning: { en: 'Wealth', fr: 'Richesse', ar: 'ثروة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤉𐤀', latin: "hyʾ", meaning: { en: 'She, it', fr: 'Elle', ar: 'هي' }, grammar: { pos: 'Pronoun', gender: 'f', number: 's' } },
  { phoenician: '𐤄𐤉𐤄', latin: 'hyh', meaning: { en: 'To be, become', fr: 'Être, devenir', ar: 'يكون، يصبح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤉𐤊𐤋', latin: 'hykl', meaning: { en: 'Palace, temple', fr: 'Palais, temple', ar: 'قصر، هيكل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤋𐤀', latin: "hlʾ", meaning: { en: 'Further, beyond', fr: 'Plus loin, au-delà', ar: 'أبعد، وراء' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'To walk, go', fr: 'Marcher, aller', ar: 'يمشي، يذهب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤋𐤋', latin: 'hll', meaning: { en: 'To praise, shine', fr: 'Louer, briller', ar: 'يسبح، يلمع' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤄𐤋𐤌', latin: 'hlm', meaning: { en: 'Hither, here', fr: 'Ici', ar: 'هنا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤄𐤌', latin: 'hm', meaning: { en: 'They (m.)', fr: 'Ils', ar: 'هم' }, grammar: { pos: 'Pronoun', gender: 'm', number: 'p' } },
  { phoenician: '𐤄𐤌𐤅𐤍', latin: 'hmwn', meaning: { en: 'Multitude, tumult', fr: 'Multitude, tumulte', ar: 'جمهور، ضجة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤌𐤄', latin: 'hmh', meaning: { en: 'To be noisy, make noise, roar', fr: 'Être bruyant, faire du bruit, rugir', ar: 'يضج، يصخب، يزأر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤌𐤕', latin: 'hmt', meaning: { en: 'They', fr: 'Ils/Elles', ar: 'هم/هن' }, grammar: { pos: 'Pronoun', gender: 'c', number: 'p' } },
  { phoenician: '𐤄𐤍', latin: 'hn', meaning: { en: 'Behold; they (f.)', fr: 'Voici; elles', ar: 'ها هن؛ هن' }, grammar: { pos: 'Interjection', notes: 'Also a pronoun.' } },
  { phoenician: '𐤄𐤍𐤄', latin: 'hnh', meaning: { en: 'Behold!', fr: 'Voici!', ar: 'ها هو!' }, grammar: { pos: 'Interjection' } },
  { phoenician: '𐤄𐤎𐤎', latin: 'hss', meaning: { en: 'To incite, keep silent', fr: 'Inciter, garder le silence', ar: 'يحرض، يصمت' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤄𐤐𐤊', latin: 'hpk', meaning: { en: 'To overturn, change', fr: 'Renverser, changer', ar: 'يقلب، يغير' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤓', latin: 'hr', meaning: { en: 'Mountain', fr: 'Montagne', ar: 'جبل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤓𐤀', latin: "hrʾ", meaning: { en: 'Excrement', fr: 'Excrément', ar: 'براز' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: '[verify]' } },
  { phoenician: '𐤄𐤓𐤂', latin: 'hrg', meaning: { en: 'To kill, slay', fr: 'Tuer', ar: 'يقتل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤓𐤄', latin: 'hrh', meaning: { en: 'To conceive, be pregnant', fr: 'Concevoir, être enceinte', ar: 'تحبل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤓𐤓', latin: 'hrr', meaning: { en: 'To be pregnant, conceive', fr: 'Être enceinte, concevoir', ar: 'تكون حاملاً، تحبل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤓𐤎', latin: 'hrs', meaning: { en: 'To demolish, destroy', fr: 'Démolir, détruire', ar: 'يهدم، يدمر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤕𐤋', latin: 'htl', meaning: { en: 'To mock', fr: 'Se moquer', ar: 'يسخر' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
];