
import type { GlossaryEntry } from '../../types';

export const he: GlossaryEntry[] = [
  // He - 𐤄
  { phoenician: '𐤄', latin: 'h', meaning: { en: 'He (fifth letter)', fr: 'He (cinquième lettre)', ar: 'هاء (الحرف الخامس)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤄-', latin: 'h-', meaning: { en: 'The (definite article)', fr: 'Le, la, les (article défini)', ar: 'الـ (أداة التعريف)' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤄𐤀', latin: "hʾ", meaning: { en: 'Behold, lo!', fr: 'Voici, voilà!', ar: 'ها هو!' }, grammar: { pos: 'Interjection' } },
  { phoenician: '𐤄𐤀', latin: 'hʾ', meaning: { en: 'HE, subject of a non-verbal sentence', fr: 'LUI, sujet d\'une phrase non verbale', ar: 'هو، مبتدأ في جملة اسمية' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤄𐤀', latin: 'hʾ', meaning: { en: 'THAT, the aforementioned (anaphoric pronoun)', fr: 'CELA, ce qui a été mentionné précédemment (pronom anaphorique)', ar: 'ذلك، المذكور آنفًا (ضمير إشاري)' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤄𐤀', latin: 'hʾ', meaning: { en: 'SHE', fr: 'ELLE', ar: 'هي' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤄𐤀', latin: 'hʾ', meaning: { en: 'Presentative, introducing a declarative sentence', fr: 'Présentatif, introduisant une phrase déclarative', ar: 'أداة تقديم، تفتتح جملة خبرية' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤄𐤀', latin: 'hʾ', meaning: { en: 'Obscure female deity', fr: 'Divinité féminine obscure', ar: 'إلهة غامضة' }, grammar: { pos: 'Noun' }, category: 'theonym' },
  { phoenician: '𐤄𐤀𐤕', latin: "hʾt", meaning: { en: 'This', fr: 'Ceci', ar: 'هذا' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤄𐤀𐤕', latin: 'hʾt', meaning: { en: 'HE (historically, the oblique form)', fr: 'LUI (historiquement, la forme oblique)', ar: 'هو (تاريخيًا، صيغة المفعولية)' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤄𐤁𐤋', latin: 'hbl', meaning: { en: 'Vapor, vanity', fr: 'Vapeur, vanité', ar: 'بخار، باطل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤂𐤄', latin: 'hgh', meaning: { en: 'To meditate, mutter', fr: 'Méditer, murmurer', ar: 'يتأمل، يهمهم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤃𐤌', latin: 'hdm', meaning: { en: 'Footstool', fr: 'Marchepied', ar: 'موطئ قدم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤃𐤓', latin: 'hdr', meaning: { en: 'Splendor, majesty', fr: 'Splendeur, majesté', ar: 'بهاء، جلال' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤃𐤅𐤌', latin: 'hdwm', meaning: { en: 'Stool', fr: 'Tabouret', ar: 'مقعد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤅𐤀', latin: "hwʾ", meaning: { en: 'He, it', fr: 'Il', ar: 'هو' }, grammar: { pos: 'Pronoun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤅𐤃', latin: 'hwd', meaning: { en: 'Splendor', fr: 'Splendeur', ar: 'بهاء' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤅𐤄', latin: 'hwh', meaning: { en: 'To fall, happen', fr: 'Tomber, arriver', ar: 'يسقط، يحدث' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤅𐤍', latin: 'hwn', meaning: { en: 'Wealth', fr: 'Richesse', ar: 'ثروة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤉𐤀', latin: "hyʾ", meaning: { en: 'She, it', fr: 'Elle', ar: 'هي' }, grammar: { pos: 'Pronoun', gender: 'f', number: 's' } },
  { phoenician: '𐤄𐤉𐤄', latin: 'hyh', meaning: { en: 'To be, become', fr: 'Être, devenir', ar: 'يكون، يصبح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤉𐤊𐤋', latin: 'hykl', meaning: { en: 'Palace, temple', fr: 'Palais, temple', ar: 'قصر، هيكل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤋𐤀', latin: "hlʾ", meaning: { en: 'Further, beyond', fr: 'Plus loin, au-delà', ar: 'أبعد، وراء' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'To walk, go', fr: 'Marcher, aller', ar: 'يمشي، يذهب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'go, go away', fr: 'aller, s\'en aller', ar: 'يذهب، يرحل' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'go on military campaign, proceed, march (of an army)', fr: 'partir en campagne militaire, avancer, marcher (d\'une armée)', ar: 'يذهب في حملة عسكرية، يتقدم، يسير (للجيش)' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'walk, travel', fr: 'marcher, voyager', ar: 'يمشي، يسافر' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'cause to go, send', fr: 'faire aller, envoyer', ar: 'يجعل يذهب، يرسل' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'bring', fr: 'apporter', ar: 'يحضر' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'host, guest-friend', fr: 'hôte, ami invité', ar: 'مضيف، صديق ضيف' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤄𐤋𐤊', latin: 'hlk', meaning: { en: 'traveller, passer-by', fr: 'voyageur, passant', ar: 'مسافر، عابر سبيل' }, grammar: { pos: 'Noun' } },
  { phoenician: '𐤄𐤋𐤊𐤕', latin: 'hlkt', meaning: { en: 'hospitality, guest-friendship', fr: 'hospitalité, amitié d\'invité', ar: 'ضيافة، صداقة ضيف' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤄𐤋𐤋', latin: 'hll', meaning: { en: 'To praise, shine', fr: 'Louer, briller', ar: 'يسبح، يلمع' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤄𐤋𐤌', latin: 'hlm', meaning: { en: 'Hither, here', fr: 'Ici', ar: 'هنا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤄𐤋𐤌', latin: 'hlm', meaning: { en: 'Presentative particle used to introduce a declarative sentence (“behold,” “here is,” “lo”)', fr: 'Particule présentative utilisée pour introduire une phrase déclarative (“voici”, “voilà”)', ar: 'أداة تقديم تستخدم لافتتاح جملة خبرية ("ها هو"، "إليك")' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤄𐤋𐤌', latin: 'hlm', meaning: { en: 'strike', fr: 'frapper', ar: 'يضرب' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤄𐤌', latin: 'hm', meaning: { en: 'They (m.)', fr: 'Ils', ar: 'هم' }, grammar: { pos: 'Pronoun', gender: 'm', number: 'p' } },
  { phoenician: '𐤄𐤌𐤅𐤍', latin: 'hmwn', meaning: { en: 'Multitude, tumult', fr: 'Multitude, tumulte', ar: 'جمهور، ضجة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤌𐤄', latin: 'hmh', meaning: { en: 'To be noisy, make noise, roar', fr: 'Être bruyant, faire du bruit, rugir', ar: 'يضج، يصخب، يزأر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤌𐤕', latin: 'hmt', meaning: { en: 'They (common gender)', fr: 'Ils/Elles (genre commun)', ar: 'هم/هن (جنس مشترك)' }, grammar: { pos: 'Pronoun', gender: 'c', number: 'p' } },
  { phoenician: '𐤄𐤍', latin: 'hn', meaning: { en: 'Behold; they (f.)', fr: 'Voici; elles', ar: 'ها هن؛ هن' }, grammar: { pos: 'Interjection', notes: 'Also a pronoun.' } },
  { phoenician: '𐤄𐤍', latin: 'hn', meaning: { en: 'presentative particle, introducing a declarative sentence', fr: 'particule présentative, introduisant une phrase déclarative', ar: 'أداة تقديم، تفتتح جملة خبرية' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤄𐤍', latin: 'hn', meaning: { en: 'deictic particle: here is', fr: 'particule déictique : voici', ar: 'أداة إشارية: ها هو' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤄𐤍', latin: 'hn', meaning: { en: 'here', fr: 'ici', ar: 'هنا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤄𐤍', latin: 'hn', meaning: { en: 'hither', fr: 'ici (direction)', ar: 'إلى هنا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤄𐤍𐤄', latin: 'hnh', meaning: { en: 'Behold!', fr: 'Voici!', ar: 'ها هو!' }, grammar: { pos: 'Interjection' } },
  { phoenician: '𐤄𐤍𐤊𐤕', latin: 'hnkt', meaning: { en: 'here', fr: 'ici', ar: 'هنا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤄𐤎𐤎', latin: 'hss', meaning: { en: 'To incite, keep silent', fr: 'Inciter, garder le silence', ar: 'يحرض، يصمت' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤄𐤐𐤊', latin: 'hpk', meaning: { en: 'To overturn, change', fr: 'Renverser, changer', ar: 'يقلب، يغير' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤐𐤊', latin: 'hpk', meaning: { en: 'overturn', fr: 'renverser', ar: 'يقلب' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤄𐤓', latin: 'hr', meaning: { en: 'Mountain, mountain country', fr: 'Montagne, pays de montagnes', ar: 'جبل، بلد جبلي' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤓', latin: 'hr', meaning: { en: 'Grain', fr: 'Grain', ar: 'حبوب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤄𐤓𐤀', latin: "hrʾ", meaning: { en: 'Excrement', fr: 'Excrément', ar: 'براز' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: '[verify]' } },
  { phoenician: '𐤄𐤓𐤏𐤋𐤌', latin: 'hr ʿlm', meaning: { en: 'temple mount, lit. “mountain of the god(s)”', fr: 'mont du temple, litt. "montagne du/des dieu(x)"', ar: 'جبل الهيكل، حرفيًا "جبل الإله/الآلهة"' }, grammar: { pos: 'Noun', notes: 'ex.' } },
  { phoenician: '𐤄𐤓𐤁', latin: 'hrb', meaning: { en: 'Herbs', fr: 'Herbes', ar: 'أعشاب' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' } },
  { phoenician: '𐤄𐤓𐤁𐤏𐤋', latin: 'hrbʿl', meaning: { en: 'HR-Baʿal (vocalisation and meaning uncertain)', fr: 'HR-Baʿal (vocalisation et signification incertaines)', ar: 'هر-بعل (النطق والمعنى غير مؤكدين)' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤄𐤓𐤂', latin: 'hrg', meaning: { en: 'To kill, slay', fr: 'Tuer', ar: 'يقتل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤓𐤄', latin: 'hrh', meaning: { en: 'To conceive, be pregnant', fr: 'Concevoir, être enceinte', ar: 'تحبل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤓𐤓', latin: 'hrr', meaning: { en: 'To be pregnant, conceive', fr: 'Être enceinte, concevoir', ar: 'تكون حاملاً، تحبل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤓𐤎', latin: 'hrs', meaning: { en: 'To demolish, destroy', fr: 'Démolir, détruire', ar: 'يهدم، يدمر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤄𐤕𐤋', latin: 'htl', meaning: { en: 'To mock', fr: 'Se moquer', ar: 'يسخر' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤄𐤒𐤋', latin: 'hkl', meaning: { en: 'HEKAL, obscure deity, found only in Phoenician personal names', fr: 'HEKAL, divinité obscure, trouvée uniquement dans les noms personnels phéniciens', ar: 'هيكل، إله غامض، يوجد فقط في الأسماء الشخصية الفينيقية' }, grammar: { pos: 'Noun' }, category: 'theonym' },
];
