import type { GlossaryEntry } from '../../types';

export const heth: GlossaryEntry[] = [
  // Heth - 𐤇
  { phoenician: '𐤇', latin: 'ḥ', meaning: { en: 'Heth (eighth letter)', fr: 'Heth (huitième lettre)', ar: 'حاء (الحرف الثامن)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤁𐤀', latin: "ḥbʾ", meaning: { en: 'To hide', fr: 'Cacher', ar: 'يخبئ' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤇𐤁𐤄', latin: 'ḥbh', meaning: { en: 'To love, affection', fr: 'Aimer, affection', ar: 'يحب، مودة' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤇𐤁𐤋', latin: 'ḥbl', meaning: { en: 'Rope, cord', fr: 'Corde', ar: 'حبل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤁𐤒', latin: 'ḥbq', meaning: { en: 'To embrace', fr: 'Étreindre', ar: 'يعانق' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤇𐤁𐤓', latin: 'ḥbr', meaning: { en: 'Friend, companion', fr: 'Ami, compagnon', ar: 'صديق، رفيق' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤂', latin: 'ḥg', meaning: { en: 'Festival, feast', fr: 'Festival, fête', ar: 'مهرجان، عيد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤂𐤓', latin: 'ḥgr', meaning: { en: 'To gird', fr: 'Ceindre', ar: 'يتمنطق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤃𐤃', latin: 'ḥdd', meaning: { en: 'HADAD (in personal names), name of the god Baʿal, otherwise unattested in Phoenician-Punic texts', fr: 'HADAD (dans les noms personnels), nom du dieu Baʿal, autrement non attesté dans les textes phéniciens-puniques', ar: 'هدد (في الأسماء الشخصية)، اسم الإله بعل، غير موثق في النصوص الفينيقية-البونيقية' }, grammar: { pos: 'Noun' }, category: 'theonym' },
  { phoenician: '𐤇𐤃𐤓𐤌', latin: 'ḥdrm', meaning: { en: 'Hadrumetum - An important Punic city on the Tunisian coast, modern Sousse.', fr: 'Hadrumetum - Importante cité punique sur la côte tunisienne, aujourd\'hui Sousse.', ar: 'هدرم - مدينة بونيقية مهمة على الساحل التونسي، حالياً سوسة.' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤇𐤃𐤋', latin: 'ḥdl', meaning: { en: 'To cease, stop', fr: 'Cesser, arrêter', ar: 'يتوقف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤃𐤓', latin: 'ḥdr', meaning: { en: 'Chamber, room', fr: 'Chambre, pièce', ar: 'حجرة، غرفة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤃𐤔', latin: 'ḥdš', meaning: { en: 'New, new moon', fr: 'Nouveau, nouvelle lune', ar: 'جديد، هلال' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤇𐤅𐤋', latin: 'ḥwl', meaning: { en: 'To whirl, dance', fr: 'Tourbillonner, danser', ar: 'يدور، يرقص' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤅𐤌', latin: 'ḥwm', meaning: { en: 'Wall', fr: 'Mur', ar: 'سور' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤇𐤅𐤓', latin: 'ḥwr', meaning: { en: 'White stuff, noble', fr: 'Matière blanche, noble', ar: 'شيء أبيض، نبيل' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adjective.' } },
  { phoenician: '𐤇𐤅𐤒', latin: 'ḥwq', meaning: { en: 'Statute, ordinance', fr: 'Statut, ordonnance', ar: 'فريضة، قانون' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤈𐤀', latin: "ḥṭʾ", meaning: { en: 'Sin', fr: 'Péché', ar: 'خطية' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤈𐤁', latin: 'ḥṭb', meaning: { en: 'To gather wood', fr: 'Ramasser du bois', ar: 'يحتطب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤈𐤄', latin: 'ḥṭh', meaning: { en: 'Wheat', fr: 'Blé', ar: 'قمح' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤇𐤈𐤌', latin: 'ḥṭm', meaning: { en: 'Muzzle', fr: 'Muselière', ar: 'كمامة' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤉', latin: 'ḥy', meaning: { en: 'Life, alive', fr: 'Vie, vivant', ar: 'حياة، حي' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤇𐤉𐤃', latin: 'ḥyd', meaning: { en: 'Riddle, sharp saying', fr: 'Énigme, parole piquante', ar: 'لغز، قول حاد' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤇𐤉𐤋', latin: 'ḥyl', meaning: { en: 'Army, strength', fr: 'Armée, force', ar: 'جيش، قوة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤉𐤕', latin: 'hyt', meaning: { en: 'Luwian / Hittite, referring to Hittite lands or people.', fr: 'Louvite / Hittite, se référant aux terres ou au peuple hittite.', ar: 'لوفي / حثي، إشارة إلى أراضي الحثيين أو شعبهم.' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤇𐤊𐤄', latin: 'ḥkh', meaning: { en: 'To wait for', fr: 'Attendre', ar: 'ينتظر' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤇𐤊𐤌', latin: 'ḥkm', meaning: { en: 'Wise, wisdom', fr: 'Sage, sagesse', ar: 'حكيم، حكمة' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤇𐤋', latin: 'ḥl', meaning: { en: 'Sand', fr: 'Sable', ar: 'رمل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤋𐤁', latin: 'ḥlb', meaning: { en: 'Milk, fat', fr: 'Lait, graisse', ar: 'حليب، دهن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤋𐤃', latin: 'ḥld', meaning: { en: 'World, duration of life', fr: 'Monde, durée de vie', ar: 'عالم، مدة الحياة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤋𐤉', latin: 'ḥly', meaning: { en: 'Ornament, jewel', fr: 'Ornement, bijou', ar: 'حلية، جوهرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤋𐤋', latin: 'ḥll', meaning: { en: 'To profane, defile', fr: 'Profaner, souiller', ar: 'يدنس' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤇𐤋𐤌', latin: 'ḥlm', meaning: { en: 'Dream', fr: 'Rêve', ar: 'حلم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤋𐤑', latin: 'ḥlṣ', meaning: { en: 'Loins, to rescue', fr: 'Reins, sauver', ar: 'حقو، ينقذ' }, grammar: { pos: 'Noun', gender: 'm', number: 'p', notes: 'Also a verb.' } },
  { phoenician: '𐤇𐤋𐤒', latin: 'ḥlq', meaning: { en: 'Portion, share', fr: 'Portion, part', ar: 'قسم، نصيب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤌', latin: 'ḥm', meaning: { en: 'Hot, father-in-law', fr: 'Chaud, beau-père', ar: 'حار، حمو' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤇𐤌𐤃', latin: 'ḥmd', meaning: { en: 'To desire, covet', fr: 'Désirer, convoiter', ar: 'يشتهي، يطمع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤌𐤓', latin: 'ḥmr', meaning: { en: 'Donkey; wine', fr: 'Âne; vin', ar: 'حمار؛ خمر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤌𐤔', latin: 'ḥmš', meaning: { en: 'Five', fr: 'Cinq', ar: 'خمسة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤇𐤌𐤏', latin: "ḥmʿ", meaning: { en: 'Butter, curd', fr: 'Beurre, caillé', ar: 'زبدة، لبن رائب' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤇𐤍', latin: 'ḥn', meaning: { en: 'Grace, favor', fr: 'Grâce, faveur', ar: 'نعمة، فضل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤍𐤁𐤏𐤋', latin: "ḥnbʿl", meaning: { en: 'Hannibal ("Grace of Ba\'al")', fr: 'Hannibal ("Grâce de Ba\'al")', ar: 'حنبعل ("نعمة بعل")' }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'personal_name' },
  { phoenician: '𐤇𐤍𐤄', latin: 'ḥnh', meaning: { en: 'To encamp', fr: 'Camper', ar: 'يخيم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤍𐤈', latin: 'ḥnṭ', meaning: { en: 'To embalm', fr: 'Embaumer', ar: 'يحنط' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤎𐤃', latin: 'ḥsd', meaning: { en: 'Kindness, faithfulness', fr: 'Bonté, fidélité', ar: 'إحسان، أمانة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤎𐤋', latin: 'ḥsl', meaning: { en: 'Locust', fr: 'Sauterelle', ar: 'جراد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤑', latin: 'ḥṣ', meaning: { en: 'Arrow', fr: 'Flèche', ar: 'سهم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤑𐤓', latin: 'ḥṣr', meaning: { en: 'Court, enclosure', fr: 'Cour, enclos', ar: 'فناء، حظيرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤒𐤓', latin: 'ḥqr', meaning: { en: 'To search, investigate', fr: 'Chercher, enquêter', ar: 'يبحث، يحقق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤒𐤒', latin: 'ḥqq', meaning: { en: 'To inscribe', fr: 'Inscrire', ar: 'ينقش' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤓', latin: 'ḥr', meaning: { en: 'Horus — a major Egyptian god, representing the sky and kingship', fr: 'Horus — un dieu égyptien majeur, représentant le ciel et la royauté', ar: 'حورس — إله مصري رئيسي، يمثل السماء والملكية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤇𐤓𐤁', latin: 'ḥrb', meaning: { en: 'Sword', fr: 'Épée', ar: 'سيف' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤇𐤓𐤁', latin: 'ḥrb', meaning: { en: 'Carob', fr: 'Caroube', ar: 'خروب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤓𐤃', latin: 'ḥrd', meaning: { en: 'To tremble', fr: 'Trembler', ar: 'يرتجف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤓𐤌', latin: 'ḥrm', meaning: { en: 'To devote, ban', fr: 'Consacrer, interdire', ar: 'يحرم' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤇𐤓𐤐', latin: 'ḥrp', meaning: { en: 'Autumn, reproach', fr: 'Automne, reproche', ar: 'خريف، تعيير' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤇𐤓𐤐𐤊𐤓𐤈', latin: 'ḥrpkrṭ', meaning: { en: "Harpocrates — the child form of the god Horus, representing the newborn sun and hope", fr: "Harpocrate — la forme enfantine du dieu Horus, représentant le soleil naissant et l'espoir", ar: "حربوقراط / Harpocrates — شكل الطفل لإله حورس، يمثل الشمس المولودة والأمل" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤇𐤓𐤑', latin: 'ḥrṣ', meaning: { en: 'Gold; trench, diligent', fr: 'Or; fossé, diligent', ar: 'ذهب؛ خندق، مجتهد' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also an adjective.' } },
  { phoenician: '𐤇𐤓𐤔', latin: 'ḥrš', meaning: { en: 'Craftsman, to be silent', fr: 'Artisan, être silencieux', ar: 'حرفي، يصمت' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤇𐤔𐤁', latin: 'ḥšb', meaning: { en: 'To think, devise', fr: 'Penser, concevoir', ar: 'يفكر، يدبر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤔𐤄', latin: 'ḥšh', meaning: { en: 'To be silent', fr: 'Être silencieux', ar: 'يصمت' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤇𐤕𐤌', latin: 'ḥtm', meaning: { en: 'Seal or signet ring', fr: 'Sceau ou chevalière', ar: 'ختم أو خاتم توقيع' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Administrative/legal tool.' } },
  { phoenician: '𐤇𐤕𐤌𐤕', latin: 'ḥtmt', meaning: { en: 'Seal', fr: 'Sceau', ar: 'ختم' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'General term.' } },
  { phoenician: '𐤇𐤕𐤇𐤓', latin: 'ḥtḥr', meaning: { en: "Hathor — goddess of love, music, and fertility", fr: "Hathor — déesse de l'amour, de la musique et de la fertilité", ar: "حتحور — إلهة الحب والموسيقى والخصوبة" }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
  { phoenician: '𐤇𐤅𐤐', latin: 'ḥwp', meaning: { en: 'shore / coast', fr: 'rivage / côte', ar: 'شاطئ / ساحل' }, grammar: { pos: 'Noun', notes: 'standard Semitic term' } },
  { phoenician: '𐤇𐤌𐤋𐤊', latin: 'ḥmlk', meaning: { en: 'Himilco, "Milqart is my brother"', fr: 'Himilcon, "Milqart est mon frère"', ar: 'حملك، "ملقرط أخي"' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤇𐤓𐤔 𐤀𐤓𐤍𐤕', latin: 'ḥrš ʾrnt', meaning: { en: 'sarcophagus', fr: 'sarcophage', ar: 'تابوت' }, grammar: { pos: 'Noun' } },
];
