import type { GlossaryEntry } from '../../types';

export const kaph: GlossaryEntry[] = [
  // Kaph - 𐤊
  { phoenician: '𐤊', latin: 'K', meaning: { en: 'BECAUSE / THAT', fr: '', ar: '' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤊', latin: 'K', meaning: { en: 'PRESENTATIVE introducing an independent (non-subordinate) clause', fr: '', ar: '' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤊', latin: 'K', meaning: { en: 'HERE', fr: '', ar: '' }, grammar: { pos: 'Adverb', notes: 'locational' } },
  { phoenician: '𐤊𐤀𐤁', latin: "kʾb", meaning: { en: 'Pain', fr: 'Douleur', ar: 'ألم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤁𐤃', latin: 'KBD', meaning: { en: 'HONOR, RESPECT', fr: '', ar: '' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤁𐤃', latin: 'KBD', meaning: { en: 'HONOR, RESPECT', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤁𐤃', latin: 'KBD', meaning: { en: 'KABOD (“Honor”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤁𐤃𐤁𐤏𐤋', latin: 'KBDBʿL', meaning: { en: 'KIBBED-BA‘AL (“Honor Baal!”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤁𐤃𐤌𐤋𐤒𐤓𐤕', latin: 'KBDMLQRT', meaning: { en: 'KIBBED-MILQART (“Honor Milqart!”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤁𐤃𐤏𐤔𐤕𐤓𐤕', latin: 'KBDʿŠTRT', meaning: { en: 'KIBBED-ʿAŠTART (“Honor Aštarte!”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤁𐤎', latin: 'KBS', meaning: { en: 'FULLER, LAUNDERER', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤁𐤓', latin: 'KBR', meaning: { en: 'LARGE, GREAT', fr: '', ar: '' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤊𐤁𐤓', latin: 'KBR', meaning: { en: 'GREATNESS', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm', notes: '(cf. Hebrew kābīr, “great, mighty”)' } },
  { phoenician: '𐤊𐤁𐤏𐤋', latin: 'KBʿL', meaning: { en: 'KAB-BA‘AL (“Baal is honored”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤃', latin: 'KD', meaning: { en: 'JAR for water', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤄', latin: 'KH', meaning: { en: 'LIKE, AS', fr: '', ar: '' }, grammar: { pos: 'Preposition', notes: '(cf. Hebrew ke-).' } },
  { phoenician: '𐤊𐤄𐤋', latin: 'KHL', meaning: { en: 'ASSEMBLY, CONGREGATION', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤄𐤍', latin: 'khn', meaning: { en: 'Priest', fr: 'Prêtre', ar: 'كاهن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤄𐤍𐤕', latin: 'KHNT', meaning: { en: 'PRIESTESS', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤊𐤅𐤊𐤁', latin: 'kwkb', meaning: { en: 'Star, planet, celestial object', fr: 'Étoile, planète, objet céleste', ar: 'نجم، كوكب، جرم سماوي' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Used for stars, and as "wandering star" for planets.' } },
  { phoenician: '𐤊𐤉𐤍', latin: 'KYN', meaning: { en: 'ESTABLISH, SET', fr: '', ar: '' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤉𐤍', latin: 'KYN', meaning: { en: 'BASE, FOUNDATION', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤉𐤔𐤓', latin: 'KYŠR', meaning: { en: 'KIŠOR, var. KIŠORIM', fr: '', ar: '' }, grammar: { pos: 'Noun', notes: '(short form of the name “Servant of Kišor”)' }, category: 'personal_name' },
  { phoenician: '𐤊𐤉𐤔𐤓𐤉', latin: 'KYŠRI', meaning: { en: 'KIŠOR = KUŠOR', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'theonym' },
  { phoenician: '𐤊𐤉𐤔𐤓𐤉𐤀', latin: 'KYŠRYʾ', meaning: { en: 'CISRA – CAERE, also called Πυργοι (Pyrgi), city in Etruria; present-day Cerveteri', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤉𐤕𐤉', latin: 'kyty', meaning: { en: 'Cypriot, a generic term for Cyprus or its inhabitants.', fr: 'Chypriote, un terme générique pour Chypre ou ses habitants.', ar: 'قبرصي، مصطلح عام لقبرص أو سكانها.' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤊𐤁', latin: 'KKB', meaning: { en: 'KAKKABĒ (Κακκαβη), a colony of the Sidonians', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤊𐤓', latin: 'KKR', meaning: { en: 'TALENT', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤊𐤓𐤌', latin: 'KKRM', meaning: { en: 'TALENTS', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' } },
  { phoenician: '𐤊𐤊𐤓𐤕', latin: 'KKRT', meaning: { en: 'TALENT', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤊𐤋', latin: 'KL', meaning: { en: 'CONTAIN, STORE food', fr: '', ar: '' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤋', latin: 'KL', meaning: { en: 'ALL, EVERY, EACH (ONE)', fr: '', ar: '' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤊𐤋', latin: 'KL', meaning: { en: 'ANYONE', fr: '', ar: '' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤊𐤋', latin: 'KL', meaning: { en: 'EVERYTHING', fr: '', ar: '' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤊𐤋', latin: 'KL', meaning: { en: 'ALL', fr: '', ar: '' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤊𐤋', latin: 'KL', meaning: { en: 'Every, any', fr: '', ar: '' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤊𐤋 𐤀𐤃𐤌', latin: 'KL ʾDM', meaning: { en: 'EVERYONE, ANYONE', fr: '', ar: '' }, grammar: { pos: 'Pronoun', notes: 'Expression.' } },
  { phoenician: '𐤊𐤋𐤁', latin: 'KLB', meaning: { en: 'HOUND of a god = OBEDIENT WORSHIPPER / WIELDER OF A PICKAX / CAGE', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤋𐤁’', latin: 'KLB’', meaning: { en: 'PRISON', fr: '', ar: '' }, grammar: { pos: 'Noun' } },
  { phoenician: '𐤊𐤋𐤁’', latin: 'KLB’', meaning: { en: 'KELBE, var. KELBAY', fr: '', ar: '' }, grammar: { pos: 'Noun', notes: 'short form of the name-type klb-[+ Divine name], “Hound of [+ Divine name].”' }, category: 'personal_name' },
  { phoenician: '𐤊𐤋𐤁𐤉', latin: 'KLBY', meaning: { en: 'KELBAY, var. KELBE', fr: '', ar: '' }, grammar: { pos: 'Noun', notes: 'short form of the name-type klb-[+ Divine name], “Hound of [+ Divine name].”' }, category: 'personal_name' },
  { phoenician: '𐤊𐤋𐤁𐤋’', latin: 'KLBL’', meaning: { en: 'KELB-’ELA (“Hound of ’El”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤋𐤁’𐤋𐤌', latin: 'KLB’LM', meaning: { en: 'KELB-’ILIM (“Hound of God”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤋𐤇𐤏𐤕', latin: 'KLHʿT', meaning: { en: 'ALL THE TIME, ALWAYS', fr: '', ar: '' }, grammar: { pos: 'Adverb', notes: 'Expression. (Lat. semper).' } },
  { phoenician: '𐤊𐤋𐤉', latin: 'KLY', meaning: { en: 'COMPLETE', fr: '', ar: '' }, grammar: { pos: 'Adjective', notes: 'Written as n. in source.' } },
  { phoenician: '𐤊𐤋𐤋', latin: 'KLL', meaning: { en: 'ENTIRE, WHOLE', fr: '', ar: '' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤊𐤋𐤌', latin: 'KLM', meaning: { en: 'KLM', fr: '', ar: '' }, grammar: { pos: 'Noun', notes: '(vocalisation and meaning uncertain)' }, category: 'personal_name' },
  { phoenician: '𐤊𐤋𐤌𐤍𐤌', latin: 'KLMNM', meaning: { en: 'ANYTHING', fr: '', ar: '' }, grammar: { pos: 'Pronoun', notes: 'Expression.' } },
  { phoenician: '𐤊𐤋𐤌𐤅', latin: 'KLMW', meaning: { en: 'KILAMUWA, 9th century B.C. king of the state of Y’DY (Sam’al), capital at present-day Zinjirli', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤋𐤉', latin: 'kly', meaning: { en: 'Vessel, instrument', fr: 'Vaisseau, instrument', ar: 'إناء، أداة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤋𐤉𐤁𐤉', latin: 'klyby', meaning: { en: 'Clupea (Kelibia, Tunisia)', fr: 'Clupea (Kelibia, Tunisie)', ar: 'قليبية (تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤋𐤉𐤕', latin: 'klyt', meaning: { en: 'Kidney', fr: 'Rein', ar: 'كلية' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤊𐤌', latin: 'KM', meaning: { en: 'LIKE, AS / SO TOO, ALSO / AS, JUST AS / AS WELL AS', fr: '', ar: '' }, grammar: { pos: 'Preposition', notes: 'Also Adverb and Conjunction.' } },
  { phoenician: '𐤊𐤌 𐤀𐤔', latin: 'KM ‘Š', meaning: { en: 'WHEN, WHENEVER / JUST AS', fr: '', ar: '' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤊𐤌𐤁', latin: 'KMB', meaning: { en: 'KAMBE (Καμβη), a colony of Sidon, identified as Carthage by Stephen of Byzantium', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤌𐤆', latin: 'KMZ', meaning: { en: 'KMZ', fr: '', ar: '' }, grammar: { pos: 'Noun', notes: '(vocalisation and meaning uncertain)' }, category: 'personal_name' },
  { phoenician: '𐤊𐤌𐤍', latin: 'KMN', meaning: { en: 'CUMIN', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤌𐤎𐤕', latin: 'KMST', meaning: { en: 'STORE of fruit', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤊𐤌𐤓', latin: 'KMR', meaning: { en: 'KOMER-PRIEST', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤌 𐤔', latin: 'KM Š', meaning: { en: 'WHEN', fr: '', ar: '' }, grammar: { pos: 'Conjunction' } },
  { phoenician: '𐤊𐤌𐤕', latin: 'KMT', meaning: { en: 'THEREFORE, FOR THIS REASON, CONSEQUENTLY', fr: '', ar: '' }, grammar: { pos: 'Adverb', notes: 'in the co-ordinated phrase k-... kmt, “because... therefore.”' } },
  { phoenician: '𐤊𐤍', latin: 'KN', meaning: { en: 'BE, EXIST, BELONG to / HAVE, POSSESS / BE IN OFFICE / ENDURE, LAST / LIVE, RESIDE / BE OBLIGATED to do something (with infinitive construct) / With past perfective, expressing the pluperfect / BECOME ESTABLISHED, FIRM / HITHER / HONEST(LY), TRUTHFUL(LY) / SO, THUS', fr: '', ar: '' }, grammar: { pos: 'Verb', notes: 'Also locational adverb, adjective/adverb, and adverb.' } },
  { phoenician: '𐤊𐤍𐤀', latin: 'KNʾ', meaning: { en: 'ACQUIRE, POSSESS / KANA (“Owner, Acquirer”)', fr: '', ar: '' }, grammar: { pos: 'Verb', notes: 'Also a Personal Name.' } },
  { phoenician: '𐤊𐤍𐤀𐤋', latin: 'KNʾL', meaning: { en: 'KANA-’EL (“El has acquired”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤍𐤁𐤏𐤋', latin: 'KNBʿL', meaning: { en: 'KANA-BA‘AL (“Baal has acquired”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤍𐤆𐤔𐤓', latin: 'KNZSR', meaning: { en: 'KNZSR', fr: '', ar: '' }, grammar: { pos: 'Noun', notes: '(vocalisation and meaning uncertain)' }, category: 'personal_name' },
  { phoenician: '𐤊𐤍𐤌𐤋𐤊', latin: 'KNMLK', meaning: { en: 'KANA-MILK (“Milk possesses”)', fr: '', ar: '' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤍𐤏𐤍', latin: "knʿn", meaning: { en: 'Canaan', fr: 'Canaan', ar: 'كنعان' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤍𐤐', latin: 'knp', meaning: { en: 'Wing', fr: 'Aile', ar: 'جناح' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤊𐤍𐤕', latin: 'KNT', meaning: { en: 'FOUNDATION, BASE', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'f', notes: '(from root knn “to establish”)' } },
  { phoenician: '𐤊𐤎𐤐', latin: 'ksp', meaning: { en: 'Silver, money', fr: 'Argent, monnaie', ar: 'فضة، مال' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤓', latin: 'KR', meaning: { en: 'PASTURE, ENCLOSURE', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤓𐤍', latin: 'KRN', meaning: { en: 'HORN / KEREN (“Horn”)', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'f', notes: 'Also a Personal Name.' } },
  { phoenician: '𐤊𐤓𐤎𐤉𐤌', latin: 'krsym', meaning: { en: 'Corsicans, inhabitants of Corsica (plural).', fr: 'Corses, habitants de la Corse (pluriel).', ar: 'الكورسيكيون، سكان كورسيكا (جمع).' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' }, category: 'personal_name' },
  { phoenician: '𐤊𐤓𐤕', latin: 'KRT', meaning: { en: 'CUT / MAKE A COVENANT (as in “cut a treaty”)', fr: '', ar: '' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤔', latin: 'KŠ', meaning: { en: 'HARD, SEVERE / DIFFICULTY', fr: '', ar: '' }, grammar: { pos: 'Adjective', notes: 'Also Noun (m).' } },
  { phoenician: '𐤊𐤔𐤓', latin: 'KŠR', meaning: { en: 'BE PROPER, FIT / SUITABLE, UPRIGHT', fr: '', ar: '' }, grammar: { pos: 'Verb', notes: 'Also Adjective.' } },
  { phoenician: '𐤊𐤕', latin: 'KT', meaning: { en: 'WRITING / INSCRIPTION', fr: '', ar: '' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤕𐤍', latin: 'KTN', meaning: { en: 'SMALL, LITTLE / YOUTH, CHILD', fr: '', ar: '' }, grammar: { pos: 'Adjective', notes: 'Also Noun (m).' } },
  { phoenician: '𐤊𐤕𐤐', latin: 'ktp', meaning: { en: 'Shoulder', fr: 'Épaule', ar: 'كتف' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤊𐤍𐤉', latin: 'KNY', meaning: { en: 'Name, appoint', fr: 'Nommer, désigner', ar: 'يسمي، يعين' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤍𐤌𐤉', latin: 'KNMY', meaning: { en: 'KNMY', fr: 'KNMY', ar: 'كنمي' }, grammar: { pos: 'Noun', notes: 'vocalisation and meaning uncertain' }, category: 'personal_name' },
  { phoenician: '𐤊𐤍𐤏𐤍', latin: 'KNʿN', meaning: { en: 'Canaan, the Phoenician name of Phoenicia', fr: 'Canaan, le nom phénicien de la Phénicie', ar: 'كنعان، الاسم الفينيقي لفينيقيا' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤍𐤐𐤅𐤍', latin: 'KNPWN', meaning: { en: 'KNPWN', fr: 'KNPWN', ar: 'كنبون' }, grammar: { pos: 'Noun', notes: 'vocalisation and meaning uncertain' }, category: 'personal_name' },
  { phoenician: '𐤊𐤍𐤔', latin: 'KNŠ', meaning: { en: 'Convenor', fr: 'Organisateur', ar: 'منظم الاجتماع' }, grammar: { pos: 'Noun', gender: 'm', notes: 'title of the praeses of a sodality' } },
  { phoenician: '𐤊𐤍𐤔', latin: 'KNŠ', meaning: { en: 'KINNAŠ (“The convenor”)', fr: 'KINNAŠ (« L\'organisateur »)', ar: 'كيناش ("المنظم")' }, grammar: { pos: 'Noun', notes: 'vars. KINNAŠA, KINNAŠAY, KINNAŠIM; fem. KINNAŠIT' }, category: 'personal_name' },
  { phoenician: '𐤊𐤔𐤀', latin: 'KSʾ', meaning: { en: 'Full moon', fr: 'Pleine lune', ar: 'بدر' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤔𐤀', latin: 'KSʾ', meaning: { en: 'Kese\', god of the full moon', fr: 'Kese\', dieu de la pleine lune', ar: 'كيسئ، إله البدر' }, grammar: { pos: 'Noun' }, category: 'theonym' },
  { phoenician: '𐤊𐤔𐤉', latin: 'KSY', meaning: { en: 'KIS’AY (“Servant of Kese’”)', fr: 'KIS’AY (« Serviteur de Kese’ »)', ar: 'كيسأي ("خادم كيسئ")' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤔𐤀𐤌', latin: 'KSʾM', meaning: { en: 'Full moons', fr: 'Pleines lunes', ar: 'بدور' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' } },
  { phoenician: '𐤊𐤔𐤉', latin: 'KSY', meaning: { en: 'Cover, conceal', fr: 'Couvrir, dissimuler', ar: 'يغطي، يخفي' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤔𐤉', latin: 'KSY', meaning: { en: 'Clothe, dress', fr: 'Vêtir, habiller', ar: 'يلبس، يكسو' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤔𐤉', latin: 'KSY', meaning: { en: 'Cover, protect', fr: 'Couvrir, protéger', ar: 'يغطي، يحمي' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤍𐤕', latin: 'KNT', meaning: { en: 'KNT', fr: 'KNT', ar: 'كنت' }, grammar: { pos: 'Noun', notes: 'vocalisation and meaning uncertain' }, category: 'personal_name' },
  { phoenician: '𐤊𐤍', latin: 'KN', meaning: { en: 'Now', fr: 'Maintenant', ar: 'الآن' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤊𐤀𐤎', latin: 'KʾS', meaning: { en: 'Undertaker and supervisor of a work', fr: 'Entrepreneur et superviseur d\'un travail', ar: 'متعهد ومشرف على عمل' }, grammar: { pos: 'Noun', gender: 'm', notes: 'Latin curator' } },
  { phoenician: '𐤊𐤓𐤐', latin: 'KPP', meaning: { en: 'Upset an object', fr: 'Renverser un objet', ar: 'يقلب شيئًا' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤐𐤎', latin: 'KPS', meaning: { en: 'A profession', fr: 'Une profession', ar: 'مهنة' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤐𐤓', latin: 'KPR', meaning: { en: 'Wipe away, cleanse; forgive', fr: 'Essuyer, nettoyer; pardonner', ar: 'يمسح، يطهر؛ يغفر' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤐𐤓', latin: 'KPR', meaning: { en: 'Town, village', fr: 'Ville, village', ar: 'بلدة، قرية' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤐𐤓', latin: 'KPR', meaning: { en: 'KPR', fr: 'KPR', ar: 'كفر' }, grammar: { pos: 'Noun', notes: 'vocalisation and meaning uncertain' }, category: 'personal_name' },
  { phoenician: '𐤊𐤐𐤓𐤀', latin: 'KPRʾ', meaning: { en: 'Solus, city in Sicily; present-day Solunto', fr: 'Solus, ville en Sicile; Solonte actuelle', ar: 'سولوس، مدينة في صقلية؛ سولونتو الحالية' }, grammar: { pos: 'Noun', notes: 'the Phoenician name was Kaphra (“City of...”)' }, category: 'location' },
  { phoenician: '𐤊𐤐𐤕', latin: 'KPT', meaning: { en: 'Bind', fr: 'Lier', ar: 'يربط' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤓𐤁', latin: 'KRB', meaning: { en: 'Cherub', fr: 'Chérubin', ar: 'كَرُوب' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤓𐤅𐤀', latin: 'KRWʾ', meaning: { en: 'Korwa (Kore)', fr: 'Korwa (Kore)', ar: 'كوروا (كوري)' }, grammar: { pos: 'Noun', notes: '(Greek Κορη) the goddess Persephone; cult introduced in Carthage in 396 B.C.' }, category: 'theonym' },
  { phoenician: '𐤊𐤓𐤅𐤋', latin: 'KRWL', meaning: { en: 'KRWL', fr: 'KRWL', ar: 'كرول' }, grammar: { pos: 'Noun', notes: 'vocalisation and meaning uncertain' }, category: 'personal_name' },
  { phoenician: '𐤊𐤓𐤇', latin: 'KRḤ', meaning: { en: 'A funerary object', fr: 'Un objet funéraire', ar: 'غرض جنائزي' }, grammar: { pos: 'Noun', gender: 'm', notes: 'Gender is uncertain.' } },
  { phoenician: '𐤊𐤓𐤈𐤍', latin: 'KRṬN', meaning: { en: 'Cirta (Constantine), city in North Africa (modern-day Algeria)', fr: 'Cirta (Constantine), ville d\'Afrique du Nord (Algérie actuelle)', ar: 'سيرتا (قسنطينة)، مدينة في شمال أفريقيا (الجزائر الحالية)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤓𐤉', latin: 'KRY', meaning: { en: 'Buy land', fr: 'Acheter une terre', ar: 'يشتري أرضًا' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤓𐤉', latin: 'KRY', meaning: { en: 'Dig', fr: 'Creuser', ar: 'يحفر' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤓𐤉𐤍', latin: 'KRYN', meaning: { en: 'KRYN', fr: 'KRYN', ar: 'كرين' }, grammar: { pos: 'Noun', notes: 'vocalisation and meaning uncertain' }, category: 'personal_name' },
  { phoenician: '𐤊𐤓𐤋𐤉', latin: 'KRLY', meaning: { en: 'Carales, city in Sardinia; present-day Cagliari', fr: 'Carales, ville en Sardaigne; Cagliari actuelle', ar: 'كاراليس، مدينة في سردينيا؛ كالياري الحالية' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤓𐤌', latin: 'KRM', meaning: { en: 'Honor', fr: 'Honorer', ar: 'يكرم' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤓𐤌', latin: 'KRM', meaning: { en: 'Restore a ruined building', fr: 'Restaurer un bâtiment en ruine', ar: 'يرمم مبنى متهدمًا' }, grammar: { pos: 'Verb', notes: 'from context' } },
  { phoenician: '𐤊𐤓𐤌', latin: 'KRM', meaning: { en: 'Vineyard', fr: 'Vignoble', ar: 'كرم' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤓𐤌', latin: 'KRM', meaning: { en: 'Charmis, a town in Sardinia', fr: 'Charmis, une ville en Sardaigne', ar: 'شارميس، بلدة في سردينيا' }, grammar: { pos: 'Noun', notes: 'founded by the Carthaginians (Stephan of Byzantium)' }, category: 'location' },
  { phoenician: '𐤊𐤓𐤎𐤉𐤌', latin: 'KRSYM', meaning: { en: 'Corsi, an ethnic group and region in Sardinia whence derives the name of the island of Corsica', fr: 'Corsi, un groupe ethnique et une région en Sardaigne d\'où dérive le nom de l\'île de Corse', ar: 'كورسي، مجموعة عرقية ومنطقة في سردينيا اشتق منها اسم جزيرة كورسيكا' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤓𐤎𐤉𐤌', latin: 'KRSYM', meaning: { en: 'The Corsic language', fr: 'La langue corse', ar: 'اللغة الكورسيكية' }, grammar: { pos: 'Noun' } },
  { phoenician: '𐤊𐤓𐤓', latin: 'KRR', meaning: { en: 'Kirur, a month of the Phoenician calendar', fr: 'Kirur, un mois du calendrier phénicien', ar: 'كيرور، شهر من التقويم الفينيقي' }, grammar: { pos: 'Noun' } },
  { phoenician: '𐤊𐤓𐤓', latin: 'KRR', meaning: { en: 'Kirur, god of the month of Kirur', fr: 'Kirur, dieu du mois de Kirur', ar: 'كيرور، إله شهر كيرور' }, grammar: { pos: 'Noun' }, category: 'theonym' },
  { phoenician: '𐤊𐤓𐤔', latin: 'KRŠ', meaning: { en: 'Figure, form, body', fr: 'Figure, forme, corps', ar: 'شكل، هيئة، جسد' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤓𐤕', latin: 'KRT', meaning: { en: 'Cut off, kill, execute', fr: 'Couper, tuer, exécuter', ar: 'يقطع، يقتل، يعدم' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤓𐤕', latin: 'KRT', meaning: { en: 'A profession', fr: 'Une profession', ar: 'مهنة' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤊𐤔𐤓', latin: 'KŠR', meaning: { en: 'Kušor, god of intellect, wisdom, learning, science and the arts', fr: 'Kušor, dieu de l\'intellect, de la sagesse, de l\'apprentissage, de la science et des arts', ar: 'كوشور، إله العقل والحكمة والتعلم والعلوم والفنون' }, grammar: { pos: 'Noun', notes: 'Χουσωρ' }, category: 'theonym' },
  { phoenician: '𐤊𐤔𐤓𐤕', latin: 'KŠRT', meaning: { en: 'Kušart, goddess of intellect, wisdom, learning, science and the arts', fr: 'Kušart, déesse de l\'intellect, de la sagesse, de l\'apprentissage, de la science et des arts', ar: 'كوشارت، إلهة العقل والحكمة والتعلم والعلوم والفنون' }, grammar: { pos: 'Noun', notes: 'Χουσωρθις' }, category: 'theonym' },
  { phoenician: '𐤊𐤔𐤓𐤉𐤕𐤍', latin: 'KŠRYTN', meaning: { en: 'Kušor-Yaton (“Kušor grant!”)', fr: 'Kušor-Yaton (« Que Kušor accorde ! »)', ar: 'كوشور-ياتون ("ليمنح كوشور!")' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤊𐤕', latin: 'KT', meaning: { en: 'Honesty, truthfulness', fr: 'Honnêteté, véracité', ar: 'صدق، أمانة' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤊𐤕', latin: 'KT', meaning: { en: 'Kition (Citium), city in Cyprus', fr: 'Kition (Citium), ville à Chypre', ar: 'كيتيوم (سيتيوم)، مدينة في قبرص' }, grammar: { pos: 'Noun', notes: 'Κιτιον , Κετιων' }, category: 'location' },
  { phoenician: '𐤊𐤕𐤉', latin: 'KTY', meaning: { en: 'Kition (Citium), city in Cyprus', fr: 'Kition (Citium), ville à Chypre', ar: 'كيتيوم (سيتيوم)، مدينة في قبرص' }, grammar: { pos: 'Noun', notes: 'Κιτιον , Κετιων' }, category: 'location' },
  { phoenician: '𐤊𐤕𐤍', latin: 'KTN', meaning: { en: 'Kition (Citium), city in Cyprus', fr: 'Kition (Citium), ville à Chypre', ar: 'كيتيوم (سيتيوم)، مدينة في قبرص' }, grammar: { pos: 'Noun', notes: 'Κιτιον , Κετιων' }, category: 'location' },
  { phoenician: '𐤊𐤕', latin: 'KT', meaning: { en: 'Here', fr: 'Ici', ar: 'هنا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤊𐤕𐤁', latin: 'KTB', meaning: { en: 'Write, inscribe, record', fr: 'Écrire, inscrire, enregistrer', ar: 'يكتب، ينقش، يسجل' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤊𐤕𐤁𐤕', latin: 'KTBT', meaning: { en: 'Writing', fr: 'Écriture', ar: 'كتابة' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤊𐤕𐤁𐤕', latin: 'KTBT', meaning: { en: 'Book, document', fr: 'Livre, document', ar: 'كتاب، وثيقة' }, grammar: { pos: 'Noun' } },
  { phoenician: '𐤊𐤕𐤁𐤕', latin: 'KTBT', meaning: { en: 'Letter of the alphabet', fr: 'Lettre de l\'alphabet', ar: 'حرف من الأبجدية' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤊𐤕𐤁𐤕 𐤃𐤁𐤓 𐤄𐤁𐤕', latin: 'KTBT DBR HBT', meaning: { en: 'Book of the Affairs of the House', fr: 'Livre des affaires de la maison', ar: 'كتاب شؤون البيت' }, grammar: { pos: 'Noun', notes: 'family chronicle and register' } },
  { phoenician: '𐤊𐤕𐤌', latin: 'KTM', meaning: { en: 'KTM', fr: 'KTM', ar: 'كتم' }, grammar: { pos: 'Noun', notes: 'vocalisation and meaning uncertain' }, category: 'personal_name' },
  { phoenician: '𐤊𐤕𐤍', latin: 'KTN', meaning: { en: 'Tunic', fr: 'Tunique', ar: 'سترة' }, grammar: { pos: 'Noun', gender: 'm', notes: 'Greek χιτων' } },
  { phoenician: '𐤊𐤕𐤍', latin: 'KTN', meaning: { en: 'Kition, city in Cyprus', fr: 'Kition, ville à Chypre', ar: 'كيتيوم، مدينة في قبرص' }, grammar: { pos: 'Noun', notes: 'this is the 9th-8th century B.C.' }, category: 'location' },
  { phoenician: '𐤊𐤕𐤓𐤕', latin: 'KTRT', meaning: { en: 'High turban', fr: 'Turban haut', ar: 'عمامة عالية' }, grammar: { pos: 'Noun', gender: 'f' } },
];
