import type { GlossaryEntry } from '../../types';

export const kaph: GlossaryEntry[] = [
  // Kaph - 𐤊
  { phoenician: '𐤊', latin: 'k', meaning: { en: 'As, like; Kaph (eleventh letter)', fr: 'Comme; Kaph (onzième lettre)', ar: 'كـ، مثل؛ كاف (الحرف الحادي عشر)' }, grammar: { pos: 'Preposition', notes: 'Also a noun (letter name).' } },
  { phoenician: '𐤊𐤀𐤁', latin: "k'b", meaning: { en: 'Pain', fr: 'Douleur', ar: 'ألم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤁𐤃', latin: 'kbd', meaning: { en: 'Heavy, glory, liver', fr: 'Lourd, gloire, foie', ar: 'ثقيل، مجد، كبد' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤊𐤁𐤅𐤃', latin: 'kbwd', meaning: { en: 'Glory', fr: 'Gloire', ar: 'مجد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤁𐤉𐤓', latin: 'kbyr', meaning: { en: 'Great, mighty', fr: 'Grand, puissant', ar: 'عظيم، جبار' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤊𐤁𐤓', latin: 'kbr', meaning: { en: 'Great, much', fr: 'Grand, beaucoup', ar: 'كبير، كثير' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤊𐤁𐤎', latin: 'kbs', meaning: { en: 'To wash, fuller', fr: 'Laver, foulon', ar: 'يغسل، قصار' }, grammar: { pos: 'Verb', stem: 'D-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤊𐤃', latin: 'kd', meaning: { en: 'Jar', fr: 'Jarre', ar: 'جرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤄𐤄', latin: 'khh', meaning: { en: 'To be dim, faint', fr: 'Être faible, s\'évanouir', ar: 'يخفت، يغمى عليه' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤄𐤍', latin: 'khn', meaning: { en: 'Priest', fr: 'Prêtre', ar: 'كاهن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤅𐤊𐤁', latin: 'kwkb', meaning: { en: 'Star', fr: 'Étoile', ar: 'نجم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤅𐤍', latin: 'kwn', meaning: { en: 'To establish, prepare', fr: 'Établir, préparer', ar: 'يؤسس، يعد' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤊𐤅𐤓', latin: 'kwr', meaning: { en: 'Furnace', fr: 'Fournaise', ar: 'فرن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤅𐤎', latin: 'kws', meaning: { en: 'Cup', fr: 'Coupe', ar: 'كأس' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤊𐤇𐤃', latin: 'kḥd', meaning: { en: 'To hide, conceal', fr: 'Cacher, dissimuler', ar: 'يخفي، يكتم' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤊𐤇𐤔', latin: 'kḥš', meaning: { en: 'To lie, deceive', fr: 'Mentir, tromper', ar: 'يكذب، يخدع' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤊𐤋', latin: 'kl', meaning: { en: 'All, every', fr: 'Tout, chaque', ar: 'كل' }, grammar: { pos: 'Adjective', notes: 'Functions as a determiner.' } },
  { phoenician: '𐤊𐤋𐤀', latin: "kl'", meaning: { en: 'Prison, restraint', fr: 'Prison, contrainte', ar: 'سجن، قيد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤋𐤁', latin: 'klb', meaning: { en: 'Dog', fr: 'Chien', ar: 'كلب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤋𐤉𐤁𐤉', latin: 'klyby', meaning: { en: 'Clupea (Kelibia, Tunisia)', fr: 'Clupea (Kelibia, Tunisie)', ar: 'قليبية (تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤋𐤄', latin: 'klh', meaning: { en: 'To be finished, complete', fr: 'Être fini, complet', ar: 'ينتهي، يكتمل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤋𐤉', latin: 'kly', meaning: { en: 'Vessel, instrument', fr: 'Vaisseau, instrument', ar: 'إناء، أداة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤋𐤌', latin: 'klm', meaning: { en: 'To shame, insult', fr: 'Faire honte, insulter', ar: 'يخزي، يهين' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤊𐤍', latin: 'kn', meaning: { en: 'Thus, so', fr: 'Ainsi, donc', ar: 'هكذا، كذلك' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤊𐤍𐤏𐤍', latin: "knʿn", meaning: { en: 'Canaan', fr: 'Canaan', ar: 'كنعان' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤍𐤏', latin: "knʿ", meaning: { en: 'To be humble', fr: 'Être humble', ar: 'يتواضع' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤊𐤍𐤐', latin: 'knp', meaning: { en: 'Wing', fr: 'Aile', ar: 'جناح' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤊𐤎𐤀', latin: "ks'", meaning: { en: 'Throne', fr: 'Trône', ar: 'عرش' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤎𐤄', latin: 'ksh', meaning: { en: 'To cover', fr: 'Couvrir', ar: 'يغطي' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤊𐤎𐤐', latin: 'ksp', meaning: { en: 'Silver, money', fr: 'Argent (métal), argent (monnaie)', ar: 'فضة، مال' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤐', latin: 'kp', meaning: { en: 'Palm (of hand)', fr: 'Paume (de la main)', ar: 'كف' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤊𐤓', latin: 'kr', meaning: { en: 'Lamb, pasture', fr: 'Agneau, pâturage', ar: 'حمل، مرعى' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤓𐤊𐤍', latin: 'krkn', meaning: { en: 'Kerkennah Islands, Tunisia', fr: 'Îles Kerkennah, Tunisie', ar: 'جزر قرقنة، تونس' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤓𐤋𐤉', latin: 'krly', meaning: { en: 'Cagliari, Sardinia', fr: 'Cagliari, Sardaigne', ar: 'كالياري، سردينيا' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤓𐤌', latin: 'krm', meaning: { en: 'Vineyard', fr: 'Vignoble', ar: 'كرم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤊𐤓𐤎', latin: 'krs', meaning: { en: "Kres — a chthonic / underworld deity", fr: "Kres — une divinité chthonienne / souterraine", ar: "كريوس — إله قاعي / تحت الأرض، مشابه للطابع الكثوني" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤊𐤓𐤎𐤌', latin: 'krsm', meaning: { en: 'To devour', fr: 'Dévorer', ar: 'يلتهم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤓𐤕', latin: 'krt', meaning: { en: 'To cut off', fr: 'Couper', ar: 'يقطع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤔𐤋', latin: 'kšl', meaning: { en: 'To stumble', fr: 'Trébucher', ar: 'يتعثر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤕𐤁', latin: 'ktb', meaning: { en: 'To write', fr: 'Écrire', ar: 'يكتب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤊𐤕𐤉', latin: 'kty', meaning: { en: 'Kition (Larnaca, Cyprus)', fr: 'Kition (Larnaca, Chypre)', ar: 'كيتيون (لارنكا، قبرص)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤊𐤕𐤍𐤕', latin: 'ktnt', meaning: { en: 'Tunic', fr: 'Tunique', ar: 'قميص' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
];