import type { GlossaryEntry } from '../../types';

export const lamedh: GlossaryEntry[] = [
  // Lamedh - 𐤋
  { phoenician: '𐤋', latin: 'l', meaning: { en: 'Lamedh (twelfth letter)', fr: 'Lamedh (douzième lettre)', ar: 'لام (الحرف الثاني عشر)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤋-', latin: 'l-', meaning: { en: 'To, for, of', fr: 'À, pour, de', ar: 'لـ، إلى' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤋𐤀', latin: "l'", meaning: { en: 'Not', fr: 'Ne...pas', ar: 'لا' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤋𐤀𐤌', latin: "l'm", meaning: { en: 'People, nation', fr: 'Peuple, nation', ar: 'شعب، أمة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤁', latin: 'lb', meaning: { en: 'Heart', fr: 'Cœur', ar: 'قلب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤁𐤃', latin: 'lbd', meaning: { en: 'Alone', fr: 'Seul', ar: 'وحده' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤋𐤁𐤉𐤀', latin: "lby'", meaning: { en: 'Lioness', fr: 'Lionne', ar: 'لبؤة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤁𐤍', latin: 'lbn', meaning: { en: 'White, brick', fr: 'Blanc, brique', ar: 'أبيض، لبنة' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤋𐤁𐤔', latin: 'lbš', meaning: { en: 'To wear, garment', fr: 'Porter, vêtement', ar: 'يلبس، ثوب' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤋𐤄𐤁', latin: 'lhb', meaning: { en: 'Flame', fr: 'Flamme', ar: 'لهب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤄𐤈', latin: 'lhṭ', meaning: { en: 'Flame, to blaze', fr: 'Flamme, flamber', ar: 'لهب، يشتعل' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤋𐤅𐤇', latin: 'lwḥ', meaning: { en: 'Tablet, plank', fr: 'Tablette, planche', ar: 'لوح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤅𐤆', latin: 'lwz', meaning: { en: 'Almond tree, to turn aside', fr: 'Amandier, se détourner', ar: 'شجرة لوز، ينحرف' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤋𐤅𐤉', latin: 'lwy', meaning: { en: 'To accompany', fr: 'Accompagner', ar: 'يصاحب' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤋𐤇𐤌', latin: 'lḥm', meaning: { en: 'Bread; to fight', fr: 'Pain; combattre', ar: 'خبز؛ يحارب' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb (N-stem).' } },
  { phoenician: '𐤋𐤇𐤑', latin: 'lḥṣ', meaning: { en: 'To oppress', fr: 'Opprimer', ar: 'يضطهد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤈𐤔', latin: 'lṭš', meaning: { en: 'To sharpen', fr: 'Aiguiser', ar: 'يشحذ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤉𐤋', latin: 'lyl', meaning: { en: 'Night', fr: 'Nuit', ar: 'ليل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤉𐤍', latin: 'lyn', meaning: { en: 'To lodge, remain overnight', fr: 'Loger, passer la nuit', ar: 'يبيت' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤉𐤑', latin: 'lyṣ', meaning: { en: 'Scoffer, mocker', fr: 'Moqueur', ar: 'مستهزئ' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤊𐤔', latin: 'lkš', meaning: { en: 'Lixus, Morocco', fr: 'Lixus, Maroc', ar: 'ليكسوس، المغرب' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤋𐤌𐤃', latin: 'lmd', meaning: { en: 'To learn', fr: 'Apprendre', ar: 'يتعلم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤐𐤒𐤉', latin: 'lpqy', meaning: { en: 'Leptis Magna (Libya) & Leptis Minor (Lamta, Tunisia)', fr: 'Leptis Magna (Libye) & Leptis Minor (Lamta, Tunisie)', ar: 'لبدة الكبرى (ليبيا) ولبدة الصغرى (لمطة، تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤋𐤏𐤂', latin: "lʿg", meaning: { en: 'To mock, stammer', fr: 'Se moquer, bégayer', ar: 'يسخر، يتلعثم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤏𐤈', latin: "lʿṭ", meaning: { en: 'To swallow', fr: 'Avaler', ar: 'يبتلع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤐𐤉𐤃', latin: 'lpyd', meaning: { en: 'Torch', fr: 'Torche', ar: 'شعلة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤐𐤕', latin: 'lpt', meaning: { en: 'To grasp, turn', fr: 'Saisir, tourner', ar: 'يمسك، يدير' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤒𐤇', latin: 'lqḥ', meaning: { en: 'To take', fr: 'Prendre', ar: 'يأخذ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤒𐤈', latin: 'lqṭ', meaning: { en: 'To gather, glean', fr: 'Ramasser, glaner', ar: 'يجمع، يلتقط' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤒𐤔', latin: 'lqš', meaning: { en: 'Late rain', fr: 'Pluie tardive', ar: 'مطر متأخر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤔𐤍', latin: 'lšn', meaning: { en: 'Tongue, language', fr: 'Langue', ar: 'لسان، لغة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤔𐤌', latin: 'lšm', meaning: { en: 'Feldspar or amazonite', fr: 'Feldspath ou amazonite', ar: 'فلدسبار أو أمازونيت' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Context: Imported gemstone.' } },
  { phoenician: '𐤋𐤁𐤀', latin: 'lbʼ', meaning: { en: 'Lion (alternative term)', fr: 'Lion (terme alternatif)', ar: 'أسد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤐', latin: 'lp', meaning: { en: 'Leaf', fr: 'Feuille', ar: 'ورقة شجر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤐', latin: 'lp', meaning: { en: 'Tree', fr: 'Arbre', ar: 'شجرة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤋𐤐𐤍', latin: 'lpn', meaning: { en: 'Fall', fr: 'Tomber', ar: 'يسقط' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤐𐤋', latin: 'lpl', meaning: { en: 'Do', fr: 'Faire', ar: 'يفعل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤋𐤊', latin: 'lk', meaning: { en: 'All', fr: 'Tout', ar: 'كل' }, grammar: { pos: 'Adjective' } },
];