import type { GlossaryEntry } from '../../types';

export const mem: GlossaryEntry[] = [
  // Mem - 𐤌
  { phoenician: '𐤌', latin: 'm', meaning: { en: 'Mem (thirteenth letter)', fr: 'Mem (treizième lettre)', ar: 'ميم (الحرف الثالث عشر)' }, grammar: { pos: 'Noun', gender: 'f', number: 'p' } },
  { phoenician: '𐤌-', latin: 'm-', meaning: { en: 'From', fr: 'De', ar: 'من' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤌𐤀𐤃', latin: "m'd", meaning: { en: 'Very, much', fr: 'Très, beaucoup', ar: 'جداً، كثيراً' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤌𐤀𐤄', latin: "m'h", meaning: { en: 'Hundred', fr: 'Cent', ar: 'مئة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤌𐤀𐤍', latin: "m'n", meaning: { en: 'To refuse', fr: 'Refuser', ar: 'يرفض' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤌𐤀𐤎', latin: "m's", meaning: { en: 'To reject, despise', fr: 'Rejeter, mépriser', ar: 'يرفض، يحتقر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤁𐤅𐤀', latin: "mbw'", meaning: { en: 'Entrance', fr: 'Entrée', ar: 'مدخل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤂𐤃𐤋', latin: 'mgdl', meaning: { en: 'Tower', fr: 'Tour', ar: 'برج' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤂𐤍', latin: 'mgn', meaning: { en: 'Shield', fr: 'Bouclier', ar: 'درع' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤂𐤓', latin: 'mgr', meaning: { en: 'To overthrow', fr: 'Renverser', ar: 'يطيح' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤌𐤃𐤃', latin: 'mdd', meaning: { en: 'To measure', fr: 'Mesurer', ar: 'يقيس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤃𐤓', latin: 'mdr', meaning: { en: 'Dwelling place', fr: 'Lieu de résidence', ar: 'مسكن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤄', latin: 'mh', meaning: { en: 'What?', fr: 'Quoi?', ar: 'ماذا؟' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤌𐤄𐤓', latin: 'mhr', meaning: { en: 'To hasten; price', fr: 'Se hâter; prix', ar: 'يسرع؛ سعر' }, grammar: { pos: 'Verb', stem: 'D-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤌𐤅𐤋', latin: 'mwl', meaning: { en: 'To circumcise', fr: 'Circoncire', ar: 'يختن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤅𐤎𐤓', latin: 'mwsr', meaning: { en: 'Discipline', fr: 'Discipline', ar: 'تأديب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤅𐤕', latin: 'mwt', meaning: { en: 'Death, to die', fr: 'Mort, mourir', ar: 'موت، يموت' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤌𐤅𐤒𐤃', latin: 'mwqd', meaning: { en: 'Hearth, burning place', fr: 'Foyer, lieu de combustion', ar: 'موقد، مكان الاحتراق' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤆𐤌𐤄', latin: 'mzmh', meaning: { en: 'Plan, device', fr: 'Plan, stratagème', ar: 'خطة، حيلة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤌𐤆𐤓', latin: 'mzr', meaning: { en: 'Girdle, loincloth', fr: 'Ceinture, pagne', ar: 'حزام، مئزر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤇𐤄', latin: 'mḥh', meaning: { en: 'To wipe out', fr: 'Effacer', ar: 'يمحو' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤈', latin: 'mṭ', meaning: { en: 'To waver, shake', fr: 'Vaciller, secouer', ar: 'يترنح، يهتز' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤈𐤄', latin: 'mṭh', meaning: { en: 'Staff, tribe', fr: 'Bâton, tribu', ar: 'عصا، سبط' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤈𐤅𐤀', latin: 'mṭwʾ', meaning: { en: 'Motya, Sicily', fr: 'Motyé, Sicile', ar: 'موتيا، صقلية' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤌𐤈𐤓', latin: 'mṭr', meaning: { en: 'Rain', fr: 'Pluie', ar: 'مطر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤉', latin: 'my', meaning: { en: 'Who?', fr: 'Qui?', ar: 'من؟' }, grammar: { pos: 'Pronoun' } },
  { phoenician: '𐤌𐤉𐤌', latin: 'mym', meaning: { en: 'Water', fr: 'Eau', ar: 'ماء' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' } },
  { phoenician: '𐤌𐤊𐤓', latin: 'mkr', meaning: { en: 'To sell', fr: 'Vendre', ar: 'يبيع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤋𐤀', latin: "ml'", meaning: { en: 'Full', fr: 'Plein', ar: 'ممتلئ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤋𐤀𐤊', latin: "ml'k", meaning: { en: 'Messenger, angel', fr: 'Messager, ange', ar: 'رسول، ملاك' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤋𐤄', latin: 'mlh', meaning: { en: 'Word (Aramaic)', fr: 'Mot (araméen)', ar: 'كلمة (آرامية)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤌𐤋𐤇', latin: 'mlḥ', meaning: { en: 'Salt', fr: 'Sel', ar: 'ملح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤋𐤇𐤌𐤄', latin: 'mlḥmh', meaning: { en: 'War, battle', fr: 'Guerre, bataille', ar: 'حرب، معركة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤌𐤋𐤈', latin: 'mlṭ', meaning: { en: 'Malta', fr: 'Malte', ar: 'مالطا' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤌𐤋𐤈', latin: 'mlṭ', meaning: { en: 'To escape', fr: 'S\'échapper', ar: 'ينجو' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤌𐤋𐤊', latin: 'mlk', meaning: { en: 'King', fr: 'Roi', ar: 'ملك' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤋𐤊𐤀', latin: 'mlkʾ', meaning: { en: 'Malaka (Málaga, Spain)', fr: 'Malaka (Málaga, Espagne)', ar: 'مالاكا (مالقة، إسبانيا)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤌𐤋𐤒𐤓𐤕', latin: 'mlqrt', meaning: { en: 'Melqart ("King of the City")', fr: 'Melqart ("Roi de la Cité")', ar: 'ملقرط ("ملك المدينة")' }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤌𐤌𐤋𐤊𐤕', latin: 'mmlkt', meaning: { en: 'Kingdom', fr: 'Royaume', ar: 'مملكة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤌𐤍', latin: 'mn', meaning: { en: 'From', fr: 'De', ar: 'من' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤌𐤍𐤇𐤄', latin: 'mnḥh', meaning: { en: 'Offering, gift', fr: 'Offrande, cadeau', ar: 'تقدمة، هدية' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤌𐤍𐤉𐤍𐤊𐤎', latin: 'mninks', meaning: { en: 'Meninx (Djerba, Tunisia)', fr: 'Meninx (Djerba, Tunisie)', ar: 'مينينكس (جربة، تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤌𐤎𐤂', latin: 'msg', meaning: { en: 'To mix', fr: 'Mélanger', ar: 'يمزج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤎𐤊', latin: 'msk', meaning: { en: 'To mix', fr: 'Mélanger', ar: 'يخلط' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤎𐤎', latin: 'mss', meaning: { en: 'To dissolve, melt', fr: 'Dissoudre, fondre', ar: 'يذوب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤏𐤃', latin: "mʿd", meaning: { en: 'To slip, stagger', fr: 'Glisser, chanceler', ar: 'يزل، يترنح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤏𐤋', latin: "mʿl", meaning: { en: 'Above, upward', fr: 'Au-dessus, vers le haut', ar: 'فوق، إلى أعلى' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤌𐤏𐤈', latin: "mʿṭ", meaning: { en: 'Little, few', fr: 'Peu', ar: 'قليل' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤌𐤑𐤀', latin: "mṣ'", meaning: { en: 'To find', fr: 'Trouver', ar: 'يجد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤑𐤄', latin: 'mṣh', meaning: { en: 'Unleavened bread', fr: 'Pain sans levain', ar: 'خبز فطير' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤌𐤑𐤓𐤌', latin: 'mṣrm', meaning: { en: 'Egypt - An important cultural and commercial center for the Phoenicians', fr: 'Égypte - Un centre culturel et commercial important pour les Phéniciens', ar: 'مصر - مركز حضاري وتجاري مهم للفينيقيين' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤌𐤒𐤃𐤔', latin: 'mqdš', meaning: { en: 'Sanctuary', fr: 'Sanctuaire', ar: 'مقدس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤒𐤅𐤌', latin: 'mqwm', meaning: { en: 'Place', fr: 'Lieu', ar: 'مكان' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤒𐤓', latin: 'mqr', meaning: { en: 'Source, spring', fr: 'Source', ar: 'مصدر، نبع' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤓', latin: 'mr', meaning: { en: 'Bitter', fr: 'Amer', ar: 'مر' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤌𐤓𐤃', latin: 'mrd', meaning: { en: 'To rebel', fr: 'Se rebeller', ar: ' يتمرد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤔𐤇', latin: 'mšḥ', meaning: { en: 'To anoint', fr: 'Oindre', ar: 'يمسح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤌𐤔𐤋', latin: 'mšl', meaning: { en: 'To rule, proverb', fr: 'Gouverner, proverbe', ar: 'يحكم، مثل' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤌𐤔𐤐𐤇𐤄', latin: 'mšpḥh', meaning: { en: 'Family, clan', fr: 'Famille, clan', ar: 'عائلة، عشيرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤌𐤔𐤐𐤈', latin: 'mšpṭ', meaning: { en: 'Judgment', fr: 'Jugement', ar: 'حكم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤌𐤐𐤊', latin: 'mfk', meaning: { en: 'Turquoise', fr: 'Turquoise', ar: 'فيروز' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Context: Trade item.' } },
];