import type { GlossaryEntry } from '../../types';

export const nun: GlossaryEntry[] = [
  // Nun - 𐤍
  { phoenician: '𐤍', latin: 'n', meaning: { en: 'Nun (fourteenth letter)', fr: 'Nun (quatorzième lettre)', ar: 'نون (الحرف الرابع عشر)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤍𐤀', latin: "n'", meaning: { en: 'Please, now', fr: 'S\'il vous plaît, maintenant', ar: 'رجاءً، الآن' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤍𐤀𐤄', latin: "n'h", meaning: { en: 'Beautiful, fitting', fr: 'Beau, convenable', ar: 'جميل، لائق' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤍𐤀𐤌', latin: "n'm", meaning: { en: 'Pleasant, utterance', fr: 'Agréable, parole', ar: 'لطيف، قول' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤍𐤁𐤀', latin: "nb'", meaning: { en: 'To prophesy', fr: 'Prophétiser', ar: 'يتنبأ' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤍𐤁𐤋', latin: 'nbl', meaning: { en: 'Foolish, wither', fr: 'Insensé, se flétrir', ar: 'أحمق، يذبل' }, grammar: { pos: 'Adjective', notes: 'Also a verb.' } },
  { phoenician: '𐤍𐤂𐤃', latin: 'ngd', meaning: { en: 'In front of, ruler', fr: 'Devant, souverain', ar: 'أمام، حاكم' }, grammar: { pos: 'Preposition', notes: 'Also a noun.' } },
  { phoenician: '𐤍𐤂𐤄', latin: 'ngh', meaning: { en: 'To shine', fr: 'Briller', ar: 'يضيء' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤂𐤏', latin: "ngʿ", meaning: { en: 'To touch, strike', fr: 'Toucher, frapper', ar: 'يلمس، يضرب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤃𐤇', latin: 'ndḥ', meaning: { en: 'To impel, banish', fr: 'Pousser, bannir', ar: 'يدفع، ينفي' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤍𐤃𐤓', latin: 'ndr', meaning: { en: 'Vow', fr: 'Vœu', ar: 'نذر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤍𐤃𐤏', latin: "ndʿ", meaning: { en: 'To drive away', fr: 'Chasser', ar: 'يطرد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤄𐤌', latin: 'nhm', meaning: { en: 'To growl, roar', fr: 'Grogner, rugir', ar: 'يزمجر، يزأر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤄𐤓', latin: 'nhr', meaning: { en: 'River', fr: 'Rivière', ar: 'نهر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤍𐤅𐤃', latin: 'nwd', meaning: { en: 'To wander', fr: 'Errer', ar: 'يهيم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤅𐤄', latin: 'nwh', meaning: { en: 'To rest', fr: 'Se reposer', ar: 'يرتاح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤅𐤓𐤄', latin: 'nwrh', meaning: { en: 'Nora, Sardinia', fr: 'Nora, Sardaigne', ar: 'نورا، سردينيا' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤍𐤅𐤎', latin: 'nws', meaning: { en: 'To flee', fr: 'Fuir', ar: 'يهرب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤇𐤌', latin: 'nḥm', meaning: { en: 'To comfort', fr: 'Consoler', ar: 'يعزي' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤍𐤇𐤔', latin: 'nḥš', meaning: { en: 'Snake, serpent', fr: 'Serpent', ar: 'ثعبان، حية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤍𐤇𐤔𐤕', latin: 'nḥšt', meaning: { en: 'Bronze, copper', fr: 'Bronze, cuivre', ar: 'برونز، نحاس' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤍𐤈𐤄', latin: 'nṭh', meaning: { en: 'To stretch out, incline', fr: 'Étendre, incliner', ar: 'يمد، يميل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤈𐤏', latin: "nṭʿ", meaning: { en: 'To plant', fr: 'Planter', ar: 'يزرع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤈𐤐', latin: 'nṭp', meaning: { en: 'To drop, drip', fr: 'Tomber goutte à goutte', ar: 'يقطر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤈𐤍', latin: 'ntn', meaning: { en: 'To give', fr: 'Donner', ar: 'يعطي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤊𐤄', latin: 'nkh', meaning: { en: 'To strike', fr: 'Frapper', ar: 'يضرب' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤍𐤊𐤓', latin: 'nkr', meaning: { en: 'Foreign, strange', fr: 'Étranger, étrange', ar: 'غريب، أجنبي' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤍𐤎𐤏', latin: "nsʿ", meaning: { en: 'To journey, set out', fr: 'Voyager, partir', ar: 'يسافر، يرتحل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤎𐤄', latin: 'nsh', meaning: { en: 'To test, try', fr: 'Tester, essayer', ar: 'يختبر، يجرب' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤍𐤎𐤊', latin: 'nsk', meaning: { en: 'To pour out', fr: 'Verser', ar: 'يسكب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤏𐤌', latin: "nʿm", meaning: { en: 'Pleasant', fr: 'Agréable', ar: 'لطيف' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤍𐤐𐤋', latin: 'npl', meaning: { en: 'To fall', fr: 'Tomber', ar: 'يسقط' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤐𐤔', latin: 'npš', meaning: { en: 'Soul, self, person', fr: 'Âme, soi-même, personne', ar: 'نفس، ذات، شخص' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤍𐤑𐤓', latin: 'nṣr', meaning: { en: 'To guard, watch', fr: 'Garder, surveiller', ar: 'يحرس، يراقب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤒𐤄', latin: 'nqh', meaning: { en: 'To be innocent', fr: 'Être innocent', ar: 'يكون بريئًا' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤍𐤔𐤀', latin: "nš'", meaning: { en: 'To lift, carry', fr: 'Soulever, porter', ar: 'يرفع، يحمل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤔𐤓', latin: 'nšr', meaning: { en: 'Eagle, vulture', fr: 'Aigle, vautour', ar: 'نسر، عقاب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤍𐤔𐤒', latin: 'nšq', meaning: { en: 'To kiss', fr: 'Embrasser', ar: 'يقبل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤍𐤐𐤊', latin: 'npk', meaning: { en: 'Turquoise', fr: 'Turquoise', ar: 'فيروز' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Valuable gemstone mined in Sinai (Egyptian origin: mfkꜣ.t).' } },
  { phoenician: '𐤍𐤕𐤓', latin: 'ntr', meaning: { en: 'Natron', fr: 'Natron', ar: 'نطرون' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Used in mummification, purification, and as a salt (Egyptian origin: nṯr).' } },
];
