import type { GlossaryEntry } from '../../types';

export const pe: GlossaryEntry[] = [
  // Pe - 𐤐
  { phoenician: '𐤐', latin: 'p', meaning: { en: 'Here; Pe (seventeenth letter)', fr: 'Ici; Pe (dix-septième lettre)', ar: 'هنا؛ فاء (الحرف السابع عشر)' }, grammar: { pos: 'Adverb', notes: 'Also a noun (letter name).' } },
  { phoenician: '𐤐𐤀𐤄', latin: "p'h", meaning: { en: 'Corner, side', fr: 'Coin, côté', ar: 'زاوية، جانب' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤐𐤀𐤓', latin: "p'r", meaning: { en: 'To glorify, beautify', fr: 'Glorifier, embellir', ar: 'يمجد، يجمل' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤐𐤂𐤏', latin: "pgʿ", meaning: { en: 'To meet, encounter', fr: 'Rencontrer', ar: 'يلتقي، يصادف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤂𐤓', latin: 'pgr', meaning: { en: 'Corpse', fr: 'Cadavre', ar: 'جثة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤐𐤃𐤄', latin: 'pdh', meaning: { en: 'To redeem, ransom', fr: 'Racheter, rançonner', ar: 'يفدي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤄', latin: 'ph', meaning: { en: 'Mouth', fr: 'Bouche', ar: 'فم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤐𐤅', latin: 'pw', meaning: { en: 'Here', fr: 'Ici', ar: 'هنا' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤐𐤅𐤄', latin: 'pwh', meaning: { en: 'To blow, speak', fr: 'Souffler, parler', ar: 'ينفخ، يتكلم' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤐𐤅𐤑', latin: 'pwṣ', meaning: { en: 'To scatter', fr: 'Disperser', ar: 'يشتت' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤇𐤃', latin: 'pḥd', meaning: { en: 'To fear, dread', fr: 'Craindre, redouter', ar: 'يخاف، يخشى' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤈𐤏', latin: "pṭʿ", meaning: { en: 'Suddenly', fr: 'Soudainement', ar: 'فجأة' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤐𐤋𐤀', latin: "pl'", meaning: { en: 'Wonder, miracle', fr: 'Merveille, miracle', ar: 'عجيبة، معجزة' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤐𐤋𐤂', latin: 'plg', meaning: { en: 'To divide', fr: 'Diviser', ar: 'يقسم' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤐𐤋𐤈', latin: 'plṭ', meaning: { en: 'To escape', fr: 'S\'échapper', ar: 'ينجو' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤐𐤍', latin: 'pn', meaning: { en: 'Face', fr: 'Visage', ar: 'وجه' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' } },
  { phoenician: '𐤐𐤎𐤇', latin: 'psḥ', meaning: { en: 'Passover', fr: 'Pâque', ar: 'فصح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤐𐤎𐤋', latin: 'psl', meaning: { en: 'Idol, to carve', fr: 'Idole, sculpter', ar: 'صنم، ينحت' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤐𐤏𐤋', latin: "pʿl", meaning: { en: 'To do, make', fr: 'Faire', ar: 'يفعل، يعمل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤏𐤌', latin: "pʿm", meaning: { en: 'Foot, time', fr: 'Pied, fois', ar: 'قدم، مرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤐𐤒𐤃', latin: 'pqd', meaning: { en: 'To visit, appoint', fr: 'Visiter, nommer', ar: 'يزور، يعين' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤒𐤇', latin: 'pqḥ', meaning: { en: 'To open (eyes)', fr: 'Ouvrir (les yeux)', ar: 'يفتح (عينيه)' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤓', latin: 'pr', meaning: { en: 'Bull', fr: 'Taureau', ar: 'ثور' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤐𐤓𐤃', latin: 'prd', meaning: { en: 'To separate', fr: 'Séparer', ar: 'يفصل' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤐𐤓𐤇', latin: 'prḥ', meaning: { en: 'Flower, to blossom', fr: 'Fleur, fleurir', ar: 'زهرة، يزهر' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤐𐤓𐤆𐤋', latin: 'przl', meaning: { en: 'Iron', fr: 'Fer', ar: 'حديد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤐𐤓𐤔', latin: 'prš', meaning: { en: 'To spread out, explain', fr: 'Étendre, expliquer', ar: 'ينشر، يشرح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤐𐤓𐤏', latin: "prʿ", meaning: { en: 'To let loose, leader', fr: 'Laisser libre, chef', ar: 'يطلق، قائد' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤐𐤔𐤏', latin: "pšʿ", meaning: { en: 'Transgression, rebellion', fr: 'Transgression, rébellion', ar: 'تعدي، تمرد' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤐𐤕𐤀', latin: "pt'", meaning: { en: 'Simple, foolish', fr: 'Simple, insensé', ar: 'بسيط، أحمق' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤐𐤕𐤇', latin: 'ptḥ', meaning: { en: 'To open, opening', fr: 'Ouvrir, ouverture', ar: 'يفتح، فتحة' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤐𐤕𐤉', latin: 'pty', meaning: { en: 'Simpleton', fr: 'Simple d\'esprit', ar: 'ساذج' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
];
