import type { GlossaryEntry } from '../../types';

export const resh: GlossaryEntry[] = [
  // Resh - 𐤓
  { phoenician: '𐤓', latin: 'r', meaning: { en: 'Resh (twentieth letter)', fr: 'Resh (vingtième lettre)', ar: 'راء (الحرف العشرون)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤓𐤀𐤄', latin: "r'h", meaning: { en: 'To see', fr: 'Voir', ar: 'يرى' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤀𐤄', latin: 'rʾh', meaning: { en: 'Lung', fr: 'Poumon', ar: 'رئة' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Essential for respiration' } },
  { phoenician: '𐤓𐤀𐤔', latin: "r'š", meaning: { en: 'Head, chief', fr: 'Tête, chef', ar: 'رأس، رئيس' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤓𐤁', latin: 'rb', meaning: { en: 'Great, many', fr: 'Grand, beaucoup', ar: 'عظيم، كثير' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤓𐤁𐤏', latin: "rbʿ", meaning: { en: 'Fourth, square', fr: 'Quatrième, carré', ar: 'رابع، مربع' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤓𐤂𐤋', latin: 'rgl', meaning: { en: 'Foot', fr: 'Pied', ar: 'رجل' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤓𐤃𐤐', latin: 'rdp', meaning: { en: 'To pursue', fr: 'Poursuivre', ar: 'يطارد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤅𐤇', latin: 'rwḥ', meaning: { en: 'Spirit, wind', fr: 'Esprit, vent', ar: 'روح، ريح' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤓𐤅𐤌', latin: 'rwm', meaning: { en: 'To be high, exalted', fr: 'Être haut, exalté', ar: 'يرتفع، يتعالى' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤅𐤌', latin: 'rwm / rwmy', meaning: { en: 'Roman, refers to Rome or Romans.', fr: 'Romain, se réfère à Rome ou aux Romains.', ar: 'روماني، إشارة إلى روما أو الرومان.' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤓𐤆', latin: 'rz', meaning: { en: 'Run', fr: 'Courir', ar: 'يجري' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤇', latin: 'rḥ', meaning: { en: 'Smell', fr: 'Sentir', ar: 'يشم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤇𐤁', latin: 'rḥb', meaning: { en: 'Wide, broad', fr: 'Large', ar: 'واسع، عريض' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤓𐤇𐤌', latin: 'rḥm', meaning: { en: 'Womb, compassion', fr: 'Utérus, compassion', ar: 'رحم، رحمة' }, grammar: { pos: 'Noun', gender: 'm', number: 'p', notes: 'Also an abstract noun.' } },
  { phoenician: '𐤓𐤇𐤑', latin: 'rḥṣ', meaning: { en: 'To wash', fr: 'Laver', ar: 'يغسل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤇𐤒', latin: 'rḥq', meaning: { en: 'Far, distant', fr: 'Loin, distant', ar: 'بعيد' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤓𐤉𐤁', latin: 'ryb', meaning: { en: 'Quarrel, dispute', fr: 'Querelle, dispute', ar: 'خصام، نزاع' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤓𐤉𐤇', latin: 'ryḥ', meaning: { en: 'Scent, odor', fr: 'Odeur, parfum', ar: 'رائحة، عطر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤓𐤊', latin: 'rk', meaning: { en: 'Tender, soft', fr: 'Tendre, doux', ar: 'رقيق، ناعم' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤓𐤊𐤁', latin: 'rkb', meaning: { en: 'To ride', fr: 'Monter (un animal)', ar: 'يركب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤌𐤇', latin: 'rmḥ', meaning: { en: 'Spear, lance', fr: 'Lance', ar: 'رمح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤓𐤌𐤌', latin: 'rmm', meaning: { en: 'To rise, be exalted', fr: 'S\'élever, être exalté', ar: 'يرتفع، يتعالى' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤓𐤌𐤍', latin: 'rimmūn', meaning: { en: 'Pomegranate', fr: 'Grenade', ar: 'رمان' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤓𐤍', latin: 'rn', meaning: { en: 'Sing', fr: 'Chanter', ar: 'يغني' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤏', latin: "rʿ", meaning: { en: 'Evil, bad', fr: 'Mal, mauvais', ar: 'شر، سيء' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤓𐤏𐤄', latin: "rʿh", meaning: { en: 'To pasture, shepherd', fr: 'Paître, berger', ar: 'يرعى، راعٍ' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤓𐤐𐤀', latin: "rp'", meaning: { en: 'To heal', fr: 'Guérir', ar: 'يشفي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤑𐤄', latin: 'rṣh', meaning: { en: 'To be pleased with', fr: 'Être satisfait de', ar: 'يرضى بـ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤓𐤒', latin: 'rq', meaning: { en: 'Empty', fr: 'Vide', ar: 'فارغ' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤓𐤓', latin: 'rr', meaning: { en: 'To drip, semen, flow', fr: 'Goutter, sperme, couler', ar: 'يقطر, مني, يتدفق' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'connected with sexuality.' } },
  { phoenician: '𐤓𐤔𐤐', latin: "ršp", meaning: { en: "Resheph, god of war and plague", fr: "Reshep, dieu de la guerre et de la peste", ar: "رشپ، إله الحرب والطاعون" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤓𐤔𐤐𐤍', latin: 'ršpn', meaning: { en: 'Ruspina (Monastir, Tunisia)', fr: 'Ruspina (Monastir, Tunisie)', ar: 'روسبينا (المنستير، تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
];