import type { GlossaryEntry } from '../../types';

export const shin: GlossaryEntry[] = [
  // Shin - 𐤔
  { phoenician: '𐤔', latin: 'š', meaning: { en: 'Shin (twenty-first letter)', fr: 'Shin (vingt-et-unième lettre)', ar: 'شين (الحرف الحادي والعشرون)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤔', latin: 'š', meaning: { en: 'Sheep (individual)', fr: 'Mouton (individu)', ar: 'خروف (فرد)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤀𐤋', latin: "š'l", meaning: { en: 'To ask, inquire', fr: 'Demander, s\'enquérir', ar: 'يسأل، يستعلم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤀𐤓', latin: "š'r", meaning: { en: 'Remnant, rest', fr: 'Reste', ar: 'بقية' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤁', latin: 'šb', meaning: { en: 'To return', fr: 'Retourner', ar: 'يرجع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤁𐤏', latin: "šbʿ", meaning: { en: 'Seven, to swear', fr: 'Sept, jurer', ar: 'سبعة، يقسم' }, grammar: { pos: 'Numeral', notes: 'Also a verb (N-stem).' } },
  { phoenician: '𐤔𐤁𐤓', latin: 'šbr', meaning: { en: 'To break', fr: 'Casser', ar: 'يكسر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤁𐤕', latin: 'šbt', meaning: { en: 'To cease, rest', fr: 'Cesser, se reposer', ar: 'يتوقف، يستريح' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤃𐤄', latin: 'šdh', meaning: { en: 'Field', fr: 'Champ', ar: 'حقل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤃𐤓𐤐', latin: 'šdrp', meaning: { en: "Shadrapa — a healing god associated with serpents", fr: "Shadrapa — un dieu de la guérison associé aux serpents", ar: "شدرپ — إله شفاء مرتبط بالأفاعي" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤔𐤅𐤁', latin: 'šwb', meaning: { en: 'To return, turn back', fr: 'Retourner', ar: 'يعود، يرجع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤅𐤓', latin: 'šwr', meaning: { en: 'Ox, bull; wall', fr: 'Bœuf, taureau; mur', ar: 'ثور؛ سور' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤉𐤔', latin: 'šīš', meaning: { en: 'Moth', fr: 'Mite', ar: 'عثة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤇𐤕', latin: 'šḥt', meaning: { en: 'Pit, to destroy', fr: 'Fosse, détruire', ar: 'حفرة، يدمر' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Also a verb (D-stem).' } },
  { phoenician: '𐤔𐤊𐤁', latin: 'škb', meaning: { en: 'To lie down', fr: 'Se coucher', ar: 'يضطجع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤊𐤓', latin: 'škr', meaning: { en: 'To be drunk', fr: 'Être ivre', ar: 'يسكر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤋𐤇', latin: 'šlḥ', meaning: { en: 'To send', fr: 'Envoyer', ar: 'يرسل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤋𐤋', latin: 'šll', meaning: { en: 'Spoil, plunder', fr: 'Butin, pillage', ar: 'غنيمة، سلب' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤋𐤌', latin: 'šlm', meaning: { en: 'Peace, welfare; to be complete', fr: 'Paix, bien-être; être complet', ar: 'سلام، عافية؛ يكتمل' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤔𐤋𐤔', latin: 'šlš', meaning: { en: 'Three', fr: 'Trois', ar: 'ثلاثة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤔𐤌', latin: 'šm', meaning: { en: 'Name', fr: 'Nom', ar: 'اسم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤌𐤏', latin: "šmʿ", meaning: { en: 'To hear, listen', fr: 'Entendre, écouter', ar: 'يسمع، يصغي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤌𐤌', latin: 'šmm', meaning: { en: 'Heaven, sky', fr: 'Ciel', ar: 'سماء' }, grammar: { pos: 'Noun', gender: 'm', number: 'p' } },
  { phoenician: '𐤔𐤌𐤍', latin: 'šmn', meaning: { en: 'Oil, fat', fr: 'Huile, graisse', ar: 'زيت، دهن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤌𐤔', latin: 'šmš', meaning: { en: 'Sun', fr: 'Soleil', ar: 'شمس' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤔𐤌𐤔', latin: 'šmš', meaning: { en: "Shamash — sun god, imported from Mesopotamian and Canaanite traditions", fr: "Shamash — dieu du soleil, importé des traditions mésopotamiennes et cananéennes", ar: "شمش — إله الشمس، مستورد من تقاليد بلاد ما بين النهرين وكنعان" }, grammar: { pos: 'Noun', gender: 'm', number: 's' }, category: 'theonym' },
  { phoenician: '𐤔𐤍', latin: 'šn', meaning: { en: 'Tooth', fr: 'Dent', ar: 'سن' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤔𐤍𐤄', latin: 'šnh', meaning: { en: 'Year', fr: 'Année', ar: 'سنة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤔𐤍𐤉', latin: 'šny', meaning: { en: 'Two, second', fr: 'Deux, second', ar: 'اثنان، ثانٍ' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤔𐤏𐤓', latin: "šʿr", meaning: { en: 'Gate', fr: 'Porte (de ville)', ar: 'بوابة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤐𐤊', latin: 'špk', meaning: { en: 'To pour out', fr: 'Verser', ar: 'يسكب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤐𐤈', latin: 'špṭ', meaning: { en: 'To judge, ruler', fr: 'Juger, dirigeant', ar: 'يحكم، حاكم' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤔𐤒𐤋', latin: 'šql', meaning: { en: 'Shekel, to weigh', fr: 'Sicle, peser', ar: 'شيكل، يزن' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤔𐤓', latin: 'šr', meaning: { en: 'Prince, official', fr: 'Prince, officiel', ar: 'أمير، مسؤول' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤓𐤃𐤍', latin: 'šrdn', meaning: { en: 'Sardinia - An important island for trade and resources.', fr: 'Sardaigne - Île importante pour le commerce et les ressources.', ar: 'سردينيا - جزيرة مهمة للتجارة والموارد.' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤔𐤓𐤔', latin: 'šrš', meaning: { en: 'Root', fr: 'Racine', ar: 'جذر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤔', latin: 'šš', meaning: { en: 'Six', fr: 'Six', ar: 'ستة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤔𐤔𐤌', latin: 'ššm', meaning: { en: 'Sesame', fr: 'Sésame', ar: 'سمسم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤔𐤕𐤄', latin: 'šth', meaning: { en: 'To drink', fr: 'Boire', ar: 'يشرب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤔𐤊𐤉𐤕', latin: 'škyt', meaning: { en: 'Ship', fr: 'Navire', ar: 'سفينة' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: 'Egyptian origin: sktʸ. Context: Denotes a specific vessel.' } },
  { phoenician: '𐤔𐤔', latin: 'šeš', meaning: { en: 'Linen', fr: 'Lin', ar: 'كتان' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Egyptian origin: šs. Context: High-quality Egyptian textile.' } },
];