import type { GlossaryEntry } from '../../types';

export const taw: GlossaryEntry[] = [
  // Taw - 𐤕
  { phoenician: '𐤕', latin: 't', meaning: { en: 'Mark; Taw (twenty-second letter)', fr: 'Marque; Taw (vingt-deuxième lettre)', ar: 'علامة؛ تاء (الحرف الثاني والعشرون)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤀𐤍𐤄', latin: "t'nh", meaning: { en: 'Fig, fig tree', fr: 'Figue, figuier', ar: 'تين، شجرة تين' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤀𐤅', latin: "t'w", meaning: { en: 'Boundary, mark', fr: 'Limite, marque', ar: 'حد، علامة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤁𐤂𐤂', latin: 'tbgg', meaning: { en: 'Thugga (Dougga, Tunisia)', fr: 'Thugga (Dougga, Tunisie)', ar: 'ثوجا (دقّة، تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤕𐤁𐤍', latin: 'tbn', meaning: { en: 'Straw', fr: 'Paille', ar: 'تبن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤁𐤅𐤍𐤄', latin: 'tbwnh', meaning: { en: 'Understanding, intelligence', fr: 'Compréhension, intelligence', ar: 'فهم، ذكاء' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤄𐤋𐤄', latin: 'thlh', meaning: { en: 'Praise, song of praise', fr: 'Louange, chant de louange', ar: 'تسبيح، ترنيمة حمد' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤄𐤅𐤌', latin: 'thwm', meaning: { en: 'The deep, abyss', fr: 'L\'abîme, le profond', ar: 'الهاوية، اللجة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤅𐤃𐤄', latin: 'twdh', meaning: { en: 'Thanksgiving, praise', fr: 'Action de grâce, louange', ar: 'شكر، تسبيح' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤅𐤋𐤃𐤄', latin: 'twldh', meaning: { en: 'Generation, descent', fr: 'Génération, descendance', ar: 'جيل، سلالة' }, grammar: { pos: 'Noun', gender: 'f', number: 'p' } },
  { phoenician: '𐤕𐤅𐤓', latin: 'twr', meaning: { en: 'To explore, spy out', fr: 'Explorer, espionner', ar: 'يستكشف، يتجسس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤅𐤓𐤄', latin: 'twrh', meaning: { en: 'Law, instruction', fr: 'Loi, instruction', ar: 'شريعة، تعليم' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤇𐤕', latin: 'tḥt', meaning: { en: 'Under, beneath', fr: 'Sous', ar: 'تحت' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤕𐤇𐤍𐤄', latin: 'tḥnh', meaning: { en: 'Supplication, favor', fr: 'Supplication, faveur', ar: 'توسل، نعمة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤉𐤓𐤅𐤔', latin: 'tyrwš', meaning: { en: 'New wine', fr: 'Vin nouveau', ar: 'خمر جديدة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤊', latin: 'tk', meaning: { en: 'Midst', fr: 'Milieu', ar: 'وسط' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤊𐤍', latin: 'tkn', meaning: { en: 'To measure, establish', fr: 'Mesurer, établir', ar: 'يقيس، يؤسس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤋', latin: 'tl', meaning: { en: 'Ruin-heap, mound', fr: 'Amoncellement de ruines, monticule', ar: 'تل، كومة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤋𐤄', latin: 'tlh', meaning: { en: 'To hang', fr: 'Pendre', ar: 'يعلق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤋𐤌', latin: 'tlm', meaning: { en: 'Furrow', fr: 'Sillon', ar: 'تلم، خط' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤋𐤌𐤕', latin: 'tlmt', meaning: { en: "Tilmut — a goddess associated with the afterlife and chthonic powers", fr: "Tilmut — une déesse associée à l'au-delà et aux puissances chthoniennes", ar: "تيلموت — إلهة مرتبطة بالآخرة والقوى السفلية" }, grammar: { pos: 'Noun', gender: 'f', number: 's' }, category: 'theonym' },
  { phoenician: '𐤕𐤌', latin: 'tm', meaning: { en: 'To be complete, perfect', fr: 'Être complet, parfait', ar: 'يكتمل، يكون كاملاً' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤌𐤊', latin: 'tmk', meaning: { en: 'To grasp, support, hold', fr: 'Saisir, soutenir, tenir', ar: 'يمسك، يدعم' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤌𐤉𐤃', latin: 'tmyd', meaning: { en: 'Continually, always', fr: 'Continuellement, toujours', ar: 'باستمرار، دائماً' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤕𐤌𐤉𐤌', latin: 'tmym', meaning: { en: 'Perfect, blameless, complete', fr: 'Parfait, sans défaut, complet', ar: 'كامل، بلا عيب' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤕𐤌𐤌', latin: 'tmm', meaning: { en: 'To be complete; integrity', fr: 'Être complet; intégrité', ar: 'يكتمل؛ نزاهة' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Noun form `tōm`.' } },
  { phoenician: '𐤕𐤌𐤓', latin: 'tmr', meaning: { en: 'Date palm, dates', fr: 'Palmier-dattier, dattes', ar: 'نخلة، تمر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤍', latin: 'tn', meaning: { en: 'Jackal', fr: 'Chacal', ar: 'ابن آوى' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤍𐤍', latin: 'tnn', meaning: { en: 'Thenae (likely Thyna, near Sfax, Tunisia)', fr: 'Thenae (probablement Thyna, près de Sfax, Tunisie)', ar: 'ثيناي (على الأرجح طينة، بالقرب من صفاقس، تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤕𐤍𐤉𐤍', latin: 'tnyn', meaning: { en: 'Serpent, dragon, sea monster', fr: 'Serpent, dragon, monstre marin', ar: 'ثعبان، تنين، وحش بحري' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤁𐤕', latin: 'tbt', meaning: { en: 'Box', fr: 'Boîte', ar: 'صندوق' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: '(From Egyptian db.t).' } },
  { phoenician: '𐤕𐤇𐤎', latin: 'tḥs', meaning: { en: 'Egyptian leather', fr: 'Cuir égyptien', ar: 'جلد مصري' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: '(An imported Egyptian material).' } },
  { phoenician: '𐤕𐤕', latin: 'tt', meaning: { en: 'Jar', fr: 'Jarre', ar: 'جرة' }, grammar: { pos: 'Noun', gender: 'f', number: 's', notes: '(From Egyptian db.t or tb.t).' } },
  { phoenician: '𐤕𐤁𐤋', latin: 'tbl', meaning: { en: 'World, universe', fr: 'Monde, univers', ar: 'عالم, كون' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤐𐤇', latin: 'tpḥ', meaning: { en: 'Apple', fr: 'Pomme', ar: 'تفاح' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
];