import type { GlossaryEntry } from '../../types';

export const taw: GlossaryEntry[] = [
  // Taw - 𐤕
  { phoenician: '𐤕', latin: 't', meaning: { en: 'Mark; Taw (twenty-second letter)', fr: 'Marque; Taw (vingt-deuxième lettre)', ar: 'علامة؛ تاء (الحرف الثاني والعشرون)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤀𐤅', latin: "t'w", meaning: { en: 'Boundary, mark', fr: 'Limite, marque', ar: 'حد، علامة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤁𐤍', latin: 'tbn', meaning: { en: 'Straw', fr: 'Paille', ar: 'تبن' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤁𐤅𐤍𐤄', latin: 'tbwnh', meaning: { en: 'Understanding, intelligence', fr: 'Compréhension, intelligence', ar: 'فهم، ذكاء' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤄𐤅𐤌', latin: 'thwm', meaning: { en: 'The deep, abyss', fr: 'L\'abîme, le profond', ar: 'الهاوية، اللجة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤅𐤃𐤄', latin: 'twdh', meaning: { en: 'Thanksgiving, praise', fr: 'Action de grâce, louange', ar: 'شكر، تسبيح' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤅𐤋𐤃𐤄', latin: 'twldh', meaning: { en: 'Generation, descent', fr: 'Génération, descendance', ar: 'جيل، سلالة' }, grammar: { pos: 'Noun', gender: 'f', number: 'p' } },
  { phoenician: '𐤕𐤅𐤓', latin: 'twr', meaning: { en: 'To explore, spy out', fr: 'Explorer, espionner', ar: 'يستكشف، يتجسس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤅𐤓𐤄', latin: 'twrh', meaning: { en: 'Law, instruction', fr: 'Loi, instruction', ar: 'شريعة، تعليم' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤇𐤕', latin: 'tḥt', meaning: { en: 'Under, beneath', fr: 'Sous', ar: 'تحت' }, grammar: { pos: 'Preposition' } },
  { phoenician: '𐤕𐤇𐤍𐤄', latin: 'tḥnh', meaning: { en: 'Supplication, favor', fr: 'Supplication, faveur', ar: 'توسل، نعمة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤉𐤓𐤅𐤔', latin: 'tyrwš', meaning: { en: 'New wine', fr: 'Vin nouveau', ar: 'خمر جديدة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤊', latin: 'tk', meaning: { en: 'Midst', fr: 'Milieu', ar: 'وسط' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤊𐤍', latin: 'tkn', meaning: { en: 'To measure, establish', fr: 'Mesurer, établir', ar: 'يقيس، يؤسس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤋', latin: 'tl', meaning: { en: 'Ruin-heap, mound', fr: 'Amoncellement de ruines, monticule', ar: 'تل، كومة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤋𐤄', latin: 'tlh', meaning: { en: 'To hang', fr: 'Pendre', ar: 'يعلق' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤋𐤌', latin: 'tlm', meaning: { en: 'Furrow', fr: 'Sillon', ar: 'تلم، خط' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤌', latin: 'tm', meaning: { en: 'To be complete, perfect', fr: 'Être complet, parfait', ar: 'يكتمل، يكون كاملاً' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤌𐤓', latin: 'tmr', meaning: { en: 'Date palm', fr: 'Palmier-dattier', ar: 'نخلة تمر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤌𐤉𐤃', latin: 'tmyd', meaning: { en: 'Continually, always', fr: 'Continuellement, toujours', ar: 'باستمرار، دائماً' }, grammar: { pos: 'Adverb' } },
  { phoenician: '𐤕𐤌𐤌', latin: 'tmm', meaning: { en: 'To be complete; integrity', fr: 'Être complet; intégrité', ar: 'يكتمل؛ نزاهة' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Noun form `tōm`.' } },
  { phoenician: '𐤕𐤍', latin: 'tn', meaning: { en: 'Jackal', fr: 'Chacal', ar: 'ابن آوى' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤍𐤅𐤓', latin: 'tnwr', meaning: { en: 'Oven, furnace', fr: 'Four, fournaise', ar: 'فرن، تنور' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤕𐤏𐤄', latin: "tʿh", meaning: { en: 'To wander, err', fr: 'Errer, se tromper', ar: 'يضل، يخطئ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤐𐤋𐤄', latin: 'tplh', meaning: { en: 'Prayer', fr: 'Prière', ar: 'صلاة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤐𐤔', latin: 'tpś', meaning: { en: 'To seize, catch', fr: 'Saisir, attraper', ar: 'يمسك، يقبض على' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤕𐤒𐤅𐤄', latin: 'tqwh', meaning: { en: 'Hope', fr: 'Espoir', ar: 'أمل' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤓𐤅𐤌𐤄', latin: 'trwmh', meaning: { en: 'Contribution, offering', fr: 'Contribution, offrande', ar: 'مساهمة، تقدمة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤕𐤔𐤏', latin: "tšʿ", meaning: { en: 'Nine', fr: 'Neuf', ar: 'تسعة' }, grammar: { pos: 'Numeral' } },
  { phoenician: '𐤕𐤔𐤅𐤁𐤄', latin: 'tšwbh', meaning: { en: 'Return, repentance', fr: 'Retour, repentance', ar: 'عودة، توبة' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
];
