
import type { GlossaryEntry } from '../../types';

export const teth: GlossaryEntry[] = [
  // Teth - 𐤈
  { phoenician: '𐤈', latin: 'ṭ', meaning: { en: 'Teth (ninth letter)', fr: 'Teth (neuvième lettre)', ar: 'طاء (الحرف التاسع)' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤈𐤁', latin: 'ṭb', meaning: { en: 'Good', fr: 'Bon', ar: 'طَيِّب' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤈𐤁𐤇', latin: 'ṭbḥ', meaning: { en: 'To slaughter, butcher', fr: 'Abattre, boucher', ar: 'يذبح، يجزر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤈𐤁𐤇', latin: 'ṭbḥ', meaning: { en: 'Butcher', fr: 'Boucher', ar: 'جزار' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤈𐤁𐤄', latin: 'ṭbh', meaning: { en: 'Unit of weight', fr: 'Unité de poids', ar: 'وحدة وزن' }, grammar: { pos: 'Noun', gender: 'm' } },
  { phoenician: '𐤈𐤁𐤓', latin: 'ṭbr', meaning: { en: 'To break', fr: 'Casser', ar: 'يكسر' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: '[verify]' } },
  { phoenician: '𐤈𐤁𐤏', latin: "ṭbʿ", meaning: { en: 'Ring, signet ring', fr: 'Bague, sceau', ar: 'خاتم' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤈𐤁𐤏', latin: 'ṭbʿ', meaning: { en: 'To stamp a coin or seal', fr: 'Frapper une monnaie ou un sceau', ar: 'يسك عملة أو يختم' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤈𐤁𐤏𐤕', latin: 'ṭbʿt', meaning: { en: 'Stamped seal on a signet ring', fr: 'Sceau estampé sur une chevalière', ar: 'ختم منقوش على خاتم توقيع' }, grammar: { pos: 'Noun', gender: 'f' } },
  { phoenician: '𐤈𐤁𐤕', latin: 'ṭbt', meaning: { en: 'ṬBT (vocalisation and meaning uncertain)', fr: 'ṬBT (vocalisation et signification incertaines)', ar: 'طبت (النطق والمعنى غير مؤكدين)' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤈𐤄𐤓', latin: 'ṭhr', meaning: { en: 'Pure, clean', fr: 'Pur, propre', ar: 'طاهر، نظيف' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤈𐤄𐤅𐤓', latin: 'ṭhwr', meaning: { en: 'Pure', fr: 'Pur', ar: 'طَهُور' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤈𐤅𐤁', latin: 'ṭwb', meaning: { en: 'Goodness', fr: 'Bonté', ar: 'طيبة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤈𐤅𐤇', latin: 'ṭwḥ', meaning: { en: 'To plaster', fr: 'Plâtrer', ar: 'يطلي' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤈𐤅𐤓', latin: 'ṭwr', meaning: { en: 'Row, line', fr: 'Rangée, ligne', ar: 'صف، سطر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤈𐤇', latin: 'ṭḥ', meaning: { en: 'To plaster', fr: 'Plâtrer', ar: 'يطلي' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤈𐤇𐤍', latin: 'ṭḥn', meaning: { en: 'To grind', fr: 'Moudre', ar: 'يطحن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤈𐤉𐤈', latin: 'ṭyṭ', meaning: { en: 'Mud, clay', fr: 'Boue, argile', ar: 'طين' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤈𐤋', latin: 'ṭl', meaning: { en: 'Dew', fr: 'Rosée', ar: 'طل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤈𐤌𐤀', latin: "ṭm'", meaning: { en: 'To be unclean', fr: 'Être impur', ar: 'يكون نجسًا' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤈𐤍', latin: 'tēn', meaning: { en: 'Fig', fr: 'Figue', ar: 'تين' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤈𐤍𐤀', latin: "ṭn'", meaning: { en: 'To load', fr: 'Charger', ar: 'يحمل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤈𐤍𐤀', latin: 'ṭnʾ', meaning: { en: 'To erect (a monument)', fr: 'Ériger (un monument)', ar: 'يقيم (نصبًا تذكاريًا)' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤈𐤍𐤀', latin: 'ṭnʾ', meaning: { en: 'To place (in charge)', fr: 'Placer (responsable)', ar: 'يولّي (مسؤولية)' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤈𐤍𐤀', latin: 'ṭnʾ', meaning: { en: 'To provide, endow', fr: 'Fournir, doter', ar: 'يزود، يمنح' }, grammar: { pos: 'Verb' } },
  { phoenician: '𐤈𐤏𐤌', latin: "ṭʿm", meaning: { en: 'Taste, decree', fr: 'Goût, décret', ar: 'طعم، مرسوم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤈𐤐𐤍', latin: 'ṭpn', meaning: { en: 'ṬPN (vocalisation and meaning uncertain)', fr: 'ṬPN (vocalisation et signification incertaines)', ar: 'طفن (النطق والمعنى غير مؤكدين)' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤈𐤐𐤋', latin: 'ṭpl', meaning: { en: 'To smear', fr: 'Enduire', ar: 'يلطخ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤈𐤐𐤕𐤍', latin: 'ṭptn', meaning: { en: 'Tipaza (city in modern-day Algeria)', fr: 'Tipaza (ville en Algérie actuelle)', ar: 'تيبازة (مدينة في الجزائر الحالية)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤈𐤐𐤑𐤓', latin: 'ṭpṣr', meaning: { en: 'Thysdrus (modern-day Eljem, Tunisia)', fr: 'Thysdrus (El Jem actuelle, Tunisie)', ar: 'ثيسدروس (الجم الحالية، تونس)' }, grammar: { pos: 'Noun' }, category: 'location' },
  { phoenician: '𐤈𐤓𐤃', latin: 'ṭrd', meaning: { en: 'To pursue, chase', fr: 'Poursuivre, chasser', ar: 'يطارد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤈𐤓𐤔𐤕', latin: 'ṭršt', meaning: { en: 'ṬRŠT (vocalisation and meaning uncertain)', fr: 'ṬRŠT (vocalisation et signification incertaines)', ar: 'طرشت (النطق والمعنى غير مؤكدين)' }, grammar: { pos: 'Noun' }, category: 'personal_name' },
  { phoenician: '𐤈𐤓𐤐', latin: 'ṭrp', meaning: { en: 'To tear (prey)', fr: 'Déchirer (proie)', ar: 'يفترس' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
];
