import type { GlossaryEntry } from '../../types';

export const yodh: GlossaryEntry[] = [
  // Yodh - 𐤉
  { phoenician: '𐤉', latin: 'y', meaning: { en: 'Yodh (tenth letter)', fr: 'Yodh (dixième lettre)', ar: 'ياء (الحرف العاشر)' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤉𐤀𐤔', latin: "y'š", meaning: { en: 'To despair', fr: 'Désespérer', ar: 'ييأس' }, grammar: { pos: 'Verb', stem: 'N-stem' } },
  { phoenician: '𐤉𐤁𐤋', latin: 'ybl', meaning: { en: 'To bring, carry', fr: 'Apporter, porter', ar: 'يحضر، يحمل' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤉𐤁𐤌', latin: 'ybm', meaning: { en: "Husband's brother", fr: 'Beau-frère (frère du mari)', ar: 'أخ الزوج' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤁𐤔', latin: 'ybš', meaning: { en: 'Dry', fr: 'Sec', ar: 'جاف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤂𐤏', latin: "ygʿ", meaning: { en: 'To toil, be weary', fr: 'Peiner, être las', ar: 'يكدح، يتعب' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤂𐤓', latin: 'ygr', meaning: { en: 'To fear', fr: 'Craindre', ar: 'يخاف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤃', latin: 'yd', meaning: { en: 'Hand', fr: 'Main', ar: 'يد' }, grammar: { pos: 'Noun', gender: 'f', number: 's' } },
  { phoenician: '𐤉𐤃𐤏', latin: "ydʿ", meaning: { en: 'To know', fr: 'Savoir', ar: 'يعرف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤄𐤓', latin: 'yhr', meaning: { en: 'To be arrogant', fr: 'Être arrogant', ar: 'يتكبر' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤅𐤁𐤋', latin: 'ywbl', meaning: { en: 'Ram, jubilee, stream', fr: 'Bélier, jubilé, courant', ar: 'كبش، يوبيل، مجرى' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤅𐤌', latin: 'ywm', meaning: { en: 'Day', fr: 'Jour', ar: 'يوم' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤅𐤍', latin: 'ywn', meaning: { en: 'Mud, mire', fr: 'Boue, bourbier', ar: 'طين، وحل' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤇𐤋', latin: 'yḥl', meaning: { en: 'To wait, hope', fr: 'Attendre, espérer', ar: 'ينتظر، يأمل' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤉𐤈𐤁', latin: 'yṭb', meaning: { en: 'To be good', fr: 'Être bon', ar: 'يكون صالحًا' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤈𐤓', latin: 'ytr', meaning: { en: 'Remainder, excess', fr: 'Reste, excès', ar: 'بقية، فائض' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤉𐤍', latin: 'yyn', meaning: { en: 'Wine', fr: 'Vin', ar: 'خمر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤋𐤃', latin: 'yld', meaning: { en: 'Child, to give birth', fr: 'Enfant, accoucher', ar: 'ولد، يلد' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤉𐤋𐤋', latin: 'yll', meaning: { en: 'To wail, howl', fr: 'Gémir, hurler', ar: 'يولول، يعوي' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤉𐤌', latin: 'ym', meaning: { en: 'Sea', fr: 'Mer', ar: 'بحر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤍𐤒', latin: 'ynq', meaning: { en: 'To suckle', fr: 'Téter', ar: 'يرضع' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤎𐤃', latin: 'ysd', meaning: { en: 'Foundation, to found', fr: 'Fondation, fonder', ar: 'أساس، يؤسس' }, grammar: { pos: 'Noun', gender: 'm', number: 's', notes: 'Also a verb.' } },
  { phoenician: '𐤉𐤎𐤐', latin: 'ysp', meaning: { en: 'To add, increase', fr: 'Ajouter, augmenter', ar: 'يضيف، يزيد' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤎𐤓', latin: 'ysr', meaning: { en: 'To discipline', fr: 'Discipliner', ar: 'يؤدب' }, grammar: { pos: 'Verb', stem: 'D-stem' } },
  { phoenician: '𐤉𐤏𐤑', latin: "yʿṣ", meaning: { en: 'To advise, counsel', fr: 'Conseiller', ar: 'ينصح، يشير' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤏𐤓', latin: "yʿr", meaning: { en: 'Forest', fr: 'Forêt', ar: 'غابة' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤐𐤄', latin: 'yph', meaning: { en: 'Beautiful', fr: 'Beau', ar: 'جميل' }, grammar: { pos: 'Adjective' } },
  { phoenician: '𐤉𐤑𐤀', latin: "yṣ'", meaning: { en: 'To go out', fr: 'Sortir', ar: 'يخرج' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤑𐤁', latin: 'yṣb', meaning: { en: 'To place, set', fr: 'Placer, poser', ar: 'يضع، ينصب' }, grammar: { pos: 'Verb', stem: 'C-stem' } },
  { phoenician: '𐤉𐤑𐤓', latin: 'yṣr', meaning: { en: 'To form, potter', fr: 'Former, potier', ar: 'يشكل، خزاف' }, grammar: { pos: 'Verb', stem: 'G-stem', notes: 'Also a noun.' } },
  { phoenician: '𐤉𐤒𐤑', latin: 'yqṣ', meaning: { en: 'To awake', fr: 'Se réveiller', ar: 'يستيقظ' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤒𐤓', latin: 'yqr', meaning: { en: 'Precious, honor', fr: 'Précieux, honneur', ar: 'ثمين، كرامة' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤉𐤓𐤀', latin: "yr'", meaning: { en: 'To fear', fr: 'Craindre', ar: 'يخاف' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤓𐤃', latin: 'yrd', meaning: { en: 'To go down', fr: 'Descendre', ar: 'ينزل' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤓𐤇', latin: 'yrḥ', meaning: { en: 'Moon, month', fr: 'Lune, mois', ar: 'قمر، شهر' }, grammar: { pos: 'Noun', gender: 'm', number: 's' } },
  { phoenician: '𐤉𐤓𐤒', latin: 'yrq', meaning: { en: 'Green, vegetable', fr: 'Vert, légume', ar: 'أخضر، خضار' }, grammar: { pos: 'Adjective', notes: 'Also a noun.' } },
  { phoenician: '𐤉𐤓𐤔', latin: 'yrš', meaning: { en: 'To inherit', fr: 'Hériter', ar: 'يرث' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤔', latin: 'yš', meaning: { en: 'There is', fr: 'Il y a', ar: 'يوجد' }, grammar: { pos: 'Particle' } },
  { phoenician: '𐤉𐤔𐤁', latin: 'yšb', meaning: { en: 'To sit, dwell', fr: 'S\'asseoir, habiter', ar: 'يجلس، يسكن' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
  { phoenician: '𐤉𐤔𐤍', latin: 'yšn', meaning: { en: 'To sleep', fr: 'Dormir', ar: 'ينام' }, grammar: { pos: 'Verb', stem: 'G-stem' } },
];
